### ISSUE TITLE
[Feature Request][UX] Animation on shape accept and reject 

### ISSUE THREAD

**Issue by goktugyil** [tobspr/shapez.io#1004]
https://prnt.sc/vqtvns

I'm sending multiple items, and as production increases it gets harder to pinpoint what shape counts and what doesn't count for the campaign. A little color, animation, size increase/decrease, etc.. on the inputs would help to easily differentiate if the item is accepted or rejected.

**Comment by EmeraldBlock** [comment]
What do you mean by accept/reject? All shapes that enter hub are stored in the hub. If you mean whether or not a shape is a goal shape, I feel that such a feature might be too excessive.

**Comment by goktugyil** [comment]
Either a goal shape or something you're tracking

**Comment by tobspr** [comment]
Tracking here: https://trello.com/c/q7k7mfBV/503-indicate-on-hub-when-a-relevant-shape-got-accepted
