### ISSUE TITLE
event.keyCode deprecated

### ISSUE THREAD

**Issue by mexanga** [tobspr/shapez.io#1005]
event.keyCode is deprecated, more informations here : https://developer.mozilla.org/fr/docs/Web/API/KeyboardEvent/keyCode

Should we use event.key instead ?

**Comment by tobspr** [comment]
I don't think thats a problem, major browsers will still support it, the deprecation just means "dont use this in future projects"

**Comment by tobspr** [comment]
(Feel free to make a PR tho)
