### ISSUE TITLE
Anything I can do to save myself from the game's revenge?

### ISSUE THREAD

**Issue by boiimakillu** [tobspr/shapez.io#1008]
Yesterday, after playing some and making some decent progress, I decided to make an Issue here, suggesting two features for waypoint management and hopping. Apparently, the game has an issue with that, as today when I booted it up, I was greeted with a notice that my save files had corrupted. Oh well, proably be able to find them somewhere in my files, right? Kind of. Managed to find the file, so it didn't get deleted. However, when I manually plug it in to Shapez, it tells me "`Error: bad-content / decompression-failed`". Am I screwed, or could I maybe try going into the file with some editor and at least salvage something?
I attached my BIN here, if that helps (I had to ZIP it or else Github complained).
Thanks guy!

[savegame-b3f940102f36f28a441e47f74e88aab7b5a69350.zip](https://github.com/tobspr/shapez.io/files/5644499/savegame-b3f940102f36f28a441e47f74e88aab7b5a69350.zip)

**Comment by EmeraldBlock** [comment]
Please only open an issue only if you believe the game itself is doing something wrong! Ask on the discord server or similar for that. **Though if you force-closed the game or the game crashed while saving, there is the known issue that it will corrupt the save.**

About your savegame, it's completely full of null characters, so basically no hope of recovering it from that.
