### ISSUE TITLE
Display breaks regularly

### ISSUE THREAD

**Issue by OakAndAspen** [tobspr/shapez.io#1011]
Hi guys,

I have this issue where the display keeps breaking (see screenshot below). At first it happened only occasionally and going to the settings and back would usually solve the problem. Now it happens every few minutes and I have to quit and restart the game for it to work normally again, it's very annoying. I don't have a lot of buildings nor crazy big ones, I'm careful to clean up regularly and pause the factories that aren't useful at the moment, so it shouldn't be related to that.

Anyone have an idea what might be causing this and how to fix it? I'm on Windows 10 Pro, on the Steam Standalone version.

![2020-12-05 17_24_47-shapez io Standalone](https://user-images.githubusercontent.com/28052156/101256638-bb404f80-371f-11eb-9f29-715ea7ccad11.png)

**Comment by EmeraldBlock** [comment]
It's caused by running out of VRAM, I think. No idea how to fix it, it's pretty well known

**Comment by tobspr** [comment]
Yup, no idea how to fix, sorry :/

**Comment by MrSlimbrowser** [comment]
How does closing unfixed issues help? Only makes it harder to find for people having the same problem.

However, I don't think it's a vram issue, at least if the vram usage that GPU-Z shows is correct with Intel UHD graphics.
As seen on the screenshot, when the issue happens cpu usage suddenly goes up and gpu load goes down while vram usage stays the same.

I'm wondering though, does it only happen on specific systems or using specific graphics cards?
For me, it happens on a Lenovo Thinkpad T490 with a  i7-8565U and it's integrated Intel UHD 620.
