### ISSUE TITLE
Rotated trash icon when using blueprint

### ISSUE THREAD

**Issue by aldebaran1997** [tobspr/shapez.io#1037]
The trash building cannot be rotated by normal means, such as pressing R key.
However, I found that the trash buildings are rotated when I blueprint them and then pressing R key.
There's no problem on their functionality, but I think it is unintentional, so I report it here anyway.

I'm playing purchased Steam version on Windows 10 by the way in case it helps you.

**Comment by TcePrepK** [comment]
Known it is easter egg please close this issue

**Comment by EmeraldBlock** [comment]
Duplicate of #1020, too

**Comment by aldebaran1997** [comment]
Sorry, I didn't know that...
