### ISSUE TITLE
Impossible shape

### ISSUE THREAD

**Issue by clcondorcet** [tobspr/shapez.io#1041]
I am level 20 but the game given me this shape to do: RuCw--Cw:----Ru--
![image](https://user-images.githubusercontent.com/21207509/103181574-c3b12380-48a2-11eb-8ec9-e79597f69c4d.png)
![image](https://user-images.githubusercontent.com/21207509/103181579-cdd32200-48a2-11eb-8075-1625da8348a1.png)

I think that this shape is impossible to make.
I first tried to combine RuCw--Cw with ----Ru-- but of course that gives me RuCwRuCw
![image](https://user-images.githubusercontent.com/21207509/103181628-7c776280-48a3-11eb-8a2f-8fd4c33b28ff.png)

So I tried something else:
I tried to make the --------:----Ru-- shape
So I cut a corner of a shape like so: RuRu--Su
and I add a shape on top wich is: RuRuRuSu (this shape doen't matter, it's just the bottom right corner that must be a Ru)
and so I obtained: RuRu--Su:RuRuRuSu
Then I tried to cut the bottom right corner to have --------:----Ru-- 
But of course it gives me: ----Ru-- back...
![image](https://user-images.githubusercontent.com/21207509/103181699-3b338280-48a4-11eb-965c-c75528c1a292.png)

So I think this shape is impossible to do and that's a big problem because I can't continue my game ...

My question is: Is this shape really impossible ?

If no how can I do it ?
If yes, how can I debug my game ?

**Comment by EmeraldBlock** [comment]
It's possible. (If it was a real issue, it would long have been reported, lol) Ask on the discord if you want a solution, though here's a hint:
<details><summary>Hint</summary>You can only keep the small square small if something is in the bottom layer (but that something doesn't have to be directly underneath the small square).</details>

**Comment by clcondorcet** [comment]
Oh ok I see ... hmm It's not simple ... But ok thanks
