### ISSUE TITLE
[Possible bug] Missing textures after dev-branch workspace is restarted

### ISSUE THREAD

**Issue by WMays287** [tobspr/shapez.io#1054]
After restarting a GitPod workspace of Shapez.io, a lot of the textures (specifically **all of the building textures**) seem to self-destruct. They're just gone, and the game engine uses placeholder textures; red boxes with question marks. Why do the textures go _poof_ after a workspace restart, and is this actually a bug or am I missing something?
![Screenshot showing missing textures](https://user-images.githubusercontent.com/60365549/104214670-bd27bd80-5405-11eb-91be-68650416f406.png)

**Comment by EmeraldBlock** [comment]
If I remember correctly, the dev build of the game does not guarantee the textures loading (really not sure about specifics). Does restarting again fix it?

**Comment by WMays287** [comment]
Yes, the textures return after the workspace is restarted again. I'm gonna try editing the config file to see what I get.

**Comment by mamamia5x** [comment]
When does this happen? Whenever I turn the Sandbox mode on, I get this, but if I leave it off it works fine.

**Comment by WMays287** [comment]
I'm assuming Sandbox mode is on by default, because these issues were occurring with the stock config file.

**Comment by mamamia5x** [comment]
In query_parameters.js in js/core folder it says
```js
export let queryParamOptions = {
    embedProvider: null,
    fullVersion: false,
    sandboxMode: false,
};
```
If I change sandbox to true, it turns the graphics off (or somethin)

**Comment by WMays287** [comment]
```javascript
export let queryParamOptions = {
    embedProvider: null,
    fullVersion: true,
    sandboxMode: false,
};
```
This seems to fix the graphics ¯\_(ツ)_/¯ Maybe the full version would be more concerned about consistent texture loading, since it's the version which would be published to Steam/Itch?

**Comment by EmeraldBlock** [comment]
Those options are not what control how the game is built; they're used in the beta build and can be changed using query strings, and I don't think they affect textures.

**Comment by WMays287** [comment]
Heck
![Screenshot_2021-01-11_13-24-02](https://user-images.githubusercontent.com/60365549/104222519-6b386500-5410-11eb-863b-4ea24ee8f7a7.png)

**Comment by EmeraldBlock** [comment]
If you open the inspect console, is there anything like "Failed to load..."?

**Comment by mamamia5x** [comment]
Is it a browser based issue at all?

**Comment by WMays287** [comment]
@EmeraldBlock Yes, it failed to load the 3 texture atlas files.
@mamamia5x I think so, but I'm not positive.

A dumped version of the inspect console can be found [here.](https://pastebin.com/MwTGXGii)

**Comment by mamamia5x** [comment]
On lines 84 and 85 there is an error that states
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8001/v1/register. (Reason: CORS request did not succeed).
```
On https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed it says
```
As of Firefox 68, https pages are not permitted to access http://localhost, although this may be changed by Bug 1488740.
```
It looks like Firefox doesn't allow localhost to access these files for some reason. Try using Chrome and if desperate use Edge.

**Comment by EmeraldBlock** [comment]
If I recall correctly, that is used for local game analytics, so it shouldn't affect anything.

**Comment by mamamia5x** [comment]
Yeah, if this were to be the actual site, this wouldn't be an issue.

**Comment by WMays287** [comment]
I tried hosting it locally (The only reasons it failed before were a missing python2 header lib (which might not even be necessary) and I forgot to use 'sudo') and it worked perfectly! Even restarted the server, textures were still good. Just have to figure out how to repeat this process on Windows........

**Comment by WMays287** [comment]
I'm not gonna repeat the process on Windows, USB dual-boot is a better option. The textures are still screwy, but I realized the server restarts pretty quickly when it's not running on the cloud :P

**Comment by dengr1065** [comment]
Hey! Since the debug build was made to run on localhost and local network only, **atlas load time is limited to 500 ms**, to allow detecting build issues early. This does not happen for localhost because the requests complete fast enough, and only happens sometimes because Firefox does a hard reload only every second time. (Also, this happens usually on slow machines like mine)
