### ISSUE TITLE
Red box with ???

### ISSUE THREAD

**Issue by Hacks-lol** [tobspr/shapez.io#1081]
hello! my school has blocked this can i add the assets manually?

becuz its just a bunch of red with "???"

**Comment by EmeraldBlock** [comment]
You possibly could, maybe local overrides in Chrome or something...
...but what exactly is going on? Is the website not blocked but the resources are? And this isn't really relevant to the game itself.

**Comment by Hacks-lol** [comment]
i fixed it :] Thanks for your help
