### ISSUE TITLE
[Bug] Leaving an underground belt into a belt corner then a splitter/merger/balancer lowers belt throughput.

### ISSUE THREAD

**Issue by Arescet** [tobspr/shapez.io#1103]
Having a full belt go through an underground segment, then a corner belt to turn into splitter/merger/balancer will lower the throughput. Not using an underground belt doesn't slow down throughput.

No underground belts, expected behavior.
![image](https://user-images.githubusercontent.com/24558724/111055999-6ceecb00-8449-11eb-92a1-3a55c7535b41.png)

Underground belts slowing down throughput.
![image](https://user-images.githubusercontent.com/24558724/111055990-5d6f8200-8449-11eb-9ec5-875257c636dc.png)

Both typed of underground belt have this issue, the underground length doesn't matter.

**Comment by EmeraldBlock** [comment]
Reminds me of something I did before...

Is this affected by tickrate and/or belt speed?

**Comment by Arescet** [comment]
> 
> 
> Reminds me of something I did before...
> 
> Is this affected by tickrate and/or belt speed?

My upgrade level is 78 (speed 24 belts) and tickrate was at 30. Forgot to mention that. 
Setting it to 60 fixes it.

On a different save at upgrade tier XXIII (speed x9.50) belt speed 18.99, tickrate 30 sets the max belt speed to exactly 15, and doesn't replicate the bug.. but has some odd behavior even at tickrate 60
![image](https://user-images.githubusercontent.com/24558724/111056277-bfc98200-844b-11eb-99ca-8ae6de59cd9e.png)

**Comment by tobspr** [comment]
Will be fixed with 1.5.0
