### ISSUE TITLE
Pressing "W" key while holding F4 crashes the game

### ISSUE THREAD

**Issue by headquarter8302** [tobspr/shapez.io#1132]
Title says all. I have seen the tip to hold F4 to see the cursor location and frames per second. I was trying to move the screen while holding F4, and an "Application crashed" prompt, nothing was broken or lost, just crashed.

I also need to add that I am doing this in the web build

**Comment by Aurumaker72** [comment]
Can't reproduce this on firefox, chrome or standalone.

**Comment by headquarter8302** [comment]
Hmm, can't seem to reproduce this too using Chrome, tried to use all variants of either pressing or holding F4, displays, and pressing or tapping W. I think this is just an isolated issue on my side

**Comment by headquarter8302** [comment]
Isolated incident, might be because a lack of memory
