### ISSUE TITLE
Please, how do we run from source with all dev/debug settings disabled?

### ISSUE THREAD

**Issue by elidoran** [tobspr/shapez.io#1139]
The README states: "Notice: This will produce a debug build with several debugging flags enabled. If you want to disable them, modify src/js/core/config.js."

It would be nice if those who know all the dev/debug stuff that's on is, would list them so we know what to change.

I changed the [IS_DEBUG](https://github.com/tobspr/shapez.io/blob/master/src/js/core/config.js#L1) to false and [IS_MAC](https://github.com/tobspr/shapez.io/blob/master/src/js/core/config.js#L10) to true.

The `G_IS_DEV` is somewhere else...

A problem I ran into is the "b" key. I change my keybindings to use the "b" key. Imagine my surprise when hitting "b" caused it to complete the current level. 

I like the idea of playing on my huge iMac screen instead of my small windows laptop... but, I'd like it to be able to play it without any dev/debug stuff going on.

thank you :)

**Comment by shelvacu** [comment]
You should be able to add `?nodebug` to the end of the URL to disable all dev/debug features.
