### ISSUE TITLE
tunnel planner similar to belt planner?

### ISSUE THREAD

**Issue by elidoran** [tobspr/shapez.io#1141]
What do you think about making a "tunnel planner" mode similar to belt planner?

It would be nice if we could go into a "tunnel planner" mode, similar to belt planner, which would do two helpful things:

1. show the line from the tunnel entrance to exit with directional arrows for the tunnels direction, just like the belt planner
2. create the tunnel in the direction we dragged the planner, just like the belt planner, and, allow ALT to have it create the tunnel in the reverse direction, also just like the belt planner.

I think this would be helpful when placing tunnels so we can simply go to tunnel mode, hold shift for tunnel planner, and click+drag to place a tunnel in that direction.

**Comment by tobspr** [comment]
Not planned but could be a mod :)
