### ISSUE TITLE
efficiency/speed indicator light on buildings?

### ISSUE THREAD

**Issue by elidoran** [tobspr/shapez.io#1143]
What do you think about adding an indicator light to buildings? Basically, a small circular colored orb somewhere on its surface with different colors indicating:

1. it's not doing any work: red
2. it's doing work, but, not much: yellow
3. it's doing a lot of work, but, not 100%: green
4. it's operating at 100% of the speed it's capable of: white

This would help to spot buildings that are not doing what they're supposed to. Anyone make a belt placement mistake and one of ur painters isn't doing any painting? Well, this indicator light would make that one stand out with a little red indicator light.

Ever wonder if ur "stacker factory" is operating at 100%? This would help by showing the green indicator meaning they're close but not 100%, and them all having the white indicator would mean the overall factory is cranking away at 100%, yay.

Perhaps the green "not quite 100% yet" indicator could have a configuration option in the settings to choose a percentage, like ">=98%" is white... so the player may choose the efficiency levels... I suppose it could be a list of colors and the percentage ranges... with 0% always being red and 100% always being white regardless of other settings (like having 0% to 10%) be considered red, and 95% to 100% be white).

This could be unlocked at higher levels than the belt reader.

Also, it could provide a tooltip/popup on mouseover which shows the exact speed the building is averaging.

**Comment by EmeraldBlock** [comment]
Personally, I think the belt reader is adequate: part of the charm comes from each building doing its own thing, so I feel any such improvements should be made to the belt reader itself.

**Comment by tobspr** [comment]
This is not planned for the base game but could be a potential mod :)
