### ISSUE TITLE
belt planner places tunnels to hop over other belts automatically ?

### ISSUE THREAD

**Issue by elidoran** [tobspr/shapez.io#1145]
It seems like it'd be easy to have the belt planner put tunnels to hop over another belt, or two, or four. If it isn't desirable to have it do this for all belt placements, whether using the planner or not, or pasting belts, then perhaps a keybinding along with the belt planner keybinding to enable auto placing tunnels.

**Comment by tobspr** [comment]
Not planned, could be a mod. But 1.5.0 will show when crossing belts or other buildings
