### ISSUE TITLE
Confirmation for placing long belts that intersect other factories

### ISSUE THREAD

**Issue by nicholassmeaton** [tobspr/shapez.io#1149]
I accidentally placed a belt across pretty much all my factories, severing connections all over the place. I had to abandon that save game because the thought of manually repairing all the broken connection was too daunting.

A solution to that problem would be to implement a confirmation dialog like the one that appears when cutting or deleting a large number of objects.

eg: if belt intersects over 20 other belts, show confirmation dialog.

**Comment by shelvacu** [comment]
Could also show as an icon next to your cursor if the belt is currently crossing any other belts/buildings

**Comment by tobspr** [comment]
Coming with 1.5.0 :)
