### ISSUE TITLE
Linux build for Steam

### ISSUE THREAD

**Issue by opl-** [tobspr/shapez.io#115]
I grabbed the Steam version of the game but was slightly disappointed to see that you don't distribute a native Electron binary for Linux. For some reason the game doesn't want to run through wine/proton (it starts but no window appears) and having native support for Linux hopefully shouldn't be too difficult.

While here I'd also like to mention that I love the simple yet highly addictive nature of the game and it being open source makes it even better.

**Comment by tobspr** [comment]
Hey, I'll work on linux builds now! :)

**Comment by tobspr** [comment]
Linux builds are now on steam! :)
