### ISSUE TITLE
[Bug] Corrupted save after system crash

### ISSUE THREAD

**Issue by mdavidn** [tobspr/shapez.io#1167]
shapez.io should automatically recover from crashes during a save.

My computer hard froze while playing version 1.3.1 @ 12c7937. After I rebooted and relaunched the game, the game displayed the [alert in preload.js](https://github.com/tobspr/shapez.io/blob/12c79370e45d34f4461235cd27ab8c982f7b8da0/src/js/states/preload.js#L151-L153). This caused some panic, but I was able to recover by importing the largest file in the save directory.

One approach would be to write _every_ save into a new temporary file and then, as a final atomic operation, overwrite the old save by moving the new save on top of it. (Journaling in NTFS and ext4 makes this atomic. The temporary file must be on the same disk or volume, so prefer the same directory over `$TMPDIR`.)

Another idea would be to rotate through three autosave files. Incorporate a timestamp or game clock into the filename. Delete the fourth-oldest after each successful save. If the latest autosave is found to be corrupted, fallback on earlier autosaves.

**Comment by tobspr** [comment]
It already exactly does this, check out `writeFileSafe` in `electron/index.js`. Not sure why it got corrupted

**Comment by mdavidn** [comment]
Ah. Perhaps `writeFileSafe` needs to [`fsync`](https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fs_fsync_fd_callback) the temporary file before renaming it?
