### ISSUE TITLE
Steam-version save-game handling issue

### ISSUE THREAD

**Issue by insensitiveclod** [tobspr/shapez.io#1169]
I had been playing for a bit on my desktop (level 22), and decided i'd save and move to the laptop (bedside) instead.
Closed the desktop game properly (no force-quit), and moved to the laptop with about a minute in between.

For some reason, the laptop's savegame did not have any of the progress I had made on the desktop game, even though earlier this had worked fine. 
Worse, it had taken it's local 'level 20' progress and saved it over the cloud-based saves.

Checking back on the desktop, it now opened the game with only a level 20 savegame available to choose from.

Basically saying: there might be an issue with steam-saves in 1.31, at least when considering multiple machines.

I have checked the steam cloud files, and the -backup.bin file there also contains the level 20 save. It'd seem level22 save has gone to the gods-of-shapes.

It *may* be possible I inadvertently did something really stupid, without noticing it, but I was careful to close the game neatly and nicely . I am sure the auto-save must've saved the level22 game multiple times during the game (the floppy-logo blinking). It seems likely to me that the Laptop-game might have suffered a 'latent connection' to Steam; not being able to connect to Steam-cloud in time to show the cloud-based savegame, but connecting to Steam succesfully to SAVE the open game , started from local cached save file.

It might be fortituous to detect this happening and offer a way to proceed while saving a file started from an OLDER save-game than the one is available on cloud.

So, something like this:
- On starting play on save-game, store savegame-date in 'current_savegame_date'
- On autosave or exit: Check current_savegame_date against date of (updated?) savegame date
-    If current_savegame_date == savegame_date:
-      Save_like_normal
-    else:
-      Provide dialog indicating a savegame with > date than current_savegame_date exists
-      Offer to save in new slot
-    fi

This will still not catch issues with people opening a previously stored savegame on a machine without an internet-connection, however, unless there is a way to interact with steamcloud in such a manner that you can detect when you're online and incorporate a last_synched_date in the savegame instead; allowing resolving of offline plays.

Disclaimer: I have not checked the source. I do not know if this (or similar) mechanism is already in place and it just failed to work (or I did something exceedingly stupid without noticing).
Cheers for the great game.

**Comment by tobspr** [comment]
The game doesn't do anything with the savegames in respect to steam cloud, it just saves it on disk and steam takes care of syncing - so this sounds like a steam cloud issue to me, nothing we can really fix :/
