### ISSUE TITLE
[UI Bug] Quad Painter Preview Image

### ISSUE THREAD

**Issue by tdnzr** [tobspr/shapez.io#1175]
The Quad Painter's preview image has output that's inconsistent with the depicted machine. See attached screenshot; the bottom-most output should look like the two outputs above it.

![2021-05-25_12-13-54](https://user-images.githubusercontent.com/35105157/119481349-e44ab000-bd52-11eb-9c51-4b06a868ecef.png)

**Comment by albiini** [comment]
Your eyes are deceiving you, there are 4 output shapes in total, the 2 lowest are just overlapping because they're not out of the painter yet

**Comment by tdnzr** [comment]
... Wow, point taken. Though I mainly pointed this out because the preview for this item could presumably confuse for players who saw it for the first time, and that's so even if the output image is technically accurate.

**Comment by tobspr** [comment]
Feel free to make a PR with a better image :)
