### ISSUE TITLE
[QoL] Automatically create tunnels when building a conveyer across other conveyer

### ISSUE THREAD

**Issue by Kietyo** [tobspr/shapez.io#1179]
Similar to how in mindustry it will automatically create a junction when you cross another conveyer line. Although this game doesn't support junctions, the same idea can be applied by automatically creating a tunnel path when routing across a conveyer line.

**Comment by EmeraldBlock** [comment]
really late but just noticed, duplicate of #1145?

**Comment by tobspr** [comment]
Not planned, could be a mod. But 1.5.0 will show when crossing belts or other buildings
