### ISSUE TITLE
Wrong output speed by PAINTER (Double)?

### ISSUE THREAD

**Issue by PaulFroh** [tobspr/shapez.io#1193]
I assume that the speed from a Double Painter should be 4 items/s, given that the tooltip shows that the speed is 2 times/s x2. But I observe that the speed is always below 4.

![grafik](https://user-images.githubusercontent.com/33546628/120905496-ad2da600-c652-11eb-869a-962c136d4763.png)

**Comment by EmeraldBlock** [comment]
Duplicate of #842

**Comment by PaulFroh** [comment]
My fault, I thought I have read every issue. Sorry

**Comment by EmeraldBlock** [comment]
Make sure to read closed issues too, if you didn't (for example, searching with `is:issue double painter`)
