### ISSUE TITLE
GOG

### ISSUE THREAD

**Issue by Ratief** [tobspr/shapez.io#1212]
It would be nice if you would also sell the game on GOG! I always try to buy from them instead of Steam.

**Comment by 2016WUJI01** [comment]
Maybe the steam was easier use that GOG?

**Comment by tobspr** [comment]
I'm in contact but it's a lot of work to manage multiple platforms, also the version wouldn't have achievements, etc

**Comment by tobspr** [comment]
You can get it on itch.io though
