### ISSUE TITLE
Cutting flattens layers

### ISSUE THREAD

**Issue by jertje260** [tobspr/shapez.io#1256]
When trying to make `CbCuCbCu:Sr------:--CrSrCr:CwCwCwCw` I ran into the issue that layers get lowered when cutting. I don't know if this is intented behaviour, but it makes it a lot harder to create these kind of shapes.

As you can see from the picture below, the empty layer on certain parts gets removed.

![image](https://user-images.githubusercontent.com/4190287/124390843-af386280-dced-11eb-99cd-2b12c8fcfbed.png)

**Comment by jertje260** [comment]
Asked in the discord later, intentional behaviour

**Comment by EmeraldBlock** [comment]
Also note that this is a duplicate of #157 and #857
