### ISSUE TITLE
Puzzles/puzzle editor gets reset after going into settings

### ISSUE THREAD

**Issue by PiTheGuy** [tobspr/shapez.io#1263]
Whenever you go into the settings menu while in a puzzle (or the editor), the puzzle gets reset, removing all progress and forcing the player to replace all the buildings they previously placed.

**Comment by Bagel03** [comment]
This happens because the settings menu is a different game state than the puzzle, this is fixed in the main game because it saves the game before leaving. Under this logic, once we have normal saving for puzzles (I’ve seen a few requests for that) this should be resolved

**Comment by tobspr** [comment]
Planned! But low prio
