### ISSUE TITLE
MacOS Version Solution (workaround)?

### ISSUE THREAD

**Issue by Thesnake66six** [tobspr/shapez.io#1267]
Well, it's not pretty, but it might just work. I was looking through the Trello list and saw that allowing full progress on the browser version after purchasing the game on Steam was an idea. Maybe you could use this so that if a MacOS user buys the game from Steam, they could play the full experience through their browser even though it's Windows only. Just an idea and probably impossible for many reasons but I thought I'd share.

**Comment by zwollner** [comment]
MacOS users already have access to the full version in the browser, without needing to buy the game.
