### ISSUE TITLE
BUG: Levels instantly show as complete without producing a single target shape

### ISSUE THREAD

**Issue by demmerichs** [tobspr/shapez.io#1271]
Using commit 62b65049 and running with development mode I found that I could skip levels by creating a marker and start typing a name. As soon as I type the letter "p" like in "blueprints" it automatically jumps to the next level (with the screen introducing new tools, etc.).
Is this a "cheat" only active in dev mode for fast testing?

**Comment by Sense101** [comment]
Not a bug, its a debug feature

**Comment by EmeraldBlock** [comment]
yeah, when in dev mode `p` is a shortcut to advance level, regardless of state

**Comment by mciicrw** [comment]
Is there ways to disable this? I've been searching in `config.js` and `config.local` but didn't know which one to disable.
i'm also found this #1139 but after adding `?nodebug` in the end of url, i still can use the cheat/debug mode.

**Comment by EmeraldBlock** [comment]
it's no where special, check in like `hub.js` (or some file like that) for an if statement
