### ISSUE TITLE
Please don't push Chrome onto people.

### ISSUE THREAD

**Issue by navid-zamani** [tobspr/shapez.io#1273]
Chrome is evil malware by the manipulative fraud (“advertisement”) company Google, that spies on people and sells their privacy. It should never be used, let alone recommended.

There is no reason the game should be slower on Firefox.

Google just tries to kill all other browsers by constantly creating new APIs for literally no other reason than that. They admitted to it in internal e-mails. It's actually what the WhatWG was created for. Because the W3C would not allow such a fast pace of spaghetti code to be dumped into standards.

So please don’t use those hostile APIs. In any case, Firefox has all APIs necessary for such a game, and in many cases is faster than Chrome too.

If you're having trouble coding the game properly, so it doesn't give Chrome its advantage, at least don't blame it on other browsers, but please tell the situation how it actually is: That Google made it hard for you to make your game run the same everywhere.

Oh, and I hope you just cross-compiled the game to WASM and such. If not, can I suggest using Godot Engine for your next project? It does that automatically afaik, by letting you export for the web, and you can avoid all that browser platform-on-a-platform nonsense software design anti-pattern. :)

Thanks for keeping the web free of criminal organizations like Google. :)

**Comment by PeterTiny1** [comment]
It is in fact slower in Firefox (especially the latest release of Firefox), unless you're staying zoomed in and not moving around too much. Use some Chromium-based browser, they all count as "Chrome"

**Comment by EmeraldBlock** [comment]
(about other chromium-based browsers, also see #1248)

**Comment by navid-zamani** [comment]
Oh, that is sad. Although I did not find it slow here. Maybe things changed…

In any case, I will not ever feed Google's agenda. I'm not such a big fan of Firefox either anymore, but it's still better than being complicit in killing the last remaining competitor.

(I'll look into the Steam version. Although I generally boycot DRM, since it's functionally equivalent to robbery.)

**Comment by EmeraldBlock** [comment]
think you can just grab the executable and run it directly? (not sure if that's got problems though)

**Comment by tutacat** [comment]
Maybe rename text to "Chrome or a chromium-based browser" or just "try a different browser to speed up javascript"

But yes, Firefox (unlike most chromium-based browsers)
has many more privacy restrictions on JS, etc. causing some intensive web apps to run slightly slower

But there are some optimizations such as "javascript compilation" or WebAssembly
(though the latter is less supported because or privacy implications)

**Comment by tutacat** [comment]
> Oh, that is sad. Although I did not find it slow here. Maybe things changed…
> 
> In any case, I will not ever feed Google's agenda. I'm not such a big fan of Firefox either anymore, but it's still better than being complicit in killing the last remaining competitor.
> 
> (I'll look into the Steam version. Although I generally boycot DRM, since it's functionally equivalent to robbery.)

If you have a slightly slower computer, or you get very far in the online version (lots of machines and belts)
it can be slightly choppy in FF
