### ISSUE TITLE
(v 1.4.3) 2-in 2-out balancers output to only 1 side randomly 

### ISSUE THREAD

**Issue by Rincos926** [tobspr/shapez.io#1290]
![20210829202729_1](https://user-images.githubusercontent.com/20920034/131251191-a57b3c71-2a9d-4aad-b31a-586e95c1fb57.jpg)

Shown as the bottom setup, having 1 belt with 3.2/s green dye and 1 belt with 3.2/s blue dye into a balancer, and the output is combine into a single belt with 6.4/s rate, and one of the input seems to be switched line twice, from the setup the last output of top line is always green dye, and vice versa. With higher input rate the problem is gone. Desired result is similar to the top splitter/merger crossing setup

**Comment by tobspr** [comment]
Should be fixed with the next update
