### ISSUE TITLE
Vertical and horizontal flip for the cutter, stacker, painter and color mixer

### ISSUE THREAD

**Issue by Azertooth** [tobspr/shapez.io#1293]
imho is a really needed feature, it's on the roadmap or there's some mod that implement it?

**Comment by zwollner** [comment]
tobspr has said that it's not going to happen, and there are already mods for it.

**Comment by EmeraldBlock** [comment]
duplicate of #986

**Comment by Azertooth** [comment]
> 
> 
> tobspr has said that it's not going to happen, and there are already mods for it.

can you please link me the mod?

**Comment by darkwater4213** [comment]
> https://discord.gg/rWuYY839bF is one (seems there's no one official link)

Oh, thanks. Now I don't have to find one myself :)
