### ISSUE TITLE
Enhancement: "Eyedropper" tool

### ISSUE THREAD

**Issue by binarycow** [tobspr/shapez.io#13]
In Factorio, if I mouse over an existing entity, and press the "Q" key, my cursor now changes to allow me to place a copy of the existing entity.

I see that you already use "Q" to de-select an active "tool" (I have the multi-select option set).  I suggest that if no tool is selected, "Q" will automatically select the tool the mouse cursor is over.

**Comment by tobspr** [comment]
This is rather difficult, but I could probably get it to work with blueprints

**Comment by Dimava** [comment]
#32

**Comment by tobspr** [comment]
https://trello.com/c/sOJSH8Qz/49-allow-q-middle-mouse-button-to-pickup

**Comment by tobspr** [comment]
Moved to trello
