### ISSUE TITLE
Level complete without actually reaching goal

### ISSUE THREAD

**Issue by hephaisto** [tobspr/shapez.io#1301]
Twice now, I have completed a level without actually producing a single one of the required shapes. I'm absolutely positive about this happening, because I never actually have built the required buildings. Sometimes, I just pause the game (Esc) and minimize the browser window. Both times, the "level complete" happened shortly (<30s) after resuming the game.

I built the game locally, and I'm on 736fbaed42077b98fe6dabb52bb076d617427492.

**Comment by EmeraldBlock** [comment]
Are these story levels? (the ones ≤ 26, before freeplay)

Also, are the shapes of the levels you've skipped shapes you've sent for upgrades? (See <https://shapezio.fandom.com/wiki/Levels>)

**Comment by hephaisto** [comment]
Yes, they were story levels (16 and 18).
No, I have never created a single one of them. I usually pause the game after I reach a level. So I paused right after reaching levels 15 and 17. And after I resumed, the game said I completed 16/18.

**Comment by EmeraldBlock** [comment]
Oh yeah, did you ever press `p` around those times?

**Comment by hephaisto** [comment]
Chances are, that I did when placing a marker. Just right now, I placed one containing the letter P, so I definitely pressed this button. Is this of relevance when the textbox is active?

**Comment by EmeraldBlock** [comment]
in a dev build, the key `p` automatically levels you up, no matter what you're doing ingame.

It's here in the code if you want to remove it:
<https://github.com/tobspr/shapez.io/blob/58fe6e2f513c46553df53c2233d8c14098d23b06/src/js/game/hub_goals.js#L113-L120>

**Comment by hephaisto** [comment]
Oh, that's good to know. Thanks!
