### ISSUE TITLE
Typo in Faster achievement on Steam

### ISSUE THREAD

**Issue by shadow7412** [tobspr/shapez.io#1303]
![image](https://user-images.githubusercontent.com/286341/134262389-697d9887-3e2c-4dc1-82f0-0001974d1479.png)

Text says "upgades", but should be "upgrades". I grepped this repo to try and find it for a PR, but it doesn't appear to be defined here as far as I can tell. Is this something that needs to be fixed in Steam?

**Comment by EmeraldBlock** [comment]
yeah, steam achievements are edited in Steamworks by the developer

**Comment by shadow7412** [comment]
Makes sense. Should I leave this here so they can fix it up, or is it not applicable given it doesn't apply to the code in the github repo?

**Comment by EmeraldBlock** [comment]
I'd *guess* leave it open since there's not really any place else to open an issue

**Comment by tobspr** [comment]
Fixed it, thanks! :)
