### ISSUE TITLE
How to disable sandbox mode

### ISSUE THREAD

**Issue by mrhappy200** [tobspr/shapez.io#1310]
Hello, I bought the game on steam but prefer playing it online (and I might want to check out the code). So I would be hosting it myself for the full version (I get I could play the beta or something but I like my domain). *BUT* I cant find how to disable sandbox mode. I have tried rebuilding it with my /src/js/core/query_parameters.js  changed to say sandboxMode: false. But it is still using sandboxMode. 
# I don't get it, what am I doing wrong
###### sorry I enjoy markdown styling *a bit* too much.

**Comment by EmeraldBlock** [comment]
using headers as large text is bad semantics practice!

but I believe that file is for beta builds (which detect query string parameters). You can build a beta build, which I think is using `yarn gulp build.staging`

I think you can also disable dev features in dev builds by modifying `G_IS_DEV`, wherever it's defined (maybe there's something else, but not sure). But those builds aren't meant to be releases

**Comment by mrhappy200** [comment]
Ok,
So disabling `G_IS_DEV` bricked all the textures and put me in demo mode. What now.
also the beta version took a while to build en then completed without opening a browser or anything and if I then ran `yarn gulp` the normal way again I end up in the normal version with sandbox mode enabled

**Comment by EmeraldBlock** [comment]
no idea how to fix the `G_IS_DEV` problem, but the beta build just gives you files to host as a webpage

**Comment by mrhappy200** [comment]
Ah, ok
