### ISSUE TITLE
Mouse release events are not registered with Chromium on Linux

### ISSUE THREAD

**Issue by dpellegr** [tobspr/shapez.io#1316]
With Chromium 95 and 96 on Linux, whether I use the online demo, or build the game locally, it is totally unplayable as the release mouse events are not registered.

For instance, if I right click to delete an object, even after releasing the mouse button the game will keep deleting everything I hover on.
If I left click to pad the map, the map will keep padding even after releasing the mouse button.

The game works fine with Firefox (apart from the known performance issues) and used to work fine with much older versions of Chromium (I used to play it in the past, more than a year ago).

**Comment by tutacat** [comment]
Works fine on version 94 and 98

Try on a fresh chromium profile (top right, click the profile icon, select add)

Otherwise see if working for you on [dev channel (v98)](https://download-chromium.appspot.com/)

**Comment by dpellegr** [comment]
Yes, I suspect that it was my profile which became corrupted over the years, as I was having other random issues on different websites.

Thank you and sorry for the noise.
