### ISSUE TITLE
I'm confused

### ISSUE THREAD

**Issue by CubasticBanjo** [tobspr/shapez.io#1330]
How do I run my modified application in browser?

**Comment by EmeraldBlock** [comment]
vague title, don't open an issue for this, and do what the README says

**Comment by CubasticBanjo** [comment]
I can't understand it bro

**Comment by EmeraldBlock** [comment]
then follow <https://github.com/Hyperion-21/shapez.io/blob/clarify-readme/README.md#building>, and if there's anything you don't understand, search it up online

if you're still unable to run it I recommend gathering some experience with coding / command line / installing stuff and coming back in the future

**Comment by CubasticBanjo** [comment]
Hey emraldblock , I need ur help,my yarn is not getting installed in root folder

**Comment by CubasticBanjo** [comment]
its showing error
error An unexpected error occurred: "EPERM: operation not permitted, mkdir 'C:\\Windows\\node_modules'".
