### ISSUE TITLE
Level Complete message is skipped if you pass multiple levels

### ISSUE THREAD

**Issue by scribblemaniac** [tobspr/shapez.io#136]
If you fulfill the goals for multiple levels at the same time, only the Level Complete dialog for the last goal you fulfilled will be shown. For example if you collect enough squares to complete level 3 before you have enough semicircles to complete level 2, it will completely skip the level two complete message and and the message describing upgrades. As you can imagine, this can cause issues particularly when this happen in the lower levels where these messages are the only way you inform users about new buildings or mechanics.

Tested on version 1.1.11

**Comment by tobspr** [comment]
AH, uh. Yeah thats because it will instantly show up. hrm - not an easy fix

**Comment by tobspr** [comment]
No plans for fixing this RN
