### ISSUE TITLE
Feature request: Map image export

### ISSUE THREAD

**Issue by scribblemaniac** [tobspr/shapez.io#137]
I really like to see the designs my buildings make when I zoom out, and I'd like to be able to share that with others too. Taking a screenshot while zoomed out works, but only for an area small enough to fit completely in the window. So it would be nice to have some way to export the entire area that the user has built on as an image (PNG, etc.) like it appears in the zoomed out view except without all of the interface elements.

**Comment by tobspr** [comment]
Cool idea, yeah that is on my todo list. Actually let me start and implement this

**Comment by tobspr** [comment]
Will be in 1.1.11!

**Comment by scribblemaniac** [comment]
Tested at it works, thanks!
