### ISSUE TITLE
Movement keys "stick" when being held down during a level up popup

### ISSUE THREAD

**Issue by bbugh** [tobspr/shapez.io#14]
I'm not sure of the exact sequence, but if you're holding down a movement button (I was pressing A both times this happened) and a level up screen pops up, then the key gets stuck moving. Pressing the opposite direction (D) just stops the movement.

**Comment by dengr1065** [comment]
almost same happens with every game (minecraft <1.13 for example), you can just press `A` again to stop it

**Comment by tobspr** [comment]
Fixed
