### ISSUE TITLE
Shape viewer: example logo is wrong

### ISSUE THREAD

**Issue by Jadaw1n** [tobspr/shapez.io#1411]
Hi,

when clicking the "Logo shape" in the example section, it's showing up wrong, see screenshot. I'm assuming the shape code needs to be corrected :)

![image](https://user-images.githubusercontent.com/1271552/161404729-3562979c-414a-43b2-8122-016f8e212eaa.png)

**Comment by EmeraldBlock** [comment]
this issue should be reported over at <https://github.com/tobspr/shapez.io-viewer>!

**Comment by Tricorng2022** [comment]
It's because you typed it incorrectly :/

The correct way is `RuCw--Cw:----Ru--`

**Comment by r23angie-cmd** [comment]
You reversed the square and quarter-circle, it's instead RuCw--Cw:----Ru-- .
