### ISSUE TITLE
Viewer Logo shape is wrong

### ISSUE THREAD

**Issue by GoktugOzturk** [tobspr/shapez.io#1413]
Logo shape on [viewer ](https://viewer.shapez.io/) is displayed as `CuRw--Rw:----Cu--`

It should be `RuCw--Cw:----Ru--`

**Comment by dengr1065** [comment]
Issue #1411 was fixed by tobspr/shapez.io-viewer#29 few minutes ago. Please clear your browser cache and retry again!
