### ISSUE TITLE
Save game loading troubles

### ISSUE THREAD

**Issue by tneo** [tobspr/shapez.io#1414]
This is a tough issue as it is not clear how I can provide the best way to replicate the behavior. 

When I open my save I may or may not be able to load the game. The save file is about 3MB in size and takes ages to load (I don't understand why that is). When it is successfully loaded I can fingers crossed play my save, as that is not clear either.

Today my save started throwing errors that the checksum was incorrect. Don't know how that would happen, as I saved it last night and just opened Shapez again. When I tried a couple of times again I did not have the checksum error again. Now my save most likely will not open and once I click on the load button my screen turns black. When it turns black it won't load (I've waited about 10 minutes). When it turns white with the loading icon it takes long to load, but it will succeed. There is a back-up in my saves directory, though that has the same time stamp as my last save.

Loosing the game is not the end of the world, but it hurts. How can I debug this issue to provide insight an hopefully a solution to my loading woes?

If it matters I'm running Steam under Linux.

**Comment by tneo** [comment]
![image](https://user-images.githubusercontent.com/6168186/164562327-2097ceed-d8ac-45e7-a9cf-44e0870cc993.png)

**Comment by EmeraldBlock** [comment]
if you don't mind, could you share or attach the savefile?

**Comment by tneo** [comment]
Sure.
[MAMv6.bin.tar.gz](https://github.com/tobspr/shapez.io/files/8535513/MAMv6.bin.tar.gz)
)

**Comment by EmeraldBlock** [comment]
can't really figure out much, though don't know much about this stuff; though, is the first checksum always `079ed4cc` before you manage to enter your save again? It seems maybe your game incorrectly calculates the checksum for the save contents

**Comment by tneo** [comment]
I received a pipewire update and that seems to have had a positive influence on my save game load. I'm closing this as it appears not related to Shapez itself.
