### ISSUE TITLE
New Shapez logo not updated for the puzzle Dlc

### ISSUE THREAD

**Issue by AnneHonyme** [tobspr/shapez.io#1439]
![shapezio_2022-06-16_16-40-48](https://user-images.githubusercontent.com/88263999/174160468-7114b27e-5986-4f3c-994a-96b34aad9dc2.png)
On the top left of the screen, there is still the old Shapez.io logo instead of the new Shapez logo

**Comment by tobspr** [comment]
Will be fixed with the next update :) It's already in the latest commit, so closing this issue for now
