### ISSUE TITLE
The windmill check should use `windmillCount > 2` instead of `windmillCount > 1`

### ISSUE THREAD

**Issue by ExE-Boss** [tobspr/shapez.io#1444]
This would allow shapes such as [<code>WuWu?u?u</code>][WuWu?u?u][^1] and [<code><img height="24" align="top" src="https://user-images.githubusercontent.com/3889017/174471636-c4869f34-9444-4734-8f8e-16a8fbe259f6.png" /> WuRuWuRu</code>][WuRuWuRu] to spawn naturally instead of being converted into [<code>RuRu?u?u</code>][RuRu?u?u][^1] and [<code><img height="24" align="top" src="https://user-images.githubusercontent.com/3889017/174471846-e3c1e2df-328e-4286-a466-123bde43495b.png" /> RuRuWuRu</code>][RuRuWuRu] respectively.

## See also
- <https://github.com/tobspr/shapez.io/pull/936>
- <https://github.com/tobspr/shapez.io/pull/1445>

[WuWu?u?u]: https://viewer.shapez.io/?WuWuSuCu
[RuRu?u?u]: https://viewer.shapez.io/?RuRuSuCu
[WuRuWuRu]: https://viewer.shapez.io/?WuRuWuRu
[RuRuWuRu]: https://viewer.shapez.io/?RuRuWuRu
[^1]: `?u` represents any non‑windmill piece

**Comment by tobspr** [comment]
See comment on PR :)
