### ISSUE TITLE
Possible improvements to layout on odd aspect ratios

### ISSUE THREAD

**Issue by baryluk** [tobspr/shapez.io#146]
Hi, love the game.

I use 1:1 monitor (Eizo EV2730Q), and noticed this when playing the demo:

![Screenshot at 2020-06-13 15-40-25](https://user-images.githubusercontent.com/110322/84573026-8913ed80-ad8d-11ea-92d0-9ea48468b147.png)

As you can see there is some overlap in few UI elements, and I feel the bottom toolbar is too big.

Small priority, but I am sure this can be fixes somehow :)  People with 4:3 and 3:2 aspect ratio screen probably might experience similar issue to me.

Most of the other screens are fine, albeit on my screen the look comically big:

![Screenshot at 2020-06-13 15-40-37](https://user-images.githubusercontent.com/110322/84573062-c9736b80-ad8d-11ea-9118-251cfef79dd5.png)
![Screenshot at 2020-06-13 15-40-33](https://user-images.githubusercontent.com/110322/84573067-d001e300-ad8d-11ea-8fbc-f38cbab794db.png)
![Screenshot at 2020-06-13 15-52-20](https://user-images.githubusercontent.com/110322/84573083-ef990b80-ad8d-11ea-84f9-748771374792.png)
![Screenshot at 2020-06-13 15-52-26](https://user-images.githubusercontent.com/110322/84573084-f031a200-ad8d-11ea-959f-565e1d8db1b8.png)
![Screenshot at 2020-06-13 15-52-32](https://user-images.githubusercontent.com/110322/84573085-f031a200-ad8d-11ea-981a-1321aec8e0f9.png)
![Screenshot at 2020-06-13 15-53-40](https://user-images.githubusercontent.com/110322/84573123-1d7e5000-ad8e-11ea-9965-78bb2d4d32fb.png)
![Screenshot at 2020-06-13 15-53-48](https://user-images.githubusercontent.com/110322/84573125-1e16e680-ad8e-11ea-8f90-aa5e79610935.png)

**Comment by baryluk** [comment]
Oh, I noticed there is "Super small" interface scale in the settings, and this kind of makes it better:

![Screenshot at 2020-06-13 15-55-51](https://user-images.githubusercontent.com/110322/84573196-7bab3300-ad8e-11ea-8a7a-f068c1589ed1.png)


And other screens are now sized decently too.

But I still think the first screenshot from the first post above is a bit of a bug, and should work better in default settings.

**Comment by tobspr** [comment]
Closing since its a rare issue and there is a workaround
