### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by JaccoGoris** [tobspr/shapez.io#147]
Hi Tobias,
First off, really cool stuff!

Secondly, I saw the Linux thread, but didn't want to re-open that one for this (I don't know which you prefer but this seams more clean)

Is it difficult to create a mac version for steam? I can help out potentially (Frontend and iOS developer)
I checked in on discord and saw that there is also other demand for this. So maybe we can put our head together to setup the pipe to generate mac builds too. So I can actually play it :D

**Comment by tobspr** [comment]
The issue here is signing the apps - I don't have a mac available right now and I can't do that on windows :)

**Comment by JaccoGoris** [comment]
https://www.electronjs.org/docs/tutorial/code-signing
I think we can work around this by using electron-forge or electron-builder to do it on CI, so you don't need a mac :)

**Comment by miguelslemos** [comment]
Yep, https://www.bitrise.io/pricing is free for open source. I could help to setup CI/CD environment too

**Comment by tobspr** [comment]
@miguelslemos would be nice! Feel free to make a PR and let me know what you'd need from me :)

**Comment by skandragon** [comment]
I'm happy to test and perhaps help.  I do have a mac, and a signing key, and could probably work out other arrangements to make signing work.

**Comment by lafelong** [comment]
I think I've almost got a standalone build going on the Mac following the build instructions... but it fails with git errors?

Running yarn gulp from inside the gulp directory:
`Mac-Pro:gulp lafe$ yarn gulp
yarn run v1.22.4
$ gulp
Please set SHAPEZ_CLI_SERVER_HOST
Please set SHAPEZ_CLI_STAGING_FTP_USER
Please set SHAPEZ_CLI_STAGING_FTP_PW
Please set SHAPEZ_CLI_LIVE_FTP_USER
Please set SHAPEZ_CLI_LIVE_FTP_PW
fatal: Not a git repository (or any of the parent directories): .git
Error: Command failed: git rev-parse --short HEAD
fatal: Not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.getRevision (/Applications/shapez.io-master/gulp/buildutils.js:9:28)
    at Object.gulptasksCSS (/Applications/shapez.io-master/gulp/css.js:6:35)
    at Object.<anonymous> (/Applications/shapez.io-master/gulp/gulpfile.js:61:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
  ],
  pid: 19648,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
}
error Command failed with exit code 1.`

**Comment by tobspr** [comment]
Did you init it from git? Or did you just download a zip?

**Comment by fresnik** [comment]
Hey, just wanted to add that I have been playing the demo in a browser and just love the game, so I bought it, but I will definitely buy it again if there's a mac version on Steam. 😉

**Comment by martinhanzik** [comment]
Something like https://github.com/samuelmeuli/action-electron-builder could be used to do this all in Github.

**Comment by tobspr** [comment]
Mac support isn't planned in the near future. So closing this one

**Comment by rasmuselmgren** [comment]
Hey! Would love to know the status on this? Mac version would be great!

**Comment by fresnik** [comment]
> MacOS is now supported

Great work! Just bought it again - thanks for the continued support.
