### ISSUE TITLE
Allow clicking to clear selection

### ISSUE THREAD

**Issue by Scarsz** [tobspr/shapez.io#150]
When you have buildings selected with ctrl+drag, you should be able to unselect by single clicking somewhere in addition to pressing escape. Of course click+dragging should still move the map though.

![](https://lol.scarsz.me/SPHljE/shapezio-1592075448.png)

**Comment by tobspr** [comment]
Thats hard to do because currently the game doesn't really distinguish between click and drag

**Comment by Scarsz** [comment]
Maybe you could check if the drag distance is small enough & if a selection has been made to clear it?

**Comment by tobspr** [comment]
Closing this because I won't get to it near future
