### ISSUE TITLE
Bug: Shapes increasing in size after a stack and cut

### ISSUE THREAD

**Issue by neilCrosswaite** [tobspr/shapez.io#157]
# Bug
I have listed two problems here about shapes changing size

## Stacker
When you stack a shape that includes a small shape it forces the shape to resize back into the bigger version as seen in this example. This impacts being able to finished level 18.

#### Example
The result:

![image](https://user-images.githubusercontent.com/43375279/84604456-13dc1180-ae8e-11ea-8502-94c67515d502.png)

The expected result (with some help from paint):
![image](https://user-images.githubusercontent.com/43375279/84604577-df1c8a00-ae8e-11ea-8213-0a172a423b8a.png)

## Cutter
I don't know if this is related or a new bug but I came across first and thought might have been a feature.

When you cut a small shape so it is on it's own it returns to the original size. 

#### Second Examples
![image](https://user-images.githubusercontent.com/43375279/84605016-e85b2600-ae91-11ea-93f4-f9dc214c617e.png)

![image](https://user-images.githubusercontent.com/43375279/84604828-b2697200-ae90-11ea-9fe0-c9b3a9175ff4.png)

**Comment by dengr1065** [comment]
stacker: counterintuitive, but technically not a bug. **will be changed soon**
cutter: there's an empty layer behind! it will be brought to bottom one.

**Comment by tobspr** [comment]
What @dengr1065 said. Will soon be obsolete

**Comment by cyantree** [comment]
Will the cutter part be obsolete too? If not, I've prepared a possible fix for it. I can also create a PR if wanted.

*shape_definition.js*
```javascript
    cloneFilteredByQuadrants(includeQuadrants) {
        const newLayers = this.internalCloneLayers();
        let lastNonEmptyLayer = -1;
        for (let layerIndex = 0; layerIndex < newLayers.length; ++layerIndex) {
            const quadrants = newLayers[layerIndex];
            let anyContents = false;
            for (let quadrantIndex = 0; quadrantIndex < 4; ++quadrantIndex) {
                if (includeQuadrants.indexOf(quadrantIndex) < 0) {
                    quadrants[quadrantIndex] = null;
                } else if (quadrants[quadrantIndex]) {
                    lastNonEmptyLayer = layerIndex;
                }
            }
        }

        // Remove top most empty layers which aren't needed anymore
        if (lastNonEmptyLayer !== newLayers.length - 1) {
            newLayers.splice(lastNonEmptyLayer + 1);
        }

        return new ShapeDefinition({ layers: newLayers });
    }
```

This works by not removing every empty layer but only the top most empty ones.

**Comment by LeeSaferite** [comment]
@dengr1065 @tobspr 
> stacker: counterintuitive, but technically not a bug. **will be changed soon**

Out of curiosity, regardless of things being changed soon, why would this be considered normal behavior?

**Comment by dengr1065** [comment]
stacker stacks per-layer, it's too hard to implement such logic accidentally :slightly_smiling_face:

**Comment by LeeSaferite** [comment]
So it's not simply stacking the full shape from the right on top of the shape from the left and instead iIt's stacking each quadrant from the right on the quadrant from the left?

**Comment by dengr1065** [comment]
it "moves/stacks" one layer from right shape on the left one, checking whether they can flatten
