### ISSUE TITLE
Bug: Changing Interface Scale option resets "pinned" "goals"

### ISSUE THREAD

**Issue by binarycow** [tobspr/shapez.io#16]
Steps to replicate:

- Enter the "Upgrades" menu
- Press the "pin" icon next to a couple of "goals"
- Note that the pinned goals are now present on the left side of the game
- Change the interface scale
- Game refreshes, all goals (except the level-specific one) are now unpinned.

**Comment by dengr1065** [comment]
pinned items aren't serialized at all

**Comment by tobspr** [comment]
Yes, i need to fix this (at some point)

**Comment by tobspr** [comment]
Fixed
