### ISSUE TITLE
Steam Cloud Win/Linux

### ISSUE THREAD

**Issue by FML128** [tobspr/shapez.io#163]
Steam Cloud seems to be not working between Windows and Linux.
(So saves from Windows won't show in Linux and otherwise)

**Comment by tobspr** [comment]
Thats a steam issue, I can't fix that ...

**Comment by FML128** [comment]
That's quite sad. Thanks anyway

**Comment by Lucki** [comment]
This is **not** a steam issue, that's your configuration issue.
Have a look here how to set it up: https://partner.steamgames.com/doc/features/cloud#steam_auto-cloud
Please give extra attention to the Root Overrides in the Unity example. (And please don't use LinuxHome there)

**Comment by tobspr** [comment]
Ah I see. Added to my todo list
