### ISSUE TITLE
Improvement: Quad Balancer

### ISSUE THREAD

**Issue by FML128** [tobspr/shapez.io#165]
Just like the regular balancer but for up to 4 lanes

**Comment by Quadrum1** [comment]
You can build a 4 lane balancer using tunnels and the normal balancer.
I don't think adding a single block would be good.

![4-Lane Balancer](https://user-images.githubusercontent.com/38959426/84663186-19346d00-af1d-11ea-838c-c7a0efd2f2bd.png)

**Comment by Andrej-in-ua** [comment]
These balancers will work: https://www.reddit.com/r/factorio/comments/9y4zjl/standard_56_67_and_78_balancers_dont_quite/e9y9215/

**Comment by tobspr** [comment]
Yeah a single block would be overkill
