### ISSUE TITLE
Feature Request: Fixed axis for belts

### ISSUE THREAD

**Issue by jnroesch** [tobspr/shapez.io#17]
When zooming out I would like to be able to draw the belts in a straight line over a huge distance. Maybe Holding down a key when dragging so that it stays on the same axis to Prevent "curvy lines".

**Comment by tobspr** [comment]
Plannned, but I haven't figured a good way for that yet

**Comment by tobspr** [comment]
https://trello.com/c/RjhjH7qS/118-direction-lock-to-place-belts-horizontally-vertically
Moved to trello
