### ISSUE TITLE
Add mirroring/flip to Blueprints.

### ISSUE THREAD

**Issue by Jonis326** [tobspr/shapez.io#174]
It would be a nice feature for blueprinting. Sometimes rotating isn't enough.

**Comment by maweki** [comment]
> It would be a nice feature for blueprinting. Sometimes rotating isn't enough.

That would only work if all components (already) had a mirrored version. The output of the cutter need to be mirrored, as does the orientation of the painter.

**Comment by lipki** [comment]
So, it would be nice to have all the structures in a mirror version.
Which we could choose like the rotation, by pressing [M]

![all_orient](https://user-images.githubusercontent.com/401965/85136771-69bf0980-b240-11ea-9704-8d0601eed86c.png)
(I like to make pictures.)

**Comment by tobspr** [comment]
Appreciate the effort, but I don't think this will happen soon - Closing it thus.
