### ISSUE TITLE
Donation download link goes through a link tracker

### ISSUE THREAD

**Issue by PE1NUT** [tobspr/shapez.io#177]
Donated/bought the game a few days ago, and downloaded it. Apparently the game doesn't auto update, so I wanted to re-download to get the latest version. However, my browser (firefox with uBlock origin) now blocks the download because pstmrk.it is listed as a known tracking/ad site.

"uBlock Origin has prevented the following page from loading (...) 
Because of the following filter ||pstmrk.it^
Found in: Peter Lowe’s Ad and tracking server list 

moz-extension://b25a11c7-6398-4c40-93f7-39ab612aa91a/asset-viewer.html?url=plowe-0

Current version: 1.1.11 on Linux.

**Comment by tobspr** [comment]
Hey,

First of all, thanks! I can't really do anything about that, since thats an itch.io related problem I guess. You might want to contact them about that
