### ISSUE TITLE
Unable to build on linux

### ISSUE THREAD

**Issue by sigzegv** [tobspr/shapez.io#182]
```
Error: Missing binding /home/.../shapez.io/gulp/node_modules/node-sass/vendor/linux-x64-64/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 12.x
```

I don't understand anything with node versions when building this app :
- building with node 10 makes an error on fsevent, building with node 12 is ok
- running with node 12 complains it should be ran with node 10, but running with node 10 makes a dependency error on a item only available with node 12 (which I have already installed)

**Comment by dengr1065** [comment]
fsevents is an optional dependency which is required only for macos, is node 10 in your path? you should install node-sass while using node 10, using yarn - that works for me

**Comment by sigzegv** [comment]
I use nvm to switch to node 10 with `nvm use v10.0.0`

**Comment by dengr1065** [comment]
@tobspr close this as resolved (and it's not relevant anymore)
