### ISSUE TITLE
Improvement: Probing output rate

### ISSUE THREAD

**Issue by tonebacas** [tobspr/shapez.io#188]
This could be useful to identify bottlenecks in your pipeline.

You could display this stat under the mouse cursor while you press a modifier key, and it would display the number of shapes/colors/etc. per minute passing through that pipeline stage -- if it's a belt, look 'upstream' from that point in the pipeline for the last output stage like painting or cutting stations.

**Comment by tobspr** [comment]
Somebody could make a PR (feel free to!), but its nothing I have planned right now. Might change with the wires update
