### ISSUE TITLE
Minor bug: Glitch when simultaneously right and left clicking

### ISSUE THREAD

**Issue by Phlosioneer** [tobspr/shapez.io#189]
I had the upgrades screen opened and moused over the X. I then accidentally simultaneously (or nearly so) clicked with the right and left buttons.

The upgrades window close button was unresponsive to any more clicks.

Pressing the F key to toggle the upgrades window worked. Further use of the upgrades window works fine.

**Comment by tobspr** [comment]
Fixed by that pr :)
