### ISSUE TITLE
Game performance degradation

### ISSUE THREAD

**Issue by Andrej-in-ua** [tobspr/shapez.io#210]
When I completed tier-4 coloring receipt (mill + circ + mill ) - game performance "has gone away")
![image](https://user-images.githubusercontent.com/942574/84924548-580b2400-b0d1-11ea-894b-d4b4f3338b2f.png)

Savegame: 
[savegame-8ca2484b77df1447b7923dab5e719872945d09aa.zip](https://github.com/tobspr/shapez.io/files/4793983/savegame-8ca2484b77df1447b7923dab5e719872945d09aa.zip)

I have 31k belts and 9k structures:
![image](https://user-images.githubusercontent.com/942574/84924625-7709b600-b0d1-11ea-8cbf-767b6ecd7ee7.png)

Game consume only one of six processor cores and almost not use a graphics card:
![image](https://user-images.githubusercontent.com/942574/84924998-f9927580-b0d1-11ea-8b2e-5e4d3acc6d28.png)

P.S. Thanks for the game, it's really cool!

**Comment by tobspr** [comment]
Hey!

30,000 belts is already a lot - I'm constantly improving performance though!

**Comment by Joker-vD** [comment]
@tobspr I believe this FFF can be a useful inspiration for further optimizations: https://factorio.com/blog/post/fff-176

**Comment by tobspr** [comment]
I'll close this as its already on my todo list

@Joker-vD i know that article :)
