### ISSUE TITLE
Minor Bug: Sound Skipping when Dragging a Line of Belts

### ISSUE THREAD

**Issue by Okubyona** [tobspr/shapez.io#215]
The satisfying sound of placing belts now skips when quickly dragging down a line of belts. This really is just a minor issue, but I enjoy the sounds of each belt being placed.

I dunno what's causing this issue but, to hear each belt sound individually, I have to drag the mouse slowly.

**Comment by tobspr** [comment]
Moved to trello: https://trello.com/c/CFVeh6lT/196-allow-more-parallel-ui-sounds
