### ISSUE TITLE
Faster extraction with curved belt

### ISSUE THREAD

**Issue by Xan-Kun** [tobspr/shapez.io#220]
I am not sure if this is a bug, but strange behaviour definitely :-)

Version is still 1.1.15

The extraction output for a belt lane that has a curve *directly* at the start of the output, is faster, than the other ones.
Maybe I am overlooking something here, but I think it should be the same rates for all 4 lanes.

![shapez io_bug](https://user-images.githubusercontent.com/11686614/85008147-da8cf580-b15c-11ea-9a7f-24abb99d573d.PNG)

Thank you so much for this awesome game!

**Comment by tobspr** [comment]
This is a precision issue - If you set it to a higher tick rate it should go away :)
