### ISSUE TITLE
Differentiate immobile forms on conveyor belts.

### ISSUE THREAD

**Issue by lipki** [tobspr/shapez.io#228]
It is sometimes difficult to see the items moving on the conveyor belt, when the speed is constant.
Motionless forms for more than 1 second, could display a visual indication.
By changing the background color for example.

![conveyor_slower](https://user-images.githubusercontent.com/401965/85078373-96354000-b1c4-11ea-9cb7-270bcb07a91a.png)

**Comment by tobspr** [comment]
Hm, I think the main issue here is not seing the items moving. I'll figure out a fix.

Moved to trello https://trello.com/c/cl9Yqp9V/197-items-are-stationary-on-high-belt-speeds
