### ISSUE TITLE
A Compact separator (two in fact)

### ISSUE THREAD

**Issue by lipki** [tobspr/shapez.io#229]
Available at high levels, it would simplify the factory entries, like "MERGER" simplify the exits.

![small_separator](https://user-images.githubusercontent.com/401965/85080560-ccc18980-b1c9-11ea-8064-ca6679ae93db.png)
![usine](https://user-images.githubusercontent.com/401965/85080566-d1863d80-b1c9-11ea-90e8-6cfb9acb5d08.png)

**Comment by tobspr** [comment]
Planned! https://trello.com/c/NZPYb8bA/106-compact-mergers
