### ISSUE TITLE
Smart tunnels removing wrong belts

### ISSUE THREAD

**Issue by Andifaind** [tobspr/shapez.io#230]
Looks like smart tunnels are removing belts between the begin and the end that are facing in the same direction as the tunnel, but it's not always appropriate.

Like in this case:
![tunnel-error](https://user-images.githubusercontent.com/67031075/85082060-2b740c80-b1a4-11ea-8499-1e2752199100.gif)

It happens in all the directions, not just _left-to-right_.

However, seems to be removing only the belts:
![tunnel-error-2](https://user-images.githubusercontent.com/67031075/85082342-03d17400-b1a5-11ea-87cc-48f453c95a24.gif)

**Comment by Magos** [comment]
I made a fix for the cases displayed here which still leaves some cases possible but involves a minimum of extra performance spend. Not sure if tracing the full path of the belt to check if removal should happen is worth it.

**Comment by tobspr** [comment]
Moved to trello https://trello.com/c/FOD0v6n6/198-improve-smart-tunnel-placement-by-only-removing-a-whole-row-of-belts
