### ISSUE TITLE
String formatting bug

### ISSUE THREAD

**Issue by maks2x2** [tobspr/shapez.io#233]
Mistakenly displayed a special characters "\xa0" in number for thousands
![Screenshot_1](https://user-images.githubusercontent.com/17342513/85126034-d7763000-b256-11ea-897b-bf7a680bbee6.jpg)

Game version: Steam 1.1.15. Game language: russian. System language: russian. Windows 10 x64 1909

**Comment by tobspr** [comment]
I think there should be a fix out in 1.1.16 - if not, please reopen! :)

**Comment by firemdkfighter** [comment]
> I think there should be a fix out in 1.1.16 - if not, please reopen! :)
Yes. It's fixed. Thanks
