### ISSUE TITLE
Document Storage overflow/output behaviour

### ISSUE THREAD

**Issue by maweki** [tobspr/shapez.io#235]
The behaviour where the storage output preferably goes (important if you want to use it as an overflow gate) is not documented or visually discernible. It seems to want to go out of the left one, independent of the input, while the arrows suggest that on "empty" an item would always fall through.

![image](https://user-images.githubusercontent.com/613272/85140254-4ea2c880-b245-11ea-8d98-4b5894d845c0.png)

**Comment by tobspr** [comment]
Ah, hm. Suggestions?

**Comment by maweki** [comment]
What the current description/design suggests is the following behaviour (which would be cool): An item wants to go to the output corresponding to the input it went into. If there is no space, it tries the other one. If there is still no space, it goes into storage. The items from storage would use whatever is free (if both are free, well, who knows?).

I haven't looked into the code but I guess this isn't easily supported as you'd have to decide on the output on input.

An alternative would be adding a "preferring the left output" (or similar) to the description and making the left arrow darker and the right one lighter. Also the input arrows should skew slightly to the center and the output arrows should come from the center, suggesting that both outputs always draw from the pool and not from the inputs.

The suggested behaviour would support the overflow-gate on either output. The current implementation would need the overflow-gate always as the right output (which is fine, I guess, if that were documented).

**Comment by tobspr** [comment]
Moved to trello 
https://trello.com/c/7uWprXsL/269-mark-preferred-input-on-storage-visually
