### ISSUE TITLE
Conveyor belts in the wrong way.

### ISSUE THREAD

**Issue by lipki** [tobspr/shapez.io#236]
It is not clear when the conveyors are not in the right direction.
There could be a visual indication, when they face each other.

![front_off](https://user-images.githubusercontent.com/401965/85199130-85341e00-b2ed-11ea-80bf-4d8e7f1e5ad1.png)

**Comment by tobspr** [comment]
Good idea. Feel free to make a pr!

**Comment by lipki** [comment]
Challenge accepted but ... I make no commitment :)
I looked at the code, I have a lead, but ... well, we'll see.

**Comment by lipki** [comment]
In general, I think that it lacks indications on the buildings to show that it works or that it does not work.

**Comment by tobspr** [comment]
Check out the `ItemProcessor` system. The buildings currently don't track the history though. But you could make a counter: Decrease it by 1 / second if not currently producing. Increase by 1 / second if producing (Up to a max of 1). If the counter is < 0, show an indicator its not producing
