### ISSUE TITLE
Add an option to disable warnings

### ISSUE THREAD

**Issue by jimmyaffatigato** [tobspr/shapez.io#240]
Later in the game, situations frequently arise where it is necessary to cut or delete many buildings at once. In these cases, the game **always** asks for confirmation that requires using the mouse to click OK. It is an annoying speedbump at that point in the game. I noticed that the keybind to delete selected buildings is called "Confirm Mass Delete," but it doesn't dismiss this warning.

**Suggestions:**
- This warning prompt could accept [Enter] as OK and [Esc] as Cancel.
- Holding shift or ctrl when cutting or deleting could skip the warning prompt.
- Add an option under Settings to remove these prompts entirely.
- Rename keybind "Confirm Mass Delete" to "Remove" to be consistent with the hint that appears onscreen when multiple buildings are selected.

**Comment by tobspr** [comment]
This should be a very easy first issue.

Just change "ok:good" to "ok:good:enter" and "cancel:bad" to "cancel:bad:escape" or so

**Comment by tobspr** [comment]
Fixed in 1.1.17
