### ISSUE TITLE
Feature Suggestion: Hide shapes in stats panel

### ISSUE THREAD

**Issue by alyip98** [tobspr/shapez.io#242]
Later in the game, the production stats of raw and simple shapes becomes irrelevant. An option to hide shapes that players don't care about in the stats panel would help minimize visual clutter.

**Comment by tobspr** [comment]
Define "don't care about"

**Comment by dengr1065** [comment]
they mean "click <something> to hide shape" (or track "last delivered/produced" and filter?)

**Comment by alyip98** [comment]
> Define "don't care about"

Up to the player. But yeah a click to hide shape like @dengr1065 suggested would work fine. The use case is for mid-late game where I produce a hundred different intermediate products that I don't want to track, and I have to scroll up and down the "last delivered/produced" tab to find the stats of the shape I want to produce.

**Comment by tobspr** [comment]
Currently not planned
