### ISSUE TITLE
disable autosaves

### ISSUE THREAD

**Issue by JuicyJuuce** [tobspr/shapez.io#244]
With late game bases, autosaves can 10 seconds to complete, and at once a minute it turns into a real headache. A simple short-term solution would be to have a `disable-autosaves` command line option.

**Comment by tobspr** [comment]
I think a setting with values like "1 minute", "2 minutes", "5 minutes", "10 minutes", "20 minutes" and "disabled" would make sense and should be very simple to implement

**Comment by tobspr** [comment]
Will be in 1.1.17
