### ISSUE TITLE
Smart tunnel can delete belts that it isn't actually replacing

### ISSUE THREAD

**Issue by Kartoffelsaft** [tobspr/shapez.io#248]
Before:
![Screenshot from 2020-06-21 19-38-09](https://user-images.githubusercontent.com/39356821/85243460-c95f1580-b3f6-11ea-9d16-f2320b55308d.png)

After:
![Screenshot from 2020-06-21 19-38-18](https://user-images.githubusercontent.com/39356821/85243459-c8c67f00-b3f6-11ea-97db-28c609a04f47.png)

This can sometimes get annoying for me, especially when I'm compacting things and have to have weird belt layouts to do so. I encounter it quite a lot, so I'm guessing it's a known bug. Apologies if this is a duplicate.

**Comment by tobspr** [comment]
Known bug :) Will be fixed (soon)
