### ISSUE TITLE
PreventDefault on all recognized key presses to avoid triggering the firefox search function 

### ISSUE THREAD

**Issue by renanlecaro** [tobspr/shapez.io#254]
Hi
Just tried the demo today, and when i press "R" it rotates the building once, but it also opens the firefox "search in page" function. Then all further keypresses go to the searchbox and pressing R again has no effect. 

I'd suggest using preventDefault on all recognized keypresses, this is low priority obviously 

https://github.com/tobspr/shapez.io/blob/d09a593f811bef81493d9afdbf3a21a42dba84d9/src/js/core/input_distributor.js#L203

**Comment by tobspr** [comment]
Ah, I was actually assuming I'd already do that!

**Comment by dengr1065** [comment]
hmm, didn't trigger search for me in firefox, but did on seamonkey

**Comment by renanlecaro** [comment]
It's an option that needs to be turned in the Firefox settings page, something like "search on page when typing", so it probably affects very few users, but the fix should be quite trivial.

**Comment by tobspr** [comment]
harder to fix than I thought

**Comment by renanlecaro** [comment]
It would break all the regular text inputs in the app if it's applied globally, and it's probably hard to make it only prevent typing when the key press is used in the game. The fix on my side is just to disable the "type to search" option in FF, so I wouldn't spend too much time on this.

**Comment by tobspr** [comment]
Alright I'll close it for now

**Comment by roipoussiere** [comment]
I have the same issue on Firefox and it's really inconvenient when playing, so I'm in favor to reopen this.

> harder to fix than I thought

Why? `preventDefault(); ` does not work as expected?
