### ISSUE TITLE
Feature request: Mirror Blueprints

### ISSUE THREAD

**Issue by Jyntax** [tobspr/shapez.io#257]
It would be nice to have the option to mirror your Blueprints. To quickly build a huge Setup that's maybe fed Objects from the left and to mirror it so that you have a second Setup next to it that can be fed from the right - to double the output quickly without editing the Setup manually.

Best regards,
Jyntax

**Comment by maweki** [comment]
#174

**Comment by Sandwichs-del** [comment]
PR was closed before gerw showed he implemented all missing buildings :(

**Comment by tobspr** [comment]
https://trello.com/c/QlYfbg9c/270-allow-mirroring-blueprints-all-buildings
