### ISSUE TITLE
Bug: Blueprint belt rotation issue

### ISSUE THREAD

**Issue by NLZ** [tobspr/shapez.io#270]
The belt auto-rotation feature with blueprints are not perfect, look at the painter output in the exaple:

![image](https://user-images.githubusercontent.com/884277/85314263-86b24180-b4b9-11ea-911a-58f252763f8d.png)

So the belt is auto-rotated after the blueprint has been placed, but if you put more stuff after it (either manually or from blueprint) then it will correct itself. And even after deleting the placed stuff the belt rotation stays in the previous (correct) rotation.

Version: 1.1.17

**Comment by tobspr** [comment]
Hm, this is how the game works though - I'd say this is actually intended. Or does it cause any issues?

**Comment by NLZ** [comment]
Yeah, if I copy X and on the blueprint will also shown as X then I expect the pasted parts to become X, not change to Y.

**Comment by tobspr** [comment]
Okay, hm. I don't know if this is trivial to fix though

**Comment by NLZ** [comment]
Tested a bit, so the issue stems from that corner belt can be originated from two states. If it is from vertial (to-down) position then the bug happens, but not from the horizontal (to-left).

**Comment by hexagonhexagon** [comment]
Had to double check to make sure, but this is fixed by #297.

![test](https://user-images.githubusercontent.com/25755516/85788564-31657280-b6fb-11ea-9fc7-6178ff1c837f.png)

**Comment by tobspr** [comment]
Will be fixed with #297
