### ISSUE TITLE
Error merging shapes

### ISSUE THREAD

**Issue by pouc** [tobspr/shapez.io#277]
Hello,

When merging shape for next level upgrades, the small square becomes big (botom left)

![image](https://user-images.githubusercontent.com/4351056/85390901-bf016080-b549-11ea-922e-020b2b56df72.png)

is this normal ?

Thanks

**Comment by dengr1065** [comment]
Duplicate of #157

**Comment by pouc** [comment]
Merging the other way around works (small cube on the bottom layer)

![image](https://user-images.githubusercontent.com/4351056/85406790-99348580-b562-11ea-80f2-c31e1b897176.png)

**Comment by dengr1065** [comment]
yeah, we know

**Comment by hexagonhexagon** [comment]
See #138, #149.

**Comment by tobspr** [comment]
known bug

**Comment by tobspr** [comment]
https://trello.com/c/IcL69eaa/272-level-18-stacker-bug
