### ISSUE TITLE
Feature request; mirrored cutter

### ISSUE THREAD

**Issue by TheTrueSCU** [tobspr/shapez.io#284]
At one of the levels, you get the counter-clockwise rotate variant.  Could a mirrored cutter variant be added as a level perk?  Some layouts would be more pleasing and space efficient if you could place cutters \\/ instead of just // because a balancer can feed into both cutters directly.

**Comment by TheTrueSCU** [comment]
Can the stacker and the color mixer also have a mirrored version?
It appears the painter and advanced balancers are the only buildings to have mirrors available.

**Comment by tobspr** [comment]
https://trello.com/c/QlYfbg9c/270-allow-mirroring-blueprints-all-buildings
