### ISSUE TITLE
Feature request: Logic gate

### ISSUE THREAD

**Issue by bbarry** [tobspr/shapez.io#29]
I'd like a component that could swap two lanes if an input matches. 

I think it should be a 2 input, 3 output shape. On the input lanes A and B:

* A - item template
* B - test lane

Outputs:

* A - item template discard
* B - match lane
* C - no match lane

I think there should be 4 variants:

1. color matcher: accepts colors on both input lanes; outputs to match lane if colors match
2. shape matcher: color only; if input is a color, match if shape has that color; otherwise match all available quads on the template
3. shape matcher: shape only; shape input only; match all available quads on template
4. shape matcher: color and shape; shape input only; match all available quads on template

It would hold both inputs until there was one in each and room on all output lanes, perform the match and then output.

---

Reasoning: endgame right now is pretty weak. After you supply the last designed shape it gives you a random one. I think it would be nice if you built towards a programmable machine that you input a small loop of item templates that are production prototypes for a much larger build line thing.

**Comment by tobspr** [comment]
I first need to do some thoughts about this - I know about the endgame being weak though, I already have plans for that :)

**Comment by tobspr** [comment]
Will be done within the wires update
