### ISSUE TITLE
Cant bind action to TAB key

### ISSUE THREAD

**Issue by StarrrLiteNL** [tobspr/shapez.io#293]
You can't bind an action to the TAB key. After clicking the key behind an action the game asks for a key to be pressed. Pressing tab does nothing.

Steam version

**Comment by TristonStuart** [comment]
This is on all versions. I'll make a PR to fix.

**Comment by TristonStuart** [comment]
Looked into this. TAB is a default key bind in the game.

You could always make a feature request to overwrite default key binds but as I look into the code there is only Enter, Tab, and Esc.

**Comment by tobspr** [comment]
binding tab adds different issues which have to be fixed. Closing since I have no plans for doing this RN
