### ISSUE TITLE
Cutting a multiple layer shape not consistent

### ISSUE THREAD

**Issue by FraDiavolo7** [tobspr/shapez.io#300]
I'm working on the lvl VI improvment shape, and I have a surprizing behavior. 

Cutting the a shape in two does not present 2 halves of the shape I input, but adds a botoom left grey cube under the one already there...

This image is probably more explicit than any text...

![image](https://user-images.githubusercontent.com/4103768/85763640-261f4080-b715-11ea-96e1-445a8545a4e9.png)

I may be doing something wrong, but this looks like an inconsistency in the cutting process...

**Comment by FraDiavolo7** [comment]
I'm confused... after reloading a second time, I have a correct behavior...

**Comment by hexagonhexagon** [comment]
This is a known visual bug that hasn't been pinned down yet as to what is going on here.

**Comment by tobspr** [comment]
https://trello.com/c/IcL69eaa/272-level-18-stacker-bug
