### ISSUE TITLE
Feature Request: Search the overview for specific shapes

### ISSUE THREAD

**Issue by thulsadum** [tobspr/shapez.io#312]
In my opinion, it would be really nice when you would be able to search the overview (when you zoom out) for specific shapes using the [viewers](https://viewer.shapez.io/) syntax. Then, matching shapes would be highlighted (e.g. by enlargement or animation).

For example, you need a `CuCuCuRu` shape for blueprints. They are actually quite common, but you (or least me) can easily oversee them.  Thus, a search field where you can enter the shape's description and get them highlighted in the view would help a lot.

Optional extensions could be:

  * simplification of the shape description language to 4 characters dropping the colour: `CuCuCuRu` would reduce to `CCCR`
  * simultaneously search for rotated variants of the shape. i.e. `CCCR` (using the previously introduced 4 character syntax) would also search for `CCRC`, `CRCC`, `RCCC`
  * wildcards would be nice too, so `CC**`, where `*` can be any shape, would search for any shape which consists of a semi-circle on the right-hand side. This in combination with the search for rotated shapes would be a rather powerful search.

**Comment by tobspr** [comment]
https://trello.com/c/xNfaWCNj/274-allow-searching-for-specific-shapes
