### ISSUE TITLE
Blurry text, might be because of hardware acceleration

### ISSUE THREAD

**Issue by orchidalloy** [tobspr/shapez.io#317]
Hey, just bought this game, great work!

I have an issue where most text in the game menus becomes blurry sporadically. A particularly severe image example: ![image](https://user-images.githubusercontent.com/33796679/85912708-95bc2b00-b7fc-11ea-8038-0c45a082af2d.png)

I had this same problem in some Electron apps at some point, and I fixed that by turning off hardware acceleration in the app's own settings. I don't know the root cause or how to fix it on my end, but could you perhaps add an option to turn off hardware acceleration? (Assuming that's the cause)

Thanks.

**Comment by tobspr** [comment]
You can disable it with `--disable-gpu --force-cpu-draw` . You can set that in the steam launch options. Does that help?

**Comment by orchidalloy** [comment]
That works, thank you! Though obviously it would seem like it impacts FPS since rendering on the GPU is more efficient.

**Comment by tobspr** [comment]
Will be fixed once achievements are in
