### ISSUE TITLE
Steam Overlay

### ISSUE THREAD

**Issue by ShyPixie** [tobspr/shapez.io#322]
I has trying to take screenshots on Steam and I realize that Steam Overlay is not implemented in game. I search a little bit and found this plugin for node.js: https://github.com/greenheartgames/greenworks

It looks quite solid and easy to implement. Is anyone already working on it? Do you see any limitations or difficulties with that? I honestly didn't look at the game code.

**Comment by tobspr** [comment]
yorg.io 3 already has this and the engine supports it. I will switch once I add achievements - So I'll close this issue since its already on my todo list :)

**Comment by ShyPixie** [comment]
Nice to now, but I think the issues must be closed when resolved no? That's the reason github has milestones and all... if you keep a todo list outside git and closes issues it's the same to assign everything to you, so one can help you...

**Comment by tobspr** [comment]
I don't use the github issues :) I move everything to trello: https://trello.com/b/ISQncpJP/shapezio
