### ISSUE TITLE
Icon is not included in Linux packaging

### ISSUE THREAD

**Issue by braiam** [tobspr/shapez.io#323]
I was creating a desktop entry for shapez.io, but found that in the package for linux the icon is not present. Can it be included?

**Comment by tobspr** [comment]
https://github.com/tobspr/shapez.io/blob/master/artwork/icon.png

**Comment by braiam** [comment]
@tobspr I know, but I was planning on suggesting a .desktop entry for easier use by Linux users that are used to Windows "Extract and Run". If it's not included in the package for Linux, I can't do that without repackaging. I don't know how Steam handle this, but they seem to not include [the icon either](https://steamdb.info/depot/1318692/), which may or may not cause problems when creating desktop entries for the Applications Menu.
