### ISSUE TITLE
Bug: Speed 20 belts seem to only transport 15 items a second

### ISSUE THREAD

**Issue by Arescet** [tobspr/shapez.io#329]
I have my upgrades to all x10 speed, belts claim to be at 20 items a second, miners are at 4 items a second. I tested both chained and regular miners for each test.

5 chained miners
---
![image](https://user-images.githubusercontent.com/24558724/85938548-4c430d00-b8dc-11ea-88c6-94bad26f5a7f.png)
If i run this for 30 seconds, i get 450 items, despite 5 chained miners at 4 items a second outputting 20 items per second, an expected  600 items in 30 seconds.

5 manually combined miners
---
![image](https://user-images.githubusercontent.com/24558724/85938571-78f72480-b8dc-11ea-834a-d23e440e42e7.png)
Running this for 30 seconds produces 450 items as well. (Using compact mergers also produced 450 items in 30 seconds)

5 seperated miners
---
![image](https://user-images.githubusercontent.com/24558724/85938635-194d4900-b8dd-11ea-86f3-0a3f2ff21168.png)
Not making the belts push 20 items a second like this produces the expected 600 items in 30 seconds from the miners.

**Comment by tobspr** [comment]
https://trello.com/c/6VOiTNQF/275-buildings-and-belts-are-not-as-fast-as-they-claim-to-be-eg-15items-s-instead-of-20
