### ISSUE TITLE
Feature Request : use the same unit of time (min/sec)

### ISSUE THREAD

**Issue by KhanKudo** [tobspr/shapez.io#332]
I find it unnecessarily hard to check if all the items that you thougth were delivered to the hub actually are because the hub uses items/minute and everything else uses items/second.
I understand that some people prefer one over the other ( I prefer sec ) but regardless of what unit is chosen, everything should be the same unit ( if it's not too much work, an option in the settings to change the unit would be nice )

It's like the measurement system.
Everyone uses metric except America...

**Comment by tobspr** [comment]
https://trello.com/c/5sa66yxZ/276-switch-stats-to-itesm-second-instead-items-minute-in-hub-maybe-make-this-toggleable
