### ISSUE TITLE
Bug: Storage building only using single output

### ISSUE THREAD

**Issue by ger-ald** [tobspr/shapez.io#333]
So as I'm fooling around after finishing the final shape for the freeplay-mode, I try to see what happens when I put a lot of shapes into the hub at once. I filled some storage and connected all outputs to the hub. For a second or so, all storage empties into the hub and then this happens:
![image](https://user-images.githubusercontent.com/10982994/85956681-afd64480-b987-11ea-86c8-fbd030fc82d2.png)
As you can see all storage only outputs on one output.

Observations:
-If I disconnect all inputs of the storage the outputs will be used again.
-If I move so the hub is not in the viewport anymore all the outputs will also be used again. (But judging from distance between the shapes on the belt, not 100%)

Here is a screenshot where I just moved back to the hub:
![image](https://user-images.githubusercontent.com/10982994/85956629-53732500-b987-11ea-9481-3939da0a146d.png)
As you can see the second outputs just stopped working and apparently they weren't used at full capacity.

**Comment by Sandwichs-del** [comment]
This was intended as feature. One output is "primary", buffer outputs to the connected belt whenever it can. The other output is "overflow", buffer outputs there only when the primary belt is full.

An "overflow" building is very useful, but the overflow output should be visually marked to make that obvious. Also would be cool to see mirror version or a compact 1-to-2 overflow without buffer

**Comment by ger-ald** [comment]
Ok, that makes sense.
I was wondering why you'd want to buffer, because most of the times it means there is a 'problem' further up the chain. I would probably have figured it out if there was only one input.

**Comment by tobspr** [comment]
https://trello.com/c/7uWprXsL/269-mark-preferred-input-on-storage-visually
