### ISSUE TITLE
Blueprints: pasting doesn't preserve belt shape

### ISSUE THREAD

**Issue by bbugh** [tobspr/shapez.io#34]
First of all, blueprints are nice 👍. 

When pasting them, though, it looks like the system is still trying to smart-merge the belts. Here's a picture, left is the copy, middle is the blueprint, right is what happens when it's pasted. The arrow points to where the belt was automatically changed for the smart directions.

<img width="344" alt="Pasted_Image_5_29_20__6_32_AM" src="https://user-images.githubusercontent.com/438465/83255595-586d6a80-a176-11ea-99a1-fce04a186e3b.png">

**Comment by tobspr** [comment]
https://trello.com/c/Iar8wpXI/150-blueprints-dont-properly-preserve-belt-rotation
Moved to trello
