### ISSUE TITLE
Bug: Full Belts are slower

### ISSUE THREAD

**Issue by NLZ** [tobspr/shapez.io#340]
Items on Belts at full capacity are transported slower.

Hard to showcase it with pictures, but hopefully this helps:

![image](https://user-images.githubusercontent.com/884277/86054114-d95fa080-ba59-11ea-82af-f4122bb7b78f.png)

![image](https://user-images.githubusercontent.com/884277/86054091-d06ecf00-ba59-11ea-92fe-4e60ae27646a.png)

Tried to determine the difference with Storage:

![image](https://user-images.githubusercontent.com/884277/86052647-9997b980-ba57-11ea-9bb4-77ef14cfd34b.png)
(To reproduce, build it, put a Trash to the Storages' output until they are cleared, delete the Trashes at the same time, then delete the input Belt at the same time.)

As you can see here, the 20/s Belt with 5x 4/s Extractor only delivered 500 item instead of 555, so I guess the Belt is 10% slower when full.

Using version 1.1.18 on 144 Hz if that matters
Possibly related to #329

**Comment by Arescet** [comment]
Ran this at 20 belt speed, miners 4 items a second. Each test was ~30 seconds.

If you have a buffer of belts
---
![image](https://user-images.githubusercontent.com/24558724/86061489-e28a4680-ba34-11ea-8366-17cf9d29ce3e.png)
the math gets a little thrown off.

Vertical
---
![image](https://user-images.githubusercontent.com/24558724/86060828-925eb480-ba33-11ea-96b9-f2b293c25ee8.png)
All the storage receive an expected number of items in 30 seconds except for the 5 miners, which is the same as the 4 miner setup.

If you have a buffer of belts
---
![image](https://user-images.githubusercontent.com/24558724/86061489-e28a4680-ba34-11ea-8366-17cf9d29ce3e.png)
the math gets a little thrown off.

Full balancer throughput
---
![image](https://user-images.githubusercontent.com/24558724/86063047-f5eae100-ba37-11ea-9b0c-b3fa38c93945.png)
With this setup a balancer (or even several in a row) will correctly provide 1.2k items in 30 seconds (20 items a second), but belts will only provide 900. (15 items a second)



I went back to the start of the game, got to 4 items per second belts, 0.4 items per second miners, so 10 miners to max a belt.
Used an upgrade requirement, started at 119/400 squares. It took ~71 seconds, which works out to ~3.96 items per second (some margin of error for needing a buffer that early game plus human error)

It seems full belts transfer items just as well, so i setup a race!

Race setup
---
![image](https://user-images.githubusercontent.com/24558724/86064553-6c3d1280-ba3b-11ea-8e1f-447e2f23bebf.png)

And the results
---
![image](https://user-images.githubusercontent.com/24558724/86064723-cf2ea980-ba3b-11ea-8ce8-be727dca8616.png)
Seems to be the same speed. Animations of full belts can be rather weird, alternating items at 20 (or rather, 15) items a second can be really tricky to see.

**Comment by tobspr** [comment]
https://trello.com/c/6VOiTNQF/275-buildings-and-belts-are-not-as-fast-as-they-claim-to-be-eg-15items-s-instead-of-20
