### ISSUE TITLE
Release web-based full version.

### ISSUE THREAD

**Issue by kevincox** [tobspr/shapez.io#342]
It would be really nice to be able to buy the full version of the game and be able to load it up in any web browser rather than having to mess around with steam.

**Comment by Dimava** [comment]
this requires server-side handling of https://partner.steamgames.com/doc/webapi/ISteamUser#CheckAppOwnership

**Comment by MidoriKami** [comment]
The concern would be performance, especially when more features are added. The browser won't run well much past level 18.

**Comment by kevincox** [comment]
Oh, I was assuming that the steam version was just a bundled browser. If it
is doing something else than it makes sense.

**Comment by MidoriKami** [comment]
The standalone runs as it's own desktop application. It has full access to system resources and is not dependent on an internet connection (Though steam itself sometimes thinks it must always have internet.)

**Comment by Dimava** [comment]
> The concern would be performance, especially when more features are added. The browser won't run well much past level 18.
> The standalone runs as it's own desktop application. It has full access to system resources and is not dependent on an internet connection (Though steam itself sometimes thinks it must always have internet.)

This is not correct.
- Chrome and game's Electron have more or less same performance, tho in some cases Chrome may be faster or slower
- Chrome has own procces per tab, so other tabs should not slow it down
- Running game in Web requires 1 browser, while running in standalone often gives three (Web which you just don't close, Steam and game 's Electron)

**Comment by Aprillion** [comment]
Feel free to display a warning about performance concerns, but it would be nice to be able to continue playing full version when we are out of reach of our Windows machines.

Speaking for myself only, I would be OK with simulation target 10 Hz while in "edit" mode ¯\\\_(ツ)_/¯ and switch to some faster "simulate" mode (or just go for coffee) when I would need to level up.

**Comment by tobspr** [comment]
https://trello.com/c/BxYKbmiR/278-allow-playing-full-version-on-web-after-purchase
