### ISSUE TITLE
With full upgrades, 5 chained extractors does not fill a belt

### ISSUE THREAD

**Issue by macdjord** [tobspr/shapez.io#343]
When all upgrades are purchased (i.e. x15 on everything), the chain extractor is supposed to generate 6 shapes/s, and the belt is supposed to carry 30 shapes/s. Thus, 5 chained extractors should completely fill a belt. However, sometimes it does not, and the resulting stream has visible gaps:

![Extractors](https://user-images.githubusercontent.com/4250155/86068648-fa1dfb00-ba45-11ea-8869-700e1c808eeb.png)

**Comment by chocoman** [comment]
I noticed the same problem. Cutters and quad cutters have the same issue: each cutter should handle 7.5 items per second, so if you divide the belt to 4 cutters, they are supposed to keep up (7.5*4=30), but there are the same visible holes in output. Stacking, painting and mixing works fine.
![Screenshot from 2020-07-01 14-57-57](https://user-images.githubusercontent.com/17728621/86246482-58b0b980-bbab-11ea-8ffd-251bf7fbec42.png)

**Comment by Arescet** [comment]
#329 it seems a lot of the end game speed upgrades aren't accurate

**Comment by tobspr** [comment]
https://trello.com/c/6VOiTNQF/275-buildings-and-belts-are-not-as-fast-as-they-claim-to-be-eg-15items-s-instead-of-20

**Comment by TannerJ07** [comment]
After the wires update the belts still only do 15 item/s instead of 16.2 with my current upgrades.

**Comment by TannerJ07** [comment]
I just had to changed the tick speed.
