### ISSUE TITLE
Cannot unpin upgrade-requirement shape once it is no longer required

### ISSUE THREAD

**Issue by macdjord** [tobspr/shapez.io#345]
In my playthrough, I had one of the shapes required for one of the Tier VI upgrades pinned. Once I had everything I needed, I performed the upgrade. Afterwards, the old shape was still pinned, as normal. However, unlike every previous tier, the Tier VII upgrades do not require any of the previous shapes. Since the pinned shape was no longer listed in the upgrades panel, there was no way (AFAICT) to un-pin the old shape.

**Comment by tobspr** [comment]
You can click a shape to unpin it. Please reopen if this doesn't work for you

**Comment by BecksIsAlreadyTaken** [comment]
Same for me. version 1.2.2
Clicking the shape in the left side doesn't work, and there is no close button to unpin the shape.
