### ISSUE TITLE
Centre zoom on mouse

### ISSUE THREAD

**Issue by macdjord** [tobspr/shapez.io#346]
When I zoom in or out using the scroll wheel, it would be nice if the zoom were centred on the location of the mouse cursor rather than the centre of the screen. Effectively, this would mean whatever you were pointing at before the zoom would still be under your cursor afterwards.

**Comment by zelosos** [comment]
Yeah that I miss too. This way moving fast between positions would be also possible.

**Comment by Dimava** [comment]
WIP

**Comment by Dimava** [comment]
Implementer in #386
