### ISSUE TITLE
Waypoints: zoom level is reset or ignored

### ISSUE THREAD

**Issue by bbugh** [tobspr/shapez.io#35]
There's two bugs here:

1. waypoints aren't restoring the correct zoom
2. when creating a waypoint, the game zooms in all the way

**Issue**

1. Set the camera's zoom level to something that isn't completely zoomed in
2. Create a waypoint with M
3. Observe that the camera zoom level has changed to the most zoomed-in when creating a waypoint
4. Zoom out
5. Activate a marker by clicking on it
6. Observe that it goes to the waypoint but is fully zoomed in again, ignoring the zoom level set for the waypoint

**Possible solution**

I think restoring the zoom problem is probably because of the `Math_max`, seems like that should be `Math_min`? It works for me with `Math_min`, anyway.

```diff
diff --git a/src/js/game/hud/parts/waypoints.js b/src/js/game/hud/parts/waypoints.js
index 746145b..485a53c 100644
--- a/src/js/game/hud/parts/waypoints.js
+++ b/src/js/game/hud/parts/waypoints.js
@@ -158,7 +158,7 @@ export class HUDWaypoints extends BaseHUDPart {
             this.waypoints.push({
                 label: markerNameInput.getValue(),
                 center: { x: center.x, y: center.y },
-                zoomLevel: Math_max(this.root.camera.zoomLevel, globalConfig.mapChunkOverviewMinZoom + 0.05),
+                zoomLevel: Math_min(this.root.camera.zoomLevel, globalConfig.mapChunkOverviewMinZoom + 0.05),
                 deletable: true,
             });
             this.waypoints.sort((a, b) => a.label.padStart(20, "0").localeCompare(b.label.padStart(20, "0")));
```

**Comment by tobspr** [comment]
Can't reproduce this. Any help on how I could do that? Since for me it works just fine.

**Comment by bbugh** [comment]
It's happening for me on Mac Chrome with 100% reproduction based on the steps I gave above on the latest master (with no code changes)! The above patch changing that to `Math_min` works.

Here is a video showing the issue https://recordit.co/45P9bDW2oK

**Comment by tobspr** [comment]
Can you reproduce it on the beta ? Since the dev version has lots of internal bound shortcut keys  (For example, "I" to set camera zoom level to 3)

**Comment by tobspr** [comment]
If you can reproduce it, please file a new issue then

**Comment by bbugh** [comment]
This can't be reproduced in the live version because markers are locked in the demo!

**Comment by bbugh** [comment]
I tried setting `G_IS_DEV` to `false` but it load the game then, saying something about the `app_settings.bin`. How do I create a non-debug build? I'm happy to help track this down.

**Comment by tobspr** [comment]
In camera.js, line 102:
```
 if (G_IS_DEV) {
            window.addEventListener("keydown", ev => {
                if (ev.key === "i") {
                    this.zoomLevel = 3;
                }
            });
        }
```

**Comment by bbugh** [comment]
Hahaha, I see what you mean now. 😂 I can confirm that filling in a name with "i" causes the issue. Thanks for explaining.
