### ISSUE TITLE
[Feature Request] Add an in-game clock

### ISSUE THREAD

**Issue by yume-chan** [tobspr/shapez.io#354]
Just had a 6-hour session in this game. 

It's so attracting and made me forgot the time.

So I request an in-game real-time clock that I can check easily.

**Comment by Arescet** [comment]
Bad feature request, the clock won't stop your addiction, you'll just "accidentally" not look at it.

**Comment by Dimava** [comment]
There are
 - clock in pause menu
 - click on your PC taskbar
just exit fullscreen

**Comment by tobspr** [comment]
Currently not planned
