### ISSUE TITLE
Belt connection issue

### ISSUE THREAD

**Issue by HendrikF** [tobspr/shapez.io#356]
With the following layout it is impossible to connect the top belt onto the bottom belt, neither by dragging, nor by rotating the held belt. The Rotation just skips the option to connect the upper one from top to bottom (in which case it could rotate the middle belt to go from top to left).

You have to remove some (all?) surrounding belts to be able to connect the top one to the bottom one.

![Bildschirmfoto von 2020-06-30 23-31-14](https://user-images.githubusercontent.com/6961660/86179592-d54f8380-bb2a-11ea-85b1-2c8442451e31.png)

**Comment by MidoriKami** [comment]
A somewhat elegant approach is to use a bridge and a balancer.
![image](https://user-images.githubusercontent.com/9083275/86458398-091cdb80-bcda-11ea-8b82-b4b5b64372a4.png)

**Comment by MidoriKami** [comment]
Alternatively, without any additional parts. 
![image](https://user-images.githubusercontent.com/9083275/86458504-2e114e80-bcda-11ea-86f2-e512c413da4b.png)

**Comment by MidoriKami** [comment]
Connecting to a middle belt becomes less elegant, but is still possible.
![image](https://user-images.githubusercontent.com/9083275/86458626-6749be80-bcda-11ea-95e3-be7adf743f01.png)

**Comment by HendrikF** [comment]
The problem is absolutely not, that I am unable to connect the belts.

One would expect that dragging a belt from the top over the two belts onto the bottom one would connect the top to the bottom.

But it does not. Try it. Instead it connects the top directly to the left and the second right goes to the left bottom belt. This also happens when trying to place belts by orienting them first. You just cannot orient them straight top to bottom.

**Comment by tobspr** [comment]
This breaks a lot of other behaviours though. There is no "perfect" solution so there is no fix for this
