### ISSUE TITLE
Missing Info/pin buttons in statistics window

### ISSUE THREAD

**Issue by cjo9900** [tobspr/shapez.io#363]
Missing Info/pin buttons in statistics window. Expect the same visual as the upgrades window.

Displayed shapes should show the pinned and info buttons in the statistics window to be consistent with the upgrades window.
PR #172 seems to cover the pin button.

Game version seen in.
Version 1.1.17 & 1.1.18

**Comment by tobspr** [comment]
Closing since its already covered by the PR
