### ISSUE TITLE
Rotate slows down the belt

### ISSUE THREAD

**Issue by DaMage93** [tobspr/shapez.io#368]
When having 2 belts, 1 with a rotate, and the other without, the belt with the rotate is slower than the belt without.  The belt speed and the rotate speed are the same (my case 12 items/s).

I've tried adding multiple rotates, but it's still the same as before. So when a belt has at least 1 rotate in it, the belt will slowdown / bottleneck due to the rotate.

I've also tried both clockwise and anticlockwise - same result

This is in the browser with 1.1.18 @ Production @ 1092975

**Comment by MidoriKami** [comment]
A simple and logical away around this problem even with mismatched rotate and belt speeds, is the following:
![image](https://user-images.githubusercontent.com/9083275/86458161-a9263500-bcd9-11ea-8c60-38fdb564c322.png)

If you can rotate say 10 items per second, but your belt carries 20 items per second, you can divide the work to multiple rotates and get no loss in flow.

**Comment by tobspr** [comment]
https://trello.com/c/6VOiTNQF/275-buildings-and-belts-are-not-as-fast-as-they-claim-to-be-eg-15items-s-instead-of-20
