### ISSUE TITLE
Error on Mac with es and for translation files

### ISSUE THREAD

**Issue by pitichampi** [tobspr/shapez.io#370]
Hi !

After having built everything fine, when I launch the game (yarn gulp) on my Mac, I've got an error. After having a look in the console (terminal, not browser console) I have found the issue. There is something wrong with the indentation of the **es** and **kor** translation files. To solve this issue I've just copied the **en** translation file over the **es** and **kor** and everything works fine now.

My configuration : 
MacOS 10.13.6
Node.JS 14.5.0
Yarn 1.17.3
Game version : 1.1.19 (master branch)

You'll find an extract of the console log attached to this issue.

[message.txt](https://github.com/tobspr/shapez.io/files/4862804/message.txt)

**Comment by tobspr** [comment]
Hey,

This was fixed already, just checkout the latest master :)

**Comment by pitichampi** [comment]
Sorry ^^ You are too fast for me ^^
