### ISSUE TITLE
option to downgrade speed upgrades

### ISSUE THREAD

**Issue by lesmana** [tobspr/shapez.io#371]
faster is not always better. i do not care about maximum possible performance. i do not play this game for efficiency. i play to watch the shapes trickle along the curves of the belt. now i upgraded once too many and the belt is too fast and i regret the upgrade. please allow to downgrade.

possible implementation: make it so that i can chose any of the speeds i have unlocked. so for example i have unlocked level 4 of belt speed then allow me to chose speed level 1, 2, 3, or 4.

also thank you for game. it is awesome.

**Comment by cachapa** [comment]
Agreed. I'd love to have a version of the game without any speed upgrades -- and with the shape numbers scaled down to compensate for it.

**Comment by GregorKopka** [comment]
With maximum speed it's too hard to see if the shapes really come out as intended, leading to having to block the belt (and repairing that damage after taking a look). Being able to (temporary) slow the speed would be a nice feature to ease setting up new machinery.

**Comment by tobspr** [comment]
https://trello.com/c/wWN9BJfv/279-reduce-later-level-speed-upgrades-to-make-it-still-able-to-see-items
