### ISSUE TITLE
Feature Request: Allow markers to be edited

### ISSUE THREAD

**Issue by Xiretza** [tobspr/shapez.io#374]
Currently, an existing marker can only be zoomed to (left click) or deleted (right click). Making a typo while creating a new marker is quite annoying because the old marker can't be edited, and you have to create a new one from scratch.

Replacing the right-click action with a modal that offers to either delete the marker or edit its name would be great - similar to how factorio does it:

![image](https://user-images.githubusercontent.com/3107142/86381091-342d0e00-bc8d-11ea-89c2-ffc42c900ae6.png)

**Comment by tobspr** [comment]
Already in
