### ISSUE TITLE
Feature Request: Web version, disable 15 minute notifications if I own it on steam

### ISSUE THREAD

**Issue by jordanburnam** [tobspr/shapez.io#375]
This may be a niche feature but I use the web version while at work where I cannot install software as a stress relief/distraction ... anyway we could disable the 15 minute notification if I have bought it ... ? Not sure how you would know that and it may not be possible but perhaps you have magic you can use :)

**Comment by Dimava** [comment]
*How*?

**Comment by extramrdo** [comment]
https://stackoverflow.com/questions/44199842/how-to-check-the-user-owns-our-game-in-steam-by-web-api

tl;dr would work for people with public profiles

**Comment by rogeriocamorim** [comment]
I think the problem is to know how you have a steam or not.
Maybe if  you load a steam save game, it will have a variable and will not show that msg.

**Comment by mse-k** [comment]
what if u share a steam savegame or worse edit the save to disable it

just add O2auth

**Comment by Dimava** [comment]
#342

**Comment by Dimava** [comment]
https://partner.steamgames.com/doc/webapi/ISteamUser#CheckAppOwnership

**Comment by cachapa** [comment]
I feel like the nagging screen should've only been implemented after #342 is resolved. Getting the notification every 15 minutes despite having paid kind of sucks.

**Comment by tobspr** [comment]
https://trello.com/c/BxYKbmiR/278-allow-playing-full-version-on-web-after-purchase
