### ISSUE TITLE
Suggestion: Change LMB to middle mouse button

### ISSUE THREAD

**Issue by adrianjakubczyk** [tobspr/shapez.io#38]
You can't move screen with mouse when holding an item because it is placed instead.
Changing LMB to clicking and draging mousewheel would solve this problem
(like on draw.io / diagrams.net)

**Comment by bbugh** [comment]
Track pads don't have middle clicks, please don't do this!

**Comment by adrianjakubczyk** [comment]
It could be changed in settings maybe. 
Besides, isn't it easier to move with WASD if you don't have a mouse?
