### ISSUE TITLE
Add build tests

### ISSUE THREAD

**Issue by Dimava** [tobspr/shapez.io#385]
Make sure the game does not crash:
- when loading to menu
- when starting a new game
- when importing a sample save
- when buiding 1 of each building
- same as above, but in both prod and debug modes

Reason for this is possibility of unrunnable state like current master branch which crashes when starting a new game:
![image](https://user-images.githubusercontent.com/20068737/86475122-d102b080-bd4c-11ea-9d53-b1dbeae5373b.png)
(because of merging #361 )

**Comment by tobspr** [comment]
I think mordof1 is working on it
