### ISSUE TITLE
After git pull:  Uncaught (in promise) TypeError: Cannot read property 'pipette' of undefined

### ISSUE THREAD

**Issue by skandragon** [tobspr/shapez.io#388]
```
Uncaught (in promise) TypeError: Cannot read property 'pipette' of undefined
    at HUDShop.initialize (shop.js:200)
    at GameHUD.initialize (hud.js:134)
    at GameCore.initializeRoot (core.js:107)
    at InGameState.stage3CreateCore (ingame.js:217)
    at ingame.js:362
```

hash:  503f9a7fe57fa41bcec20436a621dc4b0b842fb8

Steps:

* `yarn` in top level directory
* `yarn` and then `yarn gulp` in the `gulp` directory
* browser console shows this error.

**Comment by Dimava** [comment]
@skandragon 
it was broken with daa5cdecb49fd256282fc0ccfd01c6c57a638585 by merging #361
The 31fa93bbe6b1db137f7e0994a06ae15b95f5ae9b ishould probably work

I requested #385 so this does not happen again and someone started impl it already, but it will take time to merge that

**Comment by Dimava** [comment]
You may want to use https://github.com/tobspr/shapez.io/tree/1.1.19-spinoff branch meanwhile

**Comment by Dimava** [comment]
#380 fixes this
