### ISSUE TITLE
Quick hub centering

### ISSUE THREAD

**Issue by adrianjakubczyk** [tobspr/shapez.io#39]
Using space was nice to center on hub, removing this is intentional or is it temporary?

**Comment by bbugh** [comment]
Agreed, I keep hitting this frequently and nothing happens!

**Comment by bbugh** [comment]
It would also be nice if the space bar jump kept the current zoom, unlike clicking on Hub marker which unfortunately zooms all the way in.

**Comment by tobspr** [comment]
Alright I'll re-add it

**Comment by tobspr** [comment]
https://trello.com/c/eH3FFYGe/148-add-space-again-to-center
Moved to trello
