### ISSUE TITLE
implement nicer random piece generator

### ISSUE THREAD

**Issue by chocoman** [tobspr/shapez.io#391]
implement a better random shape generator, that generates symmetric shapes and mixes only similar colors.

**Comment by chocoman** [comment]
I finished implementation of the improved random shape generator today. I have it on my localhost, how can I proceed?

**Comment by dengr1065** [comment]
make sure it's on separate branch and pull request

**Comment by chocoman** [comment]
![shapes_generator](https://user-images.githubusercontent.com/17728621/86517282-092af180-be28-11ea-8273-5129df4bb049.png)
this is what it looks like. These are randomly generated shapes by the new generator.

**Comment by chocoman** [comment]
It seems that I have insufficient access rights:
```
$ git push --set-upstream origin symmetric-piece-generator
ERROR: Permission to tobspr/shapez.io.git denied to chocoman.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Dimava** [comment]
You should push to chocoman/shapez.io.git

**Comment by Dimava** [comment]
i.e. to your own fork

**Comment by chocoman** [comment]
thank you, I created the pull request. Here it is:
https://github.com/tobspr/shapez.io/pull/392
pipeline is currently failing with the same error as master.

**Comment by tobspr** [comment]
Not currently planned
