### ISSUE TITLE
Tunnel acts as merger

### ISSUE THREAD

**Issue by frankivo** [tobspr/shapez.io#399]
Build two entries in one direction and then one exit in the other direction. That's all that you need to do.

![image](https://user-images.githubusercontent.com/6542403/86575322-5d90b700-bf77-11ea-8adf-77bcce908770.png)

**Comment by frankivo** [comment]
Works up to 4 tunnels 😱 

![image](https://user-images.githubusercontent.com/6542403/86586735-aa30be00-bf88-11ea-8993-02c3b5f135c5.png)

**Comment by tobspr** [comment]
Will be fixed with the next release already
