### ISSUE TITLE
Move camera when pushing cursor to edges of the screen.

### ISSUE THREAD

**Issue by adrianjakubczyk** [tobspr/shapez.io#40]
Like in any RTS games moving cursor to an edge of the window could move the screen. It would also make selecting items easier (for reference selecting units in Warcraft III or some Age of Empires). I understand that this would require changing whole selection system because now it's tied to screen coordinates but I think that this would improve overall experience.

**Comment by tobspr** [comment]
https://trello.com/c/xpT7iWan/149-moving-camera-on-screen-borders
Moved to trello
