### ISSUE TITLE
Secondary color purple should be renamed to magenta

### ISSUE THREAD

**Issue by MrYawnie** [tobspr/shapez.io#402]
As the title states, the secondary color created by mixing red and blue should be magenta (as per RGB color model) instead of purple, as additive color mixing is used. 

Purple is an umbrella term for any mixture between red and blue, and not generally referenced in color mixing (neither additive nor subtractive, the only two color mixing models). Magenta, however, is exactly 50/50 mixture of red and blue (RGB 255, 0, 255 or HEX #FF00FF).

**Comment by tobspr** [comment]
https://trello.com/c/kiKkO4Fu/281-rename-purple-magenta
