### ISSUE TITLE
Feature Request: Auto-scroll when using the conveyor belt planner

### ISSUE THREAD

**Issue by GrahamClemo** [tobspr/shapez.io#407]
Making long conveyor belts is currently a pain. It would be better if you could drag the mouse near to the edge of the screen and it would start scrolling in the direction that you want to go, gradually increasing in speed until you let go of the mouse button or move the cursor back away from the edge. 
Currently I have to hold shift and a WASD key with one hand, and the left mouse button with the other.
For that matter it would also be nice to be able to scroll with the middle mouse button without having to deselect the item you are placing or using the keyboard.

**Comment by tobspr** [comment]
https://trello.com/c/FVpgTGgU/282-allow-moving-the-map-by-moving-the-cursor-to-the-edges-of-the-screen
