### ISSUE TITLE
High DPI screens not handled properly with current texture atlas system

### ISSUE THREAD

**Issue by WolfWings** [tobspr/shapez.io#409]
While the underlying framework of the DPI is detected to rescale the raw canvas properly so native text is rendered at full pixel resolution, something in the atlas-level selection logic is ignoring that entirely, resulting in for example the following on my 4K display which I run at 200% UI Scaling in Windows:

![DPI Scaling Issue](https://user-images.githubusercontent.com/4805696/86690678-c145cf00-bfcd-11ea-967b-d4e37bd7b98d.png)

This happens across the board both in the browser and Steam versions, and while I can work around it in the browser version by using browser-zoom to 50% to counteract the global 200% scaling applied to the monitor there's no equivalent workaround in the Steam version. On the flipside to test this on a normal DPI screen forcing the browser to 200% (or higher) zoom with Ctrl+= or the like introduces the same rendering flaws on normal screens.

~~https://github.com/tobspr/shapez.io/blob/master/src/js/game/core.js#L356~~

~~I'm not sure if the global configuration parameters need to be tuned or there's a flaw in the logic here, but this seems likely the relevant point in the code? I'm unfamiliar with electron, gulp, or many of the tools used here so I'm unable to submit a patch directly, but am happy to test variants if needed.~~

**EDIT:** The above doesn't seem to have any affect on the issue, unsure what does, so ignore that trail.

**Comment by dmitryrn** [comment]
What exactly wrong here @WolfWings? All the text on the screenshot looks big enough IMO.

**Comment by WolfWings** [comment]
It's not the text, as I said that's properly crisp as the canvas resolution is configured respecting the DPI, it's that the sprites selected for the piecemeal map rendering (not the hub though) appear to choose the atlas level without taking into account the DPI.

Here's another example with my DPI scaling in Windows set to 300% (to make the blurring more obvious) and 100%, as close as I could get the map-zooms to match, and cropped to show the hub versus the nearby square resource pool.

![300 percept DPI example](https://user-images.githubusercontent.com/4805696/87325951-bc19e000-c4f7-11ea-973a-bbb63b43333b.png)

![100 percept DPI example](https://user-images.githubusercontent.com/4805696/87326651-9f31dc80-c4f8-11ea-9bed-66bc930fb04e.png)

This also affects the level at which the map switches to the 'colored squares' view, with the 300% screenshot above as far as I can zoom out before the map changes to that view, while at the 100% mode I could zoom out much further before that happens.

**Comment by tobspr** [comment]
Will be fixed with the wires update
