### ISSUE TITLE
QuotaExceededError: Failed to execute 'setItem' on 'Storage'

### ISSUE THREAD

**Issue by clemtaylor** [tobspr/shapez.io#421]
```
Failed to write savegame-7aca985ccfe5fd7e07902f1756a671eba716cdb8.bin : DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'savegame-7aca985ccfe5fd7e07902f1756a671eba716cdb8.bin' exceeded the quota.
    at StorageImplBrowser.writeFileAsync (http://localhost:3005/bundle.js:48915:29)
    at http://localhost:3005/bundle.js:19465:41
```

I tried to import my 1MB (1004763 bytes) save game and triggered this error.

I deleted all the browser state for localhost:3005 and reloaded the game and the error triggered again.

I've seen youtube videos with much larger machines and I had deleted much of my machinery after completing the main gameplay.

Google didn't turn up a way to increase this quota for testing. 

I also tried to load it with firefox and triggered the same error.

**Comment by eyoung100** [comment]
See [Setting the value of 'dataURL' exceeded the quota](https://stackoverflow.com/questions/23977690/setting-the-value-of-dataurl-exceeded-the-quota) for possible fix

**Comment by tobspr** [comment]
Dev version uses local storage to make it easier to debug it. It's not meant to be played
