### ISSUE TITLE
[Suggestion] Quad painting shapes less than 4 quadrants

### ISSUE THREAD

**Issue by Alpha-Neldr** [tobspr/shapez.io#426]
Please allow the quad painter to paint objects that are 3, 2 or 1 quadrants without needing 4 belts of color input in every case.
![Annotation 2020-07-08 115953](https://user-images.githubusercontent.com/67922283/86941965-931dd780-c112-11ea-8741-ffcad5ac706e.png)

**Comment by tobspr** [comment]
Will be fixed with the wires update

**Comment by tobspr** [comment]
https://trello.com/c/iuyp8Cwl/217-allow-multipainter-inputs-to-be-blocked-by-pins
