### ISSUE TITLE
Despite regular 'game saved' notifications and clicking the save button every so often, lost hours of progress when I accidentally hit ctrl+w - on continue, game knocked me back 5 levels and forgot most of my factory

### ISSUE THREAD

**Issue by triffid** [tobspr/shapez.io#427]
Apparently the save feature still needs some work - is it ignoring errors about local storage sizes perhaps?

Running 5a8fce4248548ff1 in google chrome.

**Comment by tobspr** [comment]
Yes it is ignoring errors about local storage. Just don't play on the dev version. The live version uses indexeddb
