### ISSUE TITLE
Global play/pause makes the game play an audio file?

### ISSUE THREAD

**Issue by Nchi** [tobspr/shapez.io#428]
Why?? I would half understand if it unmuted the game, but it doesn't! It plays while the game is muted.... Either way you probably shouldn't touch global music controls- it sorta defeats the point, especially when I can just mute right there

**Comment by tobspr** [comment]
It's a windows issue. Can't do anything about that

**Comment by Nchi** [comment]
Aren't you using electron/chrome/chromium? chrome://flags/#hardware-media-key-handling can be passed in index I think, 

app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling,MediaSessionService');




from https://github.com/electron/electron/issues/18253#issuecomment-589542934

found it here
https://github.com/electron/electron/issues/21731

<3 You probably dont want me to actually PR, I might be able to research but... no real coding yet- might have to start if you say its another windows bug :)

(OS bugs are to be worked around, not stopped at!)

**Comment by dengr1065** [comment]
that's clearly not a windows bug, same happens on all platforms, but imo it's useful

**Comment by Nchi** [comment]
If it didnt overlap the existing music maybe- but what is ever the point of double music lol
