### ISSUE TITLE
Enable messages to display user's custom keybinds

### ISSUE THREAD

**Issue by jansenmcq** [tobspr/shapez.io#429]
I use esdf instead of wasd to move around, and I end up changing the keybinds of the modifier keys as well. Ex: shift -> a, ctrl -> shift, alt -> z, etc. Even though the correct keys are showing in the top left box of the ui, the messages that show up when I complete hub levels do not show my keys. 
I went to the english translations file, and I could not figure out any way to pull in the correct key for the message. Would it be possible to add it as a placeholder? I'm not sure how that system works.

**Comment by tobspr** [comment]
Since its a rare use case, I'd rather not change all translations to reflect it. IMO; If you change the keys you change only keys you already know
