### ISSUE TITLE
Feature Request: Counter

### ISSUE THREAD

**Issue by FlyingThunder** [tobspr/shapez.io#448]
A component which i assume would be relatively simple but very neat for the number freaks like me:
A small 1x1 building that you can put over a conveyor belt which displays the amount of items of a specific type which pass through this road each minute. Could be detailed showing all item types, or only one item type at once... but i would love it :)

**Comment by Malligan** [comment]
![image](https://user-images.githubusercontent.com/3331334/87538829-916d8a00-c6a5-11ea-93c3-af98528cb65a.png)
There is statistics window with all this data and more, isn't it?

**Comment by WolfWings** [comment]
That's the global production statistics.

What's being asked for here is some kind of way to measure the throughput of a single conveyor belt or even just a tile overall, as you might be producing the same 'fragment' in multiple different places in your factory or wanting to compare two different ways of building a shape.

**Comment by Moppler** [comment]
I have a branch with that feature. The code needs so cleaning up but it's functional. If @tobspr thinks this would be a good addition to the game, I'll create a pull request.

![unknown](https://user-images.githubusercontent.com/48440667/87548130-f88a3f00-c6a3-11ea-990a-a216b55f6ab6.PNG)

Code: https://github.com/Moppler/shapez.io/tree/feature/counter-building

**Comment by tobspr** [comment]
https://trello.com/c/YYujDa3k/271-measure-belt-pseed
