### ISSUE TITLE
Suggestion: Logic Building

### ISSUE THREAD

**Issue by eyoung100** [tobspr/shapez.io#450]
I apologize for not having artwork, so hopefully I can explain this and it makes sense:

**Example**:

1. I build a Cutter for Circles, which gives me Left and Right halves 
2. Adding a Rotator gives me Top and Bottom halves
3. Adding Cutters on the Top and Bottom of the output from 2, gives me Top Left and Top Right Quarters
4. Adding Rotators again would give me Bottom Left and Bottom Right Quarters

Sending these as individual outputs would require 4 output belts, finally merged into one

**Logic Building Example**:
Now take the example above and send all 4 outputs to one belt.  This creates mixed/unsorted output.  Instead of Separating the 1 belt into 4, I can add a logic gate that would separate for me.  In Factorio, IIRC, this is called a Combinator:

1. One Belt of mixed shape types is an input.
2. The logic Building has 2 options:
    
    - The Desired Shape that's split off from the input belt.  In the above example it would be say Top Right Circle Quarters
    - An Option to send the Discarded Choices down another belt to be sorted further. If the Option is Set to Off, the items not selected are automatically trashed.

Three Logic Buildings would result in 4 clean sorted outputs.

**Comment by tobspr** [comment]
Will be done with the wires update
