### ISSUE TITLE
[Feature Request] Filter

### ISSUE THREAD

**Issue by SeaLife** [tobspr/shapez.io#452]
Hey, i would like to see a filter component to filter a shape by its key on to a specific lane.

For example, you have 1 input and 2 outputs, left output is every shape not matching the set shape key, the right output is always a shape matching the pattern.

With this feature, you could easily route shapes from far away to somewhere else you wanna process them (depending on your build)

Regards
Sealife

**Comment by eyoung100** [comment]
See #450

**Comment by SeaLife** [comment]
Hey @eyoung100, i've seen your issue but obviously it was not simple to understand (at least for me), what you wanna accomplish with that. But now, as i have my idea in mind, i see, where your idea is going. :)
I'll take a look at the code and maybe implement a simple filter on my own if @tobspr is interested in such a feature - but somebody has to make an asset for that - im horrible at graphics :D

**Comment by MrYawnie** [comment]
I can make the asset for it.

How would you set the filter key? Maybe it could be like the first item to enter the filter registers as the key. Those shapes go right, rest go left. Instead of having a pop-up window where you choose it.

**Comment by tobspr** [comment]
Will be done with the wires update
