### ISSUE TITLE
RFC: New building - Unstacker

### ISSUE THREAD

**Issue by Moppler** [tobspr/shapez.io#453]
### Concept

The unstacker (name open for discussion) is a building variant of the stacker. As the name would suggest, It works like a stacker but in reverse. A 2:1 building, it's input is a single belt in the bottom. The output is two belts at the top. Given an input of `CuCuCuCu:CuCuCuCu` he building would produce an output of `CuCuCuCu` on belt 1 and `CuCuCuCu` on belt 2.

This building opens up new possibilities for high-efficiency factory designs, primarily:
- Denser transport belts.
- Painting more than four corners at once

### Questions to be answered

- [ ] What does the building look like?
- [ ] Given a 3 layer shape, which side should the two layers shape be on?
- [ ] At what stage should the player unlock this new variant?
- [ ] What are the possible negative impacts?
- [ ] What are the possible positive impacts?

### What is an RFC?

Request For Comments - Is a place for discussion regarding a specific feature. It is an opportunity for all interested parties to provide their thoughts and opinions. This approach helps the community to work together to shape the feature. It also provides a record of the discussion for reference later.

Please keep discussions in the comments of this RFC. Once consensus is reached, this text at the top will be updated to reflect the community decision.

#### Note

This was attempted previously and put on hold. See #11. This RFC aims to outline and address any concerns **before** development effort is invested.

**Comment by MrYawnie** [comment]
For 4-layer shape, the shape should be split in half instead of 1-3 split as discussed on Discord. 

So for example, a shape `CuCuCuCu:SuSuSuSu:CuCuCuCu:SuSuSuSu` would be split into `CuCuCuCu:SuSuSuSu` on belt 1 and `CuCuCuCu:SuSuSuSu` on belt 2. 

So **NOT** splitting into `CuCuCuCu:SuSuSuSu:CuCuCuCu` and `SuSuSuSu`

This way one can add 2x 2-layer shapes on top of each other in order to transport more shapes on a single belt (denser transportation as mentioned).

**Comment by Control55** [comment]
Maybe the unstacker could be like the quad cutter. That would solve the layer problem and 2-2 or 3-1 discussion.

**Comment by 621642** [comment]
Why not treat it like a normal cutter with 2 output belts or like a reverse colour mixer?

Unstacking 1 layer (ie the top layer) at a time so `RuRuRuRu:SuSuSuSu:CuCuCuCu:WuWuWuWu` splits into `RuRuRuRu:SuSuSuSu:CuCuCuCu` and `WuWuWuWu` hence the name **unstacking**

If you want another layer gone you just put it again through the unstacker, or maybe use wires to select how many layers from the top are unstacked

**Comment by tobspr** [comment]
Considering for the wires update

**Comment by tobspr** [comment]
https://trello.com/c/mqN2vX7Z/283-unstacker
