### ISSUE TITLE
Export/Save not working on desktop version

### ISSUE THREAD

**Issue by Xan-Kun** [tobspr/shapez.io#454]
Hello!
In the steam desktop version 1.1.18 on windows, when I try to export a game to a file on the local disk, the file choose dialog appears and I can enter a filename, but the file never gets created.
Is this supposed to work or was that a feature for the web version only?

Thanks for the great game anyways! :-)

**Comment by tobspr** [comment]
https://trello.com/c/hzIrZLF3/261-exporting-screenshots-or-savegames-does-not-work-sometimes-on-electron

Known bug :)

**Comment by Xan-Kun** [comment]
Hey, thanks for the answer.
And it definitely is correlated to the level-size ;-)

**Comment by Xan-Kun** [comment]
BTW: you could try electron-dl for the download part. It's much more reliable and waay simpler to use :-)
