### ISSUE TITLE
Feature Request: Ability to protect an area or buildings

### ISSUE THREAD

**Issue by koenada** [tobspr/shapez.io#455]
### Overview
There is currently no method for protecting buildings from being accidentally deleted or overridden.

### Context
I commonly play shapez.io on my laptop. Unfortunately, my touchpad is very finicky in terms of detecting 1 vs 2 finger clicking (likely due to my linux drivers). I commonly, while meaning to Ctrl + click to select a number of buildings and belts, will accidentally just delete things as my laptop detected a 2-finger click. This is more problematic as I don't usually notice until I start quickly dragging over a number of objects quickly.

### Suggestion
I think adding the ability to select a group of objects and "protect" or "lock" them would help. Possibly being another option after Ctrl selecting an area.

**Comment by tobspr** [comment]
Currently not planned
