### ISSUE TITLE
Request: clickable variants selection

### ISSUE THREAD

**Issue by jppresents** [tobspr/shapez.io#46]
At the moment you can only cycle variants by pressing "T".
It would be great if you could also just click on them to activate the clicked variant.
(Right now, they are click-through and you place the currently selected variant under the button)

**Comment by tobspr** [comment]
https://trello.com/c/Ljy2e0At/117-allow-selecting-variants-with-mouse-when-clicking-on-them

**Comment by tobspr** [comment]
Moved to trello
