### ISSUE TITLE
[Idea] Overflow  gate

### ISSUE THREAD

**Issue by BaleineSanguine** [tobspr/shapez.io#462]
- 1 Input
- 2 Outputs

The input always goes into the first output unless the first output is full then it goes into the second output

- 2 versions :
1 normal
1 flipped

**Comment by tobspr** [comment]
Doesn't the storage work for you?

**Comment by BaleineSanguine** [comment]
Yes but its 2x2 and both outputs are on the front and it doesnt support different items

**Comment by BaleineSanguine** [comment]
And the storage should act like a merger

**Comment by tobspr** [comment]
imo the current storage is fine, since you shouldn't mix belts anyways
