### ISSUE TITLE
Powered Building idea: The Perforator 

### ISSUE THREAD

**Issue by stylpe** [tobspr/shapez.io#463]
- [x] I checked if this was already reported here or in the Trello board (maybe the Stamper is the same thing? But it has no description...) 

![image](https://user-images.githubusercontent.com/99851/87854603-65574080-c913-11ea-962f-46d8308e4ec5.png)

An idea I had for a new powered building, with crude concept art: The Perforator, which takes two non-stacked shapes and cuts/subtracts one out of the other. The cutout should be smaller, like half or three-quarter size, so that the square doesn't completely remove any other shape, and also allow identical shapes to be used as inputs. Fits with the theme of the color inverter, too. There's a potential UX snag with visibility in stacked shapes, though.

The name and building shape are of course merely suggestions. 

I originally suggested it on Discord in #wires, and at least a couple of people seemed to like it 😇

**Comment by tobspr** [comment]
I kinda dislike this, since it can produce shapes which are really hard to distinguish.. Other feedback is appreciated

**Comment by stylpe** [comment]
Yeah, fair enough, it's already difficult with the most stacked shapes and this would be worse, you would probably be forced to use the inspection view to know what to make.

Thanks for considering! Maybe I'll make a mod with it some time. I'll leave it up to you to close it or leave it open for votes.
