### ISSUE TITLE
click and drag, pasting blueprints

### ISSUE THREAD

**Issue by 621642** [tobspr/shapez.io#465]
When pasting blueprints you currently have to place them one by one, with modular systems this can be quite annoying; as misclicking is inevitable, then having to go though the pain of removing everything and pasting it again which could cost a lot of blueprint-shapes.

The ability to paste blueprints by clicking and dragging a line in a direction pasting said blueprint automatically one after the other would be an awesome option.

**Comment by Moppler** [comment]
I feel like this would work well.
If you had to hold shift, it would remain consistent with the existing user experience. I personally place blueprints over the top of existing buildings, so it would be important for me to have the option of both as I can see myself using them at the same time.

Perhaps draw a square around the selection to represent the concept of that selection being a single, placeable tile?

**Comment by tobspr** [comment]
https://trello.com/c/qW5JGxVC/302-allow-pasting-blueprints-with-shift-drag-as-well
