### ISSUE TITLE
[Feature Request] Setting or control configuration for changing camera pan button to middle mouse from left click

### ISSUE THREAD

**Issue by DavidTriphon** [tobspr/shapez.io#466]
I would like the ability to change the camera pan keybind. I can pan the camera with left click and drag. But when I have a conveyors selected, left click and drag places conveyors. This means that I have to use WASD to pan the camera whenever I have conveyors selected. If I could use the middle mouse button instead to pan the camera, then I would not lose the ability to pan it while having the conveyors selected. It gets annoying when I'm used to panning the camera by mouse and then suddenly I've strewn conveyors over my factory while trying to move the camera.

**Comment by Moppler** [comment]
A new option for middle mouse button scrolling would be a nice addition. Also, there is already a planned change to scroll when the mouse reaches the edge of the screen:
https://trello.com/c/FVpgTGgU/282-allow-moving-the-map-by-moving-the-cursor-to-the-edges-of-the-screen

**Comment by Moppler** [comment]
Here's a branch that adds a new setting for middle mouse scrolling. But I don't think it solves the problem being described here. If you are able to, please try it out. This branch implements a new setting for middle mouse scrolling that is switched off by default.
https://github.com/Moppler/shapez.io/tree/feature/middle-mouse-scroll

**Comment by DavidTriphon** [comment]
Alright, I'll clone and build that branch and try it out. I'll get back to you once I finish that.

**Comment by DavidTriphon** [comment]
You were right about one thing, it doesn't solve the problem I described.

With the setting on, I can pan with middle click which is nice, but I didn't expect to also be able to pan with left click.
Then once I select a building (with multiplace setting on), then both left click and middle click place buildings.

What I was hoping for was that middle click would always be pan camera, and left click would only ever be place buildings. That way the button functionalities would be dedicated to different purposes and not changing behavior based on selection state.

If the setting switched pan camera from listening for left click to listening for middle click, and did not enable place on middle click,  then I think I would be happy with the changes. But in its current state it does not solve my problem.

**Comment by DavidTriphon** [comment]
I'm currently messing around with your code. I don't know the organization here so I'm still looking around.

**Comment by DavidTriphon** [comment]
Okay, I think I see why it isn't as simple as changing a single if condition. Behavior that tracks when the screen is moving is coupled directly into the function call that's only made when it's a left click and not a middle click or right click. I'm going to mess around and see if I can decouple it and make it work the way I want to.

**Comment by Moppler** [comment]
Good luck, I didn't want to get into the weeds with that one just yet.

**Comment by DavidTriphon** [comment]
There's a couple of ways I see of going about this issue. But the fact that I currently have no feedback from tobspr makes me think that I have an incredibly small chance of making a PR that would solve this issue and meet their quality standards. Tobspr, if you see this, please leave me some feedback so that I can work on making this change in a way that you would approve of.

**Comment by DavidTriphon** [comment]
I've made progress in my own branch: https://github.com/DavidTriphon/shapez.io/tree/middleClickPan

The behavior appears to work as I intended, but it's also caused some weird side effects and revealed a bug.

**Issue 1:**

If I start holding down middle click while panning, and then start holding down left click, the pan will stop and I will begin placing the specified building. As soon as I release the left click, while still holding middle click, the placement will stop and the screen will jump to mouse position, as if I had been panning the entire time.

There are two options I can think of to solve this:

- Block left click and right click action from starting while another click event is still being held down

- Let the other click events occur but make sure the screen keeps panning so that the mouse doesn't move in game space.

**Issue 2:**

While holding left click to place buildings in multiplace mode, clicking any other button will cause the placement to stop, as if left click has been released. I looked in the code and discovered that the mouseUp events do not track which mouse button has been released, so every action that waits for a mouse button to release triggers when any mouse button is released. That definitely shouldn't be behaving that way.

I'm going to look at adding the mouse button key/enum as a variable for those listeners.

**Comment by DavidTriphon** [comment]
Thanks Moppler, if you hadn't tried to solve my issue and then given me reason to download the repo and build it myself, I wouldn't be here doing my own work on this desired change of mine. I'm having a lot of fun looking around in here.

**Comment by DavidTriphon** [comment]
I just opened PR #475 to handle this issue.

**Comment by DavidTriphon** [comment]
Since I now have feedback on the PR and the dev seems to like it, I'm going to close this issue here.
