### ISSUE TITLE
Request: Option to rotate by mouse (mouse-wheel while in placing mode)

### ISSUE THREAD

**Issue by jppresents** [tobspr/shapez.io#47]
It would  be nice to be able to rotate something I am in the process of placing by using the mouse.
I would suggest that mousewheel up/down shoot rotate left/right while the item is on the cursor.

**Comment by tobspr** [comment]
You already use the mousewheel to zoom in / out though? How'd that work?

**Comment by jppresents** [comment]
I would be ok with it changing, just so you can do things "mouse only".
(I guess that would require a setting then.)
At least for anything but roads (which you can't rotate anyway) I am not zooming in and out while placing.
But I understand if that overcomplicate things.

**Comment by tobspr** [comment]
For now I'd like to keep it as is, it would confuse people I feel. I will keep it on my todo list
