### ISSUE TITLE
[Bug] Game is played at 98% speed

### ISSUE THREAD

**Issue by Dimava** [tobspr/shapez.io#472]
I have found the possible reason of 98% game speed
It's `quantizeFloat` used to round GameTime.timeSeconds
![](https://cdn.discordapp.com/attachments/706122309227905024/734452017849827418/unknown.png)
![](https://cdn.discordapp.com/attachments/706122309227905024/734452463628714084/unknown.png)
Because 0.03333 tick is rounded to 0.33 realtime and 0.16666 tick is rounded to 0.017 realtime
which gives 101% speed for 30fps and 98% speed for 60fps which corresponds to gameplay

**Comment by tobspr** [comment]
https://trello.com/c/6VOiTNQF/275-buildings-and-belts-are-not-as-fast-as-they-claim-to-be-eg-15items-s-instead-of-20
