### ISSUE TITLE
[Bug] Unable to start game through Steam when previously launched on Linux (Manjaro)

### ISSUE THREAD

**Issue by stroym** [tobspr/shapez.io#473]
The title might sound a bit weird, but it's the best I can do while keeping it somewhat short. Anyway, to elaborate:

Say you launch Steam and then want to play shapez.io. The first time you're good to go. When you exit the game and want to play again, you can't unless you restart Steam first. The game starts a bunch of "shapezio" processes as well as a "bash" one and Steam says the game is running, but it doesn't show up at all. The processes don't even react to clicking "stop" in Steam, you have to kill them manually.

 Launching the game through play.sh works fine, so this might just be some Steam/Manjaro shenanigans you can't do anything about.

**Comment by tobspr** [comment]
Hm, yeah I suspect it's the latter :/ It seems sometimes this is an issue, but I have no idea on how to fix it
