### ISSUE TITLE
[Feature Request] Ability to make custom themes including shapes and maybe grid.

### ISSUE THREAD

**Issue by MysticalSquirrel** [tobspr/shapez.io#474]
Hi, I was wondering if it would be possible to allow us to make custom themes?

If yes, I would maybe have an idea that could make it nice and simple for the users to do so:
It could be made so if a tileset.png image exists maybe next to the executable or in a gfx or resources folder, use that tileset instead or set of icons if you are using individual icons instead of a tileset for the current way it is set-up.
And if possible, could it also include the shapes themselves as well as maybe the grid so we could override them in the same way of the buildables?

I would love to make a drawn-styled version or even event themed versions (like halloween or christmas) of what is currently available in the game as well as further updates if implemented ^^

**Comment by tobspr** [comment]
https://trello.com/c/oGG7wYZv/303-mod-suppor
