### ISSUE TITLE
Revert Bug Fix Request - Multi inputs on underground belts

### ISSUE THREAD

**Issue by Arescet** [tobspr/shapez.io#476]
In issue #399 it references tunnels acting like a merger, but with full inputs they actually act like a priority input. Combined with storages acting like priority outputs, this is extremely useful.

While i agree this is a bug, it doesn't interfere with the normal gameplay as the belt orientation has no active use other than this unintended mechanic. No normal gameplay arrangements of belts would have this setup without meaning to.

They'll always prioritize pulling from the longest belt with items flowing, compared to the fix, which always pulls from the shortest belt connection regardless of item flow.

All 4 inputs, white gets priority
---
![image](https://user-images.githubusercontent.com/24558724/87993510-accb0180-cab8-11ea-9360-6d9ef27f49c2.png)

2 inputs, red gets priority
---
![image](https://user-images.githubusercontent.com/24558724/87993535-c2402b80-cab8-11ea-9f51-166d3a817ee0.png)

An example of 1 of the many uses is my setup to shift input to the left (up in this case) to cover any empty inputs

All 4 inputs, output is the same
---
![image](https://user-images.githubusercontent.com/24558724/87993585-e439ae00-cab8-11ea-9ed0-3c55f2e1edab.png)

White and red removed, blue shifted up 1, green shifted up 2
---
![image](https://user-images.githubusercontent.com/24558724/87993649-06333080-cab9-11ea-959b-cad821ec6ab4.png)

The main reason for asking for this is a lack of another way to do it without tons of erratic timing issues, lag, and sometimes even the length of the belt before them being something to take into consideration with storage overflow methods. 

If it can't stay, a replacement method such as a way to upgrade a belt to allow this (by an alternate building, or even something like appending a merger to a belt to change how it acts), or for storage buildings to have a prioritized input (they already have a priority output, and aren't intended to be balancers anyways) , or even a building similar with that mechanic would be extremely useful to people who make complicated machines in the game.

**Comment by GregorKopka** [comment]
I would rather see a config option on splitters/mergers/storage for which input and output to prefer, with an 'unset' or 'both' option.

**Comment by Arescet** [comment]
That shouldn't be needed however, to get closest priority, 1 pair of undergrounds behaves exactly as expected, the additional behavior only occurs when adding redundant inputs, which has no normal use.

**Comment by tobspr** [comment]
I don't like the "buggy" behaviour, since I feel its unintuitive. You can only have one tunnel entry and exit, like in real life. Feel free to change my mind! :P
