### ISSUE TITLE
Launching through steam crashes

### ISSUE THREAD

**Issue by SohumB** [tobspr/shapez.io#485]
I'm on a mixed debian system. The error is as follows: 

```
[2181503:0722/181433.389219:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /sohum/.local/share/Steam/steamapps/common/shapez.io/chrome-sandbox is owned by root and has mode 4755.
/sohum/.local/share/Steam/steamapps/common/shapez.io/play.sh: line 2: 2181503 Trace/breakpoint trap   ./shapezio
```

After chmod 4755 chown root, it does work, but this is ... extremely weird, and the average user shouldn't be expected to be able to or, indeed, _want_ to make random binaries setuid root.

**Comment by Pikaro** [comment]
It's not setuid root here and works if launched directly. (Also launches from Steam but it's very slow, #496, and shows the behavior described in #473 .) Do you have SELinux on enforcing? It may be blocking something the sandbox wants to do.

**Comment by SohumB** [comment]
I can also confirm that #473 occurs on my system, yeah. But that doesn't seem to be this particular issue. I don't believe I have SELinux—this isn't an SELinux/capabilities issue at all, as far as I can tell. 

The error replicates if I run the binary directly, assuming I chown chrome-sandbox back to my user: 
```
% ./shapezio
[3016713:0725/142806.277281:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /sohum/.local/share/Steam/steamapps/common/shapez.io/chrome-sandbox is owned by root and has mode 4755.
zsh: trace trap  ./shapezio
```

This appears to be a widely-seen electron issue https://github.com/electron/electron/issues/17972. From my reading of it, there's multiple workarounds, some of which are available to the developer, and some to the user.

* run with `--no-sandbox`. In theory `play.sh` could then read `./shapezio || ./shapezio --no-sandbox`. This however is relatively not ideal; it apparently introduces some kinds of security concerns regarding code leaking from the app?
* have the user enable namespace sandboxing for unprivileged users (`sudo sysctl kernel.unprivileged_userns_clone=1`). Electron uses namespace sandboxing before setuid sandboxing if it's available.
* use a system-level chrome-sandbox if it's available. On debian the package `chromium-sandbox` installs `/usr/lib/chromium/chrome-sandbox`, which already has the appropriate permissions. 

Hope this helps! I'm using namespace sandboxing for now.

**Comment by tobspr** [comment]
https://trello.com/c/C7wsfgQi/253-game-does-not-start-sometimes-on-linux-sandbox-issue
