### ISSUE TITLE
[Feature Request] Dyes for Markers and Statistics

### ISSUE THREAD

**Issue by Adrthegamedev** [tobspr/shapez.io#489]
Allow markers to use the shapes of dyes, as i would love to label any dye-making factories i build.
Along with that, show dyes in the statistics, because it would be useful to see how much dye i produce from dye factories.

**Comment by tobspr** [comment]
https://trello.com/c/v3wKZCR0/305-allow-using-colors-in-markers-and-show-them-in-the-statistics
