### ISSUE TITLE
Improvement: Under "Upgrades" show if progress is beeing made when numbers are abriviated

### ISSUE THREAD

**Issue by jppresents** [tobspr/shapez.io#49]
At the moment if you have for example "16k / 37k" of a certain shape in the upgrades tab, you can't tell if those are still reaching the hub or if it's standing still. 

It would be nice, if there was some small indicator icon (up arrow or something that on hover shows the rate of change, maybe switch to "stop sign" icon if nothing is delivered)

**Comment by tobspr** [comment]
An upcoming change showing more detailed numbers should fix this :)
