### ISSUE TITLE
[Bug] (Cosmetic) Cyrillics are rendered with a different font

### ISSUE THREAD

**Issue by D-side** [tobspr/shapez.io#490]
This is admittedly a very minor issue.
Because the font used in-game doesn't include Cyrillic characters, letters in Russian are rendered with a default font, which results in significantly wider labels and doesn't match the numbers. And I don't feel serif fits the minimalistic aesthetic the game is going for.

Comparison:
![image](https://user-images.githubusercontent.com/2567124/88288663-c65c8b00-ccfc-11ea-84c1-9f8f1a677e89.png) ![image](https://user-images.githubusercontent.com/2567124/88288686-ce1c2f80-ccfc-11ea-97bf-519decd39585.png)

Making `sans-serif` the last fallback font can help, I made a quick preview in the web version with Arial set as default (same as default sans serif); still a touch too wide, but more consistent with the numbers at least:
![image](https://user-images.githubusercontent.com/2567124/88289151-78945280-ccfd-11ea-8882-d237f6aa2fb0.png)

Any chance Russian can get a natively looking font?

**Comment by dengr1065** [comment]
note: fira sans condensed may be a good fallback font

**Comment by tobspr** [comment]
https://trello.com/c/7x5WLL64/306-cyrillic-font
