### ISSUE TITLE
 [Bug] (Cosmetic) Trashcan icon in blueprint paste is also rotated

### ISSUE THREAD

**Issue by P-Storm** [tobspr/shapez.io#492]
The icon is rotated. Looks like unintended because you can't rotate the trashcan manual. It doesn't break anything, but it is nice if it is consistent.

Screenshot: 

![image](https://user-images.githubusercontent.com/1581006/88410238-66d2ae00-cdd6-11ea-985d-008779004112.png)

Game version (steam):
1.1.18 @ Production @ 1092975

**Comment by SeaLife** [comment]
Cannot be reproduced in the current alpha build (the Trashcan is not rotateable in the current alpha build).

This kinda fixes this issue and would be available on Steam with the Wires update (probably). :)

Regards
SeaLife

**Comment by P-Storm** [comment]
Great to hear that it is already fixed, can be closed than 👍
