### ISSUE TITLE
Extremely low performance when launched from Steam on Linux

### ISSUE THREAD

**Issue by Pikaro** [tobspr/shapez.io#496]
Linux 5.7.6-201.fc32.x86_64
Fedora 32
Steam 1595519552
shapez.io 6.1.12

When launched from Steam, the game is unplayably slow right from the start. (I. e. with nothing to calcuate.) When launched from the command line, it's butter smooth. (Well, up to a point - I don't know when it starts to have issues on Windows. L16 is very choppy for me with an R9 3900X.)

You seem to be aware of the problem so this is basically just a pro forma report.

**Comment by tobspr** [comment]
Thanks, yeah I have no idea why TBH. Is it using steam play by any chance (Proton)? Then it'll be emulated

**Comment by Pikaro** [comment]
No, last I tried I wasn't able to launch it through Proton at all.

**Comment by jonaseberle** [comment]
Performance was ok for me when launched from steam. Quite smooth until the end. 30-60 (locked at 60) FPS depending how many objects are on screen.
I don't notice any performance difference between steam and running `...Steam/steamapps/common/shapez.io/shapezio` directly.

<pre>
Linux 4.15.0
KDE neon (Ubuntu-18.04-based)
Intel(R) Core(TM) i7-6500U CPU (using on-board Intel graphics)
shapez.io 1.1.18 @ Production @ 1092975
Steam 1595519552
</pre>

I am not sure which libraries affect browser/electron performance most. But I am happy to help troubleshooting. 

Sometimes the app does not exit cleanly and keeps a process running, though.

**Comment by Pikaro** [comment]
Oh, forgot the window manager in my report - I use i3 with Compton, but same results without Compton and when using Gnome.

I also didn't think the graphics card was relevant for an Electron game but it's an RTX 2080 Ti using driver version 440.100. (Same results with the previous one, .82 I think?)

**Comment by tobspr** [comment]
Closing since I have no idea on how to fix it
