### ISSUE TITLE
Improvement: Clicking an activated pin in the "upgrades" dialog should unpin the shape

### ISSUE THREAD

**Issue by jppresents** [tobspr/shapez.io#50]
Improvement: Clicking an activated pin in the "upgrades" dialog should unpin the shape.
Right now, you can only unpin by clicking on the shape where it is now displayed in the in the main UI.

Also that little pin could use a tool tip explaining what it does. It took me a moment to figure out.
If I didn't read a help text carefully that already explained it, sorry :) - still think tool tip would help.

**Comment by tobspr** [comment]
People don't read text though :D

**Comment by tobspr** [comment]
Also, how'd you know that you just unpinned it? Would the icon change?

**Comment by jppresents** [comment]
Right now "white" pin means clickable (and not yet pinned).
Then you click it, it gets "grey" and now it's pinned.
Now I think it should still be clickable again, to make it unpinned (and white) again.

**Comment by tobspr** [comment]
Coming in 1.1.9
