### ISSUE TITLE
Failed to Initialize Application

### ISSUE THREAD

**Issue by Vader-Tricks** [tobspr/shapez.io#501]
![Error](https://user-images.githubusercontent.com/68836826/88502652-5c5a1500-cf8c-11ea-9288-f12656203bb0.png)

We have tried every manner of uninstalling and re-installing. The only thing we do NOT want to do is reset because we don't want to loose our save data. We get the same error from both the desktop shortcut, the Steam shortcut, and we even tried running it as admin. Nothing changed the results.
We were able to play for the first day of purchase, then an update caused this error.
Running Windows 10

**Comment by tobspr** [comment]
You can reset it, then re-import your savegames from the savegames folder :)
Windows: %APPDATA%/shapez.io/saves
Linux: ~/.local/share/shapez.io/saves
