### ISSUE TITLE
Wire Merger Graphic Has Arrows in the Wrong Direction

### ISSUE THREAD

**Issue by MarkJepson** [tobspr/shapez.io#506]
Testing the Alpha release (1.2) from today. Noticed that the Wire Merger has the wrong arrows on it.
Reported in Discord  #AlphaBugs (@Harrier98)

![image](https://user-images.githubusercontent.com/14073633/88560934-aa235b80-d026-11ea-86b4-1ad15d00c2d5.png)

^^ Double arrow on top right when should be input

Wire Splitter appears ok. Seems to be corroborated by @FreakyWaves Music#1400 https://discordapp.com/channels/706121159405731910/729775585722630296/737320585033678888

**Comment by tobspr** [comment]
Planned :) Closing because it was never working, and I know about it already :)
