### ISSUE TITLE
Feature Request: Zoom to Mouse

### ISSUE THREAD

**Issue by sybrenstuvel** [tobspr/shapez.io#508]
Hello!

I just bought Shapez.io on Steam, and I'm already addicted 👍 

In many games & applications I enable Zoom to Mouse Cursor if such an option is available. I use this in Blender, as well as Planetary Annihilation and other RTS games. When enabled, using the scroll wheel doesn't zoom towards the centre of the screen, but rather towards the position of the mouse cursor.  OpenStreetMap and Google Maps also work this way. The big advantage is that you zoom in on what you're looking at, as usually you have your mouse cursor floating around there as well.

Would you be willing to add such a feature in Shapez.io as well?

Cheers,
Sybren

**Comment by dengr1065** [comment]
This is already done by #386. It should be a setting though, IMO.

**Comment by tobspr** [comment]
It's already in the alpha
