### ISSUE TITLE
Allow Markers to Create Columns

### ISSUE THREAD

**Issue by eyoung100** [tobspr/shapez.io#511]
Allow Marker creation to scale based on interface size

Super Small:
![SuperSmall](https://user-images.githubusercontent.com/5230163/88617335-02c11b80-d05c-11ea-9352-af5f84d0f115.png)

Normal:
![Normal](https://user-images.githubusercontent.com/5230163/88617526-79f6af80-d05c-11ea-8657-727a649c92a7.png)

Notice that the only way I can see all my Markers is if I use the Super Small Interface.  The behavior will occur again one I fill up the column in Super Small, and there are no more interface sizes to choose from.   It would be nice if the Markers were paginated, so I could see them all in the Normal Interface

Pseudo Code
```
iSize = Interface.GetSze
if iSize = Normal
    pager = 6 Markers
    columnCount = 0
else if
    ... //Test Every Size
end if

columnCount = totalMarkers / pager
// Output Markers to screen using value stored in columnCount
```

**Comment by tobspr** [comment]
Well .. that's a lot of markers

**Comment by tobspr** [comment]
I'll think about it. Closing here since I document everything on trello
