### ISSUE TITLE
Building Blocks Ideas for life improvement

### ISSUE THREAD

**Issue by Sejiko** [tobspr/shapez.io#513]
I have multiple Ideas for new Blocks that could improve our lifes.

### Lane swapper
This Block should function like the 2 lane merger but instead just switches the lanes 

### Track distributor
I think this block should be a 9x9 where you can map out wich line goes to which side, i would prefer it with a numbering system.
This Block could be used to send items to a storage and keep them there for an amount of time and if you need something you just rewire this block instead of all the lines.

If anything is not clear enaugh feel free to ask me.

**Comment by tobspr** [comment]
Thanks for the ideas, but I currently see no way how this would fit into the game :)
