### ISSUE TITLE
Improvement: Pinned Shapes should be on top of the list in the Statistics Dialog

### ISSUE THREAD

**Issue by jppresents** [tobspr/shapez.io#52]
Improvement: Pinned Shapes should be on top of the list in the Statistics Dialog
This would make it easier to check progress on the shapes that the player has already marked as important.

**Comment by tobspr** [comment]
What if they'd at least be marked special? Sorting them is a bit more annoying (though doable).

Also probably a good first issue

**Comment by jppresents** [comment]
well, they are already "marked" by their symbol.
I think scrolling through and looking for the symbol won't be much improved by scrolling through and looking for a special marker.

**Comment by MrAJGurney** [comment]
With regards to pinning, shapes seem to fall in four categories:
* pinned by user
* blueprint
* current goal
* everything else

If a shape is pinned, the blueprint, or the current goal should it be above everything else?

Should the statistics page indicate if a shape is in one of the three special categories (maybe with a small icon)?

**Comment by tobspr** [comment]
Closing, feel free to make a PR tho
