### ISSUE TITLE
i cannot quit ( suggestion )

### ISSUE THREAD

**Issue by Yourself1234** [tobspr/shapez.io#528]
i could only notice that alt+F4 does not quit the game. i have no idea if its intended, i was just wondering, could it be added ?

**Comment by tobspr** [comment]
Well, that could cause your savegames to break if the game is saving while you quit ...

**Comment by ekevoo** [comment]
If unable to trap the event and handle it gracefully as described by magneticflux, you can do a cautious rename-then-save instead of a blindly optimistic overwriting save. When loading, just try both files.
