### ISSUE TITLE
Bug: play.sh script doesn't work correctly on Linux

### ISSUE THREAD

**Issue by hexagonhexagon** [tobspr/shapez.io#53]
This is because the wrong line endings are used on Linux. Line endings on Linux are '\n' rather than '\r\n', causing the following error when I run it normally on Ubuntu:
![image](https://user-images.githubusercontent.com/25755516/83338635-497cda00-a294-11ea-8c24-64e822389f3a.png)
I manually changed the line ending type from '\r\n' to just '\n' and it worked just fine.

**Comment by tobspr** [comment]
Ah, thanks! Will fix
