### ISSUE TITLE
belt issues

### ISSUE THREAD

**Issue by satoshuni** [tobspr/shapez.io#532]
belts don't seem to line the shapes up properly. I have 4 shapes all of which go through 1 stacker per extraction site. along with this I made sure all the shapes have the same amount of turns (idk if turns affect speeds) but for some reason some shapes are closer spaced together then others. for more info the four shapes are pinwheel, circle, star, and square. only the pinwheel is slightly different cause I need to cut a shape in half but after that everything else is the same so ive come to the conclusion eh belts aren't working right. idk if this file will work for the world but here it is

[ACHEIVEMENT.docx](https://github.com/tobspr/shapez.io/files/5019342/ACHEIVEMENT.docx)

**Comment by satoshuni** [comment]
I should also note stackers seem to be going wacky on this world as well if you look at the very last line youll occasionally see a weird shape coming out that isn't the blue pointer with a white circle. idk what could be causing this since the way I have it set up it should evenly split up the four pieces of the shapes and recombine them properly. seems like it just doesn't want to work but thats just me.

**Comment by tobspr** [comment]
1) https://trello.com/c/6VOiTNQF/275-buildings-and-belts-are-not-as-fast-as-they-claim-to-be-eg-15items-s-instead-of-20

2) Check your factory
