### ISSUE TITLE
[Bug] Storage Building Doesn't output on both lanes

### ISSUE THREAD

**Issue by LMaster765** [tobspr/shapez.io#534]
In this picture, there are two lanes inputting color and only one output. The storage will randomly switch between not using the second output and using it (even if the storage is full). When not using it, it backs up the input lines. This causes machines that start with a storage building to sometimes only work at half capacity.

![Storage Bug](https://user-images.githubusercontent.com/69209061/89314926-40b7d400-d648-11ea-8dc5-cafe0c55f313.png)

**Comment by dengr1065** [comment]
this is partially intended, and most logic gates are based on that. storage is also used as overflow gate (most popular usage)

**Comment by LMaster765** [comment]
I understand the overflow part, I'm using that just above the part shown in the picture, but I feel like if there are two inputs, there should be two outputs, instead of clogging the inputs.

**Comment by dengr1065** [comment]
storages can output 1 item per tick max, having 2 items per tick would break overflow gates

**Comment by LMaster765** [comment]
I guess this is what I was thinking of: 
the storage would try to output to one lane first (like the merger) and would take two half lanes or one full lane and output it in the first lane. If more than one lane worth of shape or color is sent, then the excess would move over to the second lane, rather than clogging the inputs if the storage is full. I don't know if this is how it was intended, but I think it would be nice this way. It lets the storage act as an overflow into a new lane and a storage.

**Comment by tobspr** [comment]
This indented, but: https://trello.com/c/7uWprXsL/269-mark-preferred-input-on-storage-visually

**Comment by tobspr** [comment]
You can put a splitter after it, that *should* do the job
