### ISSUE TITLE
New game + option?

### ISSUE THREAD

**Issue by matthewmwps** [tobspr/shapez.io#538]
I wish to suggest the option for players to play a new savefile that would keep the unlock progress of other saves (but NOT the level progress). Basically to let us replay the game with all the tools available from the start to see what kind of stuff we can make

**Comment by MarkJepson** [comment]
@matthewmwps Can't you do this by zooming out, selecting everything and then deleting? If you save then you get the same thing. Not forgetting to export your save first 😉

**Comment by dengr1065** [comment]
@MarkJepson well, but you're on freeplay then
>>> unlock progress of other saves (but NOT the level progress)

**Comment by MarkJepson** [comment]
@dengr1065 By level progress I thought @matthewmwps was referring to built factories, which you can easily remove if you want to restart.  By exporting a save game (an optionally re-importing it to use later) before opening it and trashing everything you get the unlocks and the levels, and a clean map to play with. This could be done whether you are on level 12 or level 25+.

The next full release of the game will probably not allow the use of older savegames, but if they allowed this ^^ then I'd be happy.

**Comment by matthewmwps** [comment]
> @dengr1065 By level progress I thought @matthewmwps was referring to built factories, which you can easily remove if you want to restart. By exporting a save game (an optionally re-importing it to use later) before opening it and trashing everything you get the unlocks and the levels, and a clean map to play with. This could be done whether you are on level 12 or level 25+.
> 
> The next full release of the game will probably not allow the use of older savegames, but if they allowed this ^^ then I'd be happy.

Yeah no, the idea i had in mind was that you would start in an entirely different map at lvl 1 (where you gotta give the circles) and just have everything unlocked from the start. Sure you can just wipe the map and do it that way, but the way I suggest makes it easier to keep track of all the shapes you needed to make AND gives a new map so you have some extra spice to it.

**Comment by MarkJepson** [comment]
@matthewmwps Oh I see. I like that idea as well. I believe there is a save game editor that can do this. Basically you start a new map, Dave your game and then edit your unlocks: https://www.reddit.com/r/shapezio/comments/htyc5f/shapezio_save_editor_v10_release/?utm_medium=android_app&utm_source=share

**Comment by tobspr** [comment]
I'm also considering a sandbox mode
