### ISSUE TITLE
Adding quarter rotator

### ISSUE THREAD

**Issue by YPetremann** [tobspr/shapez.io#539]
the quarter rotator would only apply if their is only one quarter of a shape (layers allowed) and would rotate the quarter in his corner.

This would allow shapes like houses, hexagons and more

**Comment by pampogokiraly** [comment]
The problem with this buiilding that it could make shapes that look like a circle on a square, while in reality it is two circles on top of each other but the lower one is "quarter-rotated".
I actally like your idea but it needs some "fixing"/"polishing".

**Comment by tobspr** [comment]
Well I don't think this will fit into the current game
