### ISSUE TITLE
Issue: Can't distinguish between colors

### ISSUE THREAD

**Issue by mihakralj** [tobspr/shapez.io#54]
For color-blind people, it is very hard to separate yellow and green in the game. Select a more diverse color palette so people with various types of color blindness will be able to play

**Comment by bbarry** [comment]
Simply a slightly darker green would be nice and probably work like `#28a745` (the color of Github's comment button here) or even `rgb(30,234,0)`

**Comment by mihakralj** [comment]
the visual difference between white and cyan needs to be stronger too.

**Comment by tobspr** [comment]
Moved to trello https://trello.com/c/J4TNC5cY/159-color-blind-mode
