### ISSUE TITLE
Feature Requests : Undo, ability to rebind Selection keybind

### ISSUE THREAD

**Issue by grian32** [tobspr/shapez.io#540]
Feature Request 1 : Undo
Don't really need to say any more, keybind would preferably be ctrl+z and rebindable
Feature Request 2 : Ability to rebind selection keybind
It's kind of a weird keybind for selected, would be nice if we could rebind it so people can use something they're more used to, i understand why its not hold right click or something but i dont really get why you cant rebind it

**Comment by tobspr** [comment]
1) https://trello.com/c/Dp7kIfAW/304-undo-redo

2) Hm, yeah I will keep track if others have this problem too, feel free to make a PR btw :)

**Comment by grian32** [comment]
2. id make one except idk js at all lol soz
