### ISSUE TITLE
[Feature Request] Covered belts

### ISSUE THREAD

**Issue by johnfraser** [tobspr/shapez.io#547]
A variant of the belt that could unlock at level 18, that offers faster speed, but visually looks like a pipe of sorts (hyperloop?), with small arrows pointing the direction it's going.

Items going through it wouldn't be rendered, so it could replace how people use tunnels to improve performance.

This could also play in hand with lowering the multipliers during early game, and allowing faster speeds in late-game without introducing too much lag.

**Comment by tobspr** [comment]
I have something similar planned

**Comment by tobspr** [comment]
https://trello.com/c/LaPkVDPD/236-crates
