### ISSUE TITLE
The top right downward hub input doesn't accept items as fast as the others.

### ISSUE THREAD

**Issue by bbarry** [tobspr/shapez.io#55]
The top right input (circled in image) doesn't accept items as quickly as the others.

![image](https://user-images.githubusercontent.com/84951/83343307-8792f180-a2c6-11ea-8a94-c33678bad578.png)

This is most noticeable in Firefox from my testing. 

![image](https://user-images.githubusercontent.com/84951/83343363-4a7b2f00-a2c7-11ea-9867-9c5fc5a1c307.png)

**Comment by tobspr** [comment]
Does a full belt go into both? Or does it stall?

**Comment by bbarry** [comment]
The input belt to the top right corner was not entirely packed but more like the ones going in the bottom (about half the distance compared to them though). It was delivered slow enough that the inputs were not entirely gone before the next set arrived. There was an ever growing backup towards the blueprint item source before I moved that input to the next one over.

**Comment by bbarry** [comment]
Seems to be fixed with the current version.
