### ISSUE TITLE
x15 speed buildings slower than they claim to be

### ISSUE THREAD

**Issue by MarMar-1** [tobspr/shapez.io#551]
After reaching the final upgrade level for the belts and buildings, the buildings are slower than they are supposed to be while the belts perform as expected.

The easiest example to demonstrate is extractors:
Since extractors claim to produce 6 items/second and belts move 30 items/second, you should need 5 extractors to saturate a belt and deliver 1.8k items/minute. However, 5 extractors only deliver 1.5k items/minute.

I have not individually tested every building, but they seem to all be slow by the same amount.

This is super frustrating because it means having to increase the amount of each building by 1 if you want to fully saturate a line, meaning all production lines created with the correct ratio of buildings in a previous teir have to be modified if you want to maximize efficiency.

**Comment by tobspr** [comment]
https://trello.com/c/6VOiTNQF/275-buildings-and-belts-are-not-as-fast-as-they-claim-to-be-eg-15items-s-instead-of-20
