### ISSUE TITLE
Shapes switch layers when merged

### ISSUE THREAD

**Issue by gquinn** [tobspr/shapez.io#554]
![ShapezIO_Bug_20200809_cropped](https://user-images.githubusercontent.com/2108995/89728784-cc09de80-da27-11ea-8500-6eca8409ac82.jpg)

http://wiredcat.hopto.org/shapezio/ShapezIO_Bug_20200809_cropped.jpg

Notice how the white star is on top of the the blue circle, but after the merger the the star is underneath the circle.

**Comment by dengr1065** [comment]
This particular case is fixed by #138.

**Comment by gquinn** [comment]
Thankyou.
