### ISSUE TITLE
Show real time until next upgrade or level criteria is met

### ISSUE THREAD

**Issue by hyphz** [tobspr/shapez.io#57]
Based on the current production rate it should be easier to see how long there is to wait until the next upgrade.

**Comment by tobspr** [comment]
But isn't that kinda boring? I mean actually seeing that you need to wait 20 minutes would kinda open the opportunity to just step back and return then

**Comment by hyphz** [comment]
Wait, it's not supposed to be an idle game?

**Comment by tobspr** [comment]
Thats definitely not how you should play it

**Comment by hyphz** [comment]
Might be worth blocking that method then to avoid Pandemonium Warden issues, especially if the demo is on Kong where idle games are pretty much the default now :)

**Comment by tobspr** [comment]
Well, I won't prevent anybody but I just added a hint in level 1 that this game is not an idle game :P

**Comment by hyphz** [comment]
I saw that, the confusing thing is that it says that but even after hooking up 4 belts, you still have to wait. Maybe the missions/levels, or some other tracker, could be based on production/sec instead of production total? That way it's obvious to the player what they "should" be going for to have the designed game experience.
