### ISSUE TITLE
UX Improvement: Move the Key Bindings button into the list of settings.

### ISSUE THREAD

**Issue by MicahZoltu** [tobspr/shapez.io#589]
~~I use a Dvorak keyboard so the default key bindings are basically unusable.  Beyond that, I also find WASD uncomfortable.  Allowing users to rebind keys would solve both of these problems, along with a number of other problems related to static key bindings.~~

When I went looking for key bindings I clicked on Settings and then looked through the list of options and did not see an option for setting up custom key bindings.  The problem is that the Key Bindings are not part of the *list of available settings*, which makes it easy to miss them/overlook them when searching.

Proposal: Move Key Bindings into the list of settings, rather than having it be a separate button that is not part of the list of settings.

**Comment by dengr1065** [comment]
Hey, did you check Settings > Keybindings? :smile:

**Comment by MicahZoltu** [comment]
Ah, totally missed that because it wasn't part of the main list of options.  Will update this feature request to be a UX improvement to move the key bindings into the list of settings.

**Comment by dengr1065** [comment]
This is already done in latest version (unreleased).
![settings-tabs](https://user-images.githubusercontent.com/32245793/90992077-10fc4c00-e5b6-11ea-9da0-1fe28d2fbe35.png)
