### ISSUE TITLE
Chinese Localization

### ISSUE THREAD

**Issue by Luna1996** [tobspr/shapez.io#59]
Hello! Lovely game indeed! Bought at itch.io, but miss the steam key you send out yesterday. I'm more than happy to provide Chinese Localization if you are interested.

**Comment by tobspr** [comment]
> but miss the steam key you send out yesterday

Not entirely sure what you mean?
 
> I'm more than happy to provide Chinese Localization if you are interested.

Definitely! Right now there is no translation support though. Planned :)
