### ISSUE TITLE
Feature Request: Hotkeys for orientation instead of stepwise rotation

### ISSUE THREAD

**Issue by schaetzc** [tobspr/shapez.io#600]
Building would be much more comfortable (at least for me) if there was a way to assign hotkeys that select a fixed orientation for buildings instead of having to press <kbd>R</kbd> 1 to 3 times. Here's the idea:
- So far, all buildings have their outputs on one side. Therefore, all buildings have an intuitive orientation/direction. Players often say »the building is *facing up*« if its outputs are on top.
- If the settings allowed it, I'd like to assign ...
  - <kbd>W</kbd> = rotate the building so that it is facing **up**
  - <kbd>S</kbd> = rotate the building so that it is facing **down**
  - <kbd>A</kbd> = rotate the building so that it is facing **left**
  - <kbd>D</kbd> = rotate the building so that it is facing **right**
- For buildings with mirrored variants (I really hope every building will be mirrorable in the future), I'd like to either hold <kbd>shift</kbd> or press a key once (for instance <kbd>E</kbd>); and then press one of <kbd>W</kbd><kbd>S</kbd><kbd>A</kbd><kbd>D</kbd> to get the mirrored variant facing in the same directions mentioned above. The only difference is, that the supplementary inputs (like the painters color input) will then be on the opposite site.

**Comment by lflfm** [comment]
this is already there, check the keybinding options - by default it's the arrow keys

**Comment by EmeraldBlock** [comment]
I *believe* that feature was added after the creation of this issue

**Comment by schaetzc** [comment]
Thank you.
