### ISSUE TITLE
[FeatureRequest] Coordinate System with Hub at 0,0

### ISSUE THREAD

**Issue by strickdd** [tobspr/shapez.io#612]
Having a coordinate system for easier map navigation would be a great QoL improvement. Setting the hub at 0,0 would allow for quickly laying belts long distances towards the hub. Knowing the x or y coordinates of a belt/building/etc would also allow for an easier connection from a distance without continually zooming in/out to make sure it lines up.

**Comment by EmeraldBlock** [comment]
A coordinate system has already been implemented (which can be accessed in the alpha)

**Comment by strickdd** [comment]
Did not realize that. Didn't see it in the UI or settings. Thanks for confirming it's existence

**Comment by EmeraldBlock** [comment]
In case you still don't know, you can access it by pressing `F4` twice - the coordinates will show up in the bottom right.

**Comment by dengr1065** [comment]
you can press f4 twice in alpha to enable detailed debug info. also there's now chunk grid, also cool
