### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by anydot** [tobspr/shapez.io#62]
At the moment the game's icon is hard to see on Win10 taskbar:
![image](https://user-images.githubusercontent.com/78886/83527841-9ce76600-a4e8-11ea-82d1-702a5cd3ea31.png)

Having slightly colored icon (pastel colors?) or some border set could help

**Comment by dengr1065** [comment]
Looks like the favicon.ico (which is old standard and i don't like it):
<img src="https://beta.shapez.io/favicon.ico" width="64">
Linux builds use dedicated favicon.png, and macOS builds use favicon.icns
Windows builds should use favicon.ico which is bundled, but they don't for some reason. (I didn't look into Electron wrapper code yet)

**Comment by tobspr** [comment]
Yeah I should fix that, its copied at the wrong location during the build process

**Comment by tobspr** [comment]
Moved to trello https://trello.com/c/ykLhcv8K/162-better-favicon
