### ISSUE TITLE
Unlock the tunnel before the painter

### ISSUE THREAD

**Issue by Bqleine** [tobspr/shapez.io#625]
So I recently decided to do a new game and found out it's very hard to get 800 red circles in a reasonable time without portals

Since the painter has 3 inputs/output, you can't chain it exept with a portal and it make it a real mess to just put 3 of them.

![image](https://user-images.githubusercontent.com/51089082/91885070-6f48bf00-ec87-11ea-80b3-412e41aa61f7.png)

What I suggest is unlocking the portal before the painter to fix this problem

**Comment by EmeraldBlock** [comment]
The tunnel *is* unlocked before the painter (after level 5 vs after level 6)
