### ISSUE TITLE
[Feature Request] Multiplayer

### ISSUE THREAD

**Issue by Phandal** [tobspr/shapez.io#626]
I want to play this game but with a friend so we can both look at the same map and build on the same machines. It would make this game even more fun!

**Comment by minger0** [comment]
https://github.com/DJ1TJOO/shapez.io has got a beta version that runs on a server. I could not get it working locally though. 
@DJ1TJOO would you share instructions for developers on the multiplayer? That would help other devs to contribute.

**Comment by DJ1TJOO** [comment]
First of all, shapez.io is not made for multiplayer. There are lost of things happening at the same time. Therefore the multiplayer mod is not syncing everything thats happening. I've added some extra documenting for setting up a server. 

Do also note that this version is not the newest version. The newest version is a mod for the modloader that can be found here: https://github.com/DJ1TJOO/shapez.io-modloader/tree/MultiplayerMod and is on the modloader website too (http://mods.thomasbrants.nl). To let this work you need to host your own multiplayer server.
