### ISSUE TITLE
[Feature Request] Mirrored variant for the filter

### ISSUE THREAD

**Issue by qgustavor** [tobspr/shapez.io#631]
I tried implementing it myself:

![image](https://user-images.githubusercontent.com/1020670/92133552-e5136e80-edde-11ea-9cac-56d8ffef57ae.png)

I can send a pull request but the sprite is just mirrored (the shadows are wrong).

**Comment by scikadaei** [comment]
I definitely would like this as well. I totally built my MAM in the "wrong direction" (right to left) because I have to have extra room for the filters, but I was too far into it to start over. Mirrored filters would be awesome!

**Comment by EmeraldBlock** [comment]
note that any additional mirrored buildings are currently not planned, and suggestions to do so are typically rejected (typically considered boring and reducing the problem-solving with only one orientation)

...in the meantime wow are there a lot of mirrored building github issues

**Comment by qgustavor** [comment]
Well, I opened this one month before Wires update being released, but after it was released I think it's too late to add this feature now. Also, at that time it don't seemed to be something to be rejected, instead a simple and logic addition, in the other hand, if now there are many issues related to mirrored variants and those are being rejected it only makes sense rejecting this idea.

**Comment by EmeraldBlock** [comment]
I think the rejection of mirrored buildings has been present pretty much the whole time

**Comment by qgustavor** [comment]
I said that because the existence of mirrored variants in-game, like, IIRC, all different splitters and mergers, made it look it was a simple addition, is not like I'm looked for other rejected ideas.

**Comment by EmeraldBlock** [comment]
not exactly sure what you mean, but it's primarily a game design thing, not much to do with implementation troubles (don't really think anything's changed)
