### ISSUE TITLE
Lag after placing very long (> 1 minute at fastest speed) conveyors

### ISSUE THREAD

**Issue by Vaelatern** [tobspr/shapez.io#638]
Mostly when items are on it. My workaround is to break every so often to break and place a tunnel. This breaks up the conveyor's great length, and the game can scroll by quickly again.

This also affects jumping directly to the mark, because the ultra-long conveyor is rendered along the way, and the game stutters.

The longest of these conveyors meant at max upgrade it took over 10 minutes for my hub to receive differences in production at the other end. This is likely an edge case, and the mitigation of occasional tunnels works well.

**Comment by pampogokiraly** [comment]
I see your point but can i ask one thing?:
Why do you have a belt system, that takes 10 minutes for the shapes to travel from A to B
(i think i made a few mistakes in my english.. sorry about that)

**Comment by Vaelatern** [comment]
I wanted space to not consume local resources, and I scrolled until I found the shapes I wanted. That took quite some time.

**Comment by tobspr** [comment]
Ah, yeah long paths take long to render

**Comment by Vaelatern** [comment]
This seems fixed to me now, or maybe my paths are just much shorter
