### ISSUE TITLE
Unlock screen is blurred when "Primary Goal" is achieved with statistics window open

### ISSUE THREAD

**Issue by rpwjanzen** [tobspr/shapez.io#64]
If a player completes a "Primary Goal" while the Statistics window is open, the "unlock" screen opens but is blurry and illegible. It can still be dismissed by clicking on the very blurry cyan "dismiss" button.

**Comment by tobspr** [comment]
Yeah known issue, on my todo list :)

**Comment by tobspr** [comment]
Moved to trello https://trello.com/c/YfOGQiI5/161-imagepng
