### ISSUE TITLE
[Alpha] Pin shaped isn't the same as the required shape after level 18

### ISSUE THREAD

**Issue by Bqleine** [tobspr/shapez.io#650]
On the alpha version of the game, when you change level with the dev tools, the pin shape isn't the same as the one shown on the hub
![image](https://user-images.githubusercontent.com/51089082/92996967-eeec4e80-f50f-11ea-86fe-5a51394e67d2.png)

**Comment by BaleineSanguine** [comment]
Edit: the shape shown on the hub changes when zooming, it is sometimes correct and sometimes not.
Looks like overlapping shapes to me

**Comment by BaleineSanguine** [comment]
Edit: After further research, it seems like the previous shape displayed on the hub stays after changing the level. The bug also fixes itself when changing tab
