### ISSUE TITLE
How to test for undefined shape? 

### ISSUE THREAD

**Issue by maestrx** [tobspr/shapez.io#652]
When I use shape analyzer on shape that is not complete (one segment is not defined) i get signal saying that color and shape is not defined (the special symbol). But how to test for this special value using "compare" block on the signal layer? 

Ive tried by inserting output of "virtual cutter" that outputs "undefined" when it has not input. Unfortunately the compare block does not output 1 when both inputs are "unfedined"?

How to do it then?

**Comment by maestrx** [comment]
![image](https://user-images.githubusercontent.com/6150459/93016008-40531700-f5be-11ea-9a9f-a647ea9510fd.png)

**Comment by EmeraldBlock** [comment]
Just send the signal into a NOT, since shapes are considered truthy, while empty is considered falsy.

**Comment by maestrx** [comment]
Thanks, works like a charm :)
