### ISSUE TITLE
[Feature Request] Automatically adjust to keyboard layout

### ISSUE THREAD

**Issue by Jemsterr** [tobspr/shapez.io#653]
It would be nice if the game could automatically assign the hotkeys based on the existing keyboard layout, in a similar way to Minecraft and Factorio.

Currently, I have to switch my keyboard layout to QWERTY to be able to use the WASD keys.  In other games, such as Minecraft and Factorio, my dvorak keyboard layout is recognised, and the WASD changes to ,AOE automatically.

**Comment by Exund** [comment]
You can remap the keybindings in the settings
And given that this game uses web technologies it can't detect the keyboard layout. There is a way to detect key presses based on their physical position on the keyboard however but I'm not sure how the game handles that

**Comment by tobspr** [comment]
Yup, it's impossible with the current technology :)
