### ISSUE TITLE
Feature request: A way to edit existing "Constant Signal", and/or pipette includes reading the value.

### ISSUE THREAD

**Issue by thehans** [tobspr/shapez.io#658]
Currently it seems the only way to change a value from the constant signal building is to delete it and place a new one.
This is especially bothersome if a complex shape were hand typed in, and the player needed to tweak it slightly, they just have to remember exactly what they just typed I guess (or know to pre-emptively copy the text into clipboard themselves before closing the dialog).

Some way to edit these such as left clicking on one when no other tool selected could open the edit dialog with the current value still in the text box.

I also propose that if the building has pipette used on it, then when another is placed, it will remember the value from that one being copied.  It could still prompt for changes to the value in case the user wants to change it, but the prompt would auto-fill to that value.

**Comment by KeithLRobertson** [comment]
This is a huge pet peeve of mine. I'm surprised it isn't getting more traction.

**Comment by EmeraldBlock** [comment]
I have #1255, which implements this
