### ISSUE TITLE
Feature request: Upgrade mechanic that consumes shapes

### ISSUE THREAD

**Issue by simply-peachy** [tobspr/shapez.io#68]
I like the mechanic whereby blueprints consume shapes. This mechanic could also be used to upgrade buildings to their next available level (e.g. short bridges to long bridges), possibly consuming a quantity of shapes automatically to upgrade the factory and/or using the selection mechanic to manually upgrade. Perhaps it could also be used to apply tier upgrades to existing structures - which would encourage the player to provide a lot of upgrade shapes to keep all structures at maximum efficiency.

**Comment by tobspr** [comment]
I have something similar planned. Closed because this is already on trello :)
