### ISSUE TITLE
Crash when importing save made on bf2eee9..665360c

### ISSUE THREAD

**Issue by LeopoldTal** [tobspr/shapez.io#681]
The application crashes when importing a savefile made between commits bf2eee908fedb84dbbabd359a200c446020a340e and 665360c5a543d030d29fbbe2836ded9dd3672981 inclusive.

Importing one of these test savefiles:

- Nearly empty savefile made on bf2eee9: 
[savegame-bf2eee9-simple.bin](https://github.com/tobspr/shapez.io/files/5264424/savegame-bf2eee9-simple.bin.txt)
- Nearly empty savefile made on 665360c: [savegame-665360c-simple.bin](https://github.com/tobspr/shapez.io/files/5264165/savegame-665360c-simple.bin.txt)
- Level 28 savefile made on 665360c: [savegame-665360c-level-28.bin](https://github.com/tobspr/shapez.io/files/5264166/savegame-665360c-level-28.bin.txt)

crashes the app with error `1006 Migration: Could not reconstruct code for undefined`.

Saves made outside this commit range are imported correctly.

This is a regression introduced in 9075841768e1516a31c4bd63b89b99a2dddf19bb, which adds save migration.

**Comment by tobspr** [comment]
yes, thats desired. I don't migrate the alpha savegames :)
