### ISSUE TITLE
draw belts in straight lines

### ISSUE THREAD

**Issue by u19809** [tobspr/shapez.io#682]
It is difficult to draw long belts with a mouse and keep them straight.  
Perhaps add some modifier to lock horizontal or vertical drawing mode

**Comment by EmeraldBlock** [comment]
Can't you just use belt planner? (shift+drag)

**Comment by tonitch** [comment]
yhea but it's not possible over long distance because of the de-zoom

**Comment by EmeraldBlock** [comment]
You can press space to quickly drag a belt to hub, in case you want to do that

**Comment by jojolebestof** [comment]
You can use WASD + click
The mouse do not move.
The move is done by WASD key.

**Comment by jojolebestof** [comment]
> 
> 
> You can press space to quickly drag a belt to hub, in case you want to do that

Is it possible to add that in Tips?

**Comment by shawjef3** [comment]
I came here to post a similar feature request. I should be able to click the start location, then the end location. The game already does this for tunnels.

**Comment by shawjef3** [comment]
Heck, it should even auto-build tunnels when I place a long belt this way.
