### ISSUE TITLE
[Feature Request] Distribute for macOS via Steam

### ISSUE THREAD

**Issue by LeigerGaming** [tobspr/shapez.io#684]
I've just purchased the Steam version because I want to support the game despite this, but at the moment my only two options to play on my main computer (macOS) is:

- Play in the browser at https://shapez.io
- Play in a Windows VM or via Bootcamp (Apple's version of dual-booting)

I'd like to play natively on the Mac if possible.

Alternatively, some way to verify my Steam purchase via the website, so I can unlock dark mode etc in the web version?

**Comment by Exund** [comment]
To distribute the mac version on Steam the app needs to be built on mac (which tobspr doesn't have) and the app needs to be signed which apparently requires you to pay something.

You can try to build it yourself from source.

**Comment by LeigerGaming** [comment]
Thanks for the reply - that's a good point, hadn't occurred to me that it would likely need to be compiled on macOS.

I'll try building from source.

**Comment by izanagi1995** [comment]
As discussed with @tobspr, The plan is to have a separate repo where @tobspr will push the build made on windows, then the Travis build will fetch the built executable, will sign it, notarise it and push it to Steam.

**Comment by LeopoldTal** [comment]
Just opened #687 to do this!

electron-packager#71 probably breaks the plan to cross-build on Windows. Cross-building on Linux would work.

**Comment by dacoinminster** [comment]
I love this game on web, and I will buy it on steam once it is available for OSX!

**Comment by izanagi1995** [comment]
Coming soon !

**Comment by balu-** [comment]
bought it on steam before i saw that its only windows. I'd love to play the full version.

**Comment by vifi42** [comment]
any News on this matter? Love playing the game in Browser, but would love to play It directly on my Mac!

**Comment by jw2476** [comment]
Just build it from source

**Comment by 2xAA** [comment]
What are the problems with building for macOS? If it's not just the money for the dev license I can lend a hand.

I've been through the pains of signing and notarising electron apps, both on Travis and GitHub Actions, fairly recently - would be more than willing to give my time to get the build working on CI if needed.

Please @ me :)

**Comment by nderambure** [comment]
My vote too for a mac version ;)

**Comment by testinnplayin** [comment]
I just tried this game last night in a Brave browser and really like it. Has anyone tried building from source on an Apple Silicon Mac? I'm just curious.

**Comment by tobspr** [comment]
macOS is now supported: https://store.steampowered.com/news/app/1318690/view/3178987160554616924
