### ISSUE TITLE
Binding rotate to middle click works everywhere but blueprints

### ISSUE THREAD

**Issue by yorickvP** [tobspr/shapez.io#693]
I've bound rotate to middle-mouse-button, this works well for most places, but not blueprints. When I attempt to rotate blueprints, they are indeed rotated, but also pasted at the same time.

**Comment by madsen** [comment]
I have the same problem.  It's really annoying.  Binding "Planner: Switch side" to MMB has a similar problem; it switches and immediately places the belt.

**Comment by adalovebass** [comment]
Just coming to add a +1. I also had an issue, I don't remember it exactly, where binding... rotate(?) to RMB would deselect the current tool.
