### ISSUE TITLE
[Feature Request] Default keybinding in translation file

### ISSUE THREAD

**Issue by jojolebestof** [tobspr/shapez.io#697]
All country have not a US QWERTY keyboard layout (in France it is AZERTY). Default up, left right and down move (WASD) are sometimes a litle bit no easy to use. If it is possible to have the default keybinding defined inside the translation file, each country can define the good keys (in particular for navigation keys).

**Comment by TrueSalmon** [comment]
I agree. I'm trying to look for the least painful way of fixing this locally, but this should really be a game option.

**Comment by dengr1065** [comment]
There might be a separate `keymaps-la-ng.yml` for every language, but how will you handle language changes? Ask whether to keep old keybindings?

**Comment by tobspr** [comment]
Shouldn't that be a matter of selecting the keyboard layout additionally to the language in the settings?  Considering
