### ISSUE TITLE
Impassible Level Goal

### ISSUE THREAD

**Issue by jmeggitt** [tobspr/shapez.io#7]
https://github.com/tobspr/shapez.io/blob/2161aa680ef1a03dbadce1fa3763745ed754474d/src/js/game/tutorial_goals.js#L95

The current level 10 goal requires the use of the star shape to unlock the stacker. However, the star shape does not spawn on its own and must be assembled.

**Comment by tobspr** [comment]
Will fix

**Comment by jmeggitt** [comment]
The discord clarified that it does spawn on its own, but in some examples it is missing due to very unlucky RNG.

**Comment by tobspr** [comment]
I will ensure that there are always some stars next to your hub
