### ISSUE TITLE
Button to advance to next level is cut off

### ISSUE THREAD

**Issue by binarycow** [tobspr/shapez.io#71]
Sometimes, the button to advance to the next level is cut off.  I was not able to advance from level 1 to level 2 without refreshing the page (that bypassed the 'next level' screen).  I didn't get a screenshot of that one, but here's another one showing the issue....

![image](https://user-images.githubusercontent.com/37249876/83933729-388f0580-a779-11ea-8614-589f49b9ac28.png)

I *do* have the interface scale to "Huge" (so I can see the "goal" items on the left side of the screen better.)

**Comment by tobspr** [comment]
Will fix! :) (PS: Good first issue)

**Comment by tobspr** [comment]
Is this with an UI scale different to "regular"?

**Comment by tobspr** [comment]
This is just a setting with ui scale "huge"
