### ISSUE TITLE
[Bug] Splitter duplicates a block when having different Shapes

### ISSUE THREAD

**Issue by DragonDev1906** [tobspr/shapez.io#742]
## Actual Behaviour
As shown in the Image below the Splitter doesn't work correctly when different shapes are used.
Both sides are identical, only the input differs. The splitter that doesn't seem to work correctly is the bottom most splitter.

On the right side it works as expected (4 tiles in, 4 tiles out) but the left side outputs 5 tiles instead of 4.

## Expected Behaviour
Both sides should output the same Items after Splitting. The only difference should be the lower left tile.

## Additional Info

- All Full-Square Inputs are comming from the same Miner(s)
- The production was stopped for taking the Image
- Both examples still work after copying or rebuilding them
- I have included the creation of the Input for this splitter in case this is importent (although I don't think so)

![grafik](https://user-images.githubusercontent.com/8270201/94864075-bddeaa00-043b-11eb-8909-d867b311f93e.png)

**Comment by EmeraldBlock** [comment]
This bug is known, and should have been fixed in the current beta.
