### ISSUE TITLE
Belt Reader may slow down the belt they are attached to

### ISSUE THREAD

**Issue by kdltr** [tobspr/shapez.io#748]
The title says it all. I get this weird behavior when placing a reader on a fast belt: as you can see the extractors and belts have a capacity of 14 items per second, but one of the reader measures 12 and the core receives 26 squares in total, in this example.
I’m on master of this date, commit beb09a9e3e985440fb8289281b367f4db40f24c6
Setting a higher tick rate seems to solve the problem in this example.

![quantum-belt](https://user-images.githubusercontent.com/19929894/94991321-abbb5380-0582-11eb-83ad-4da42423c340.png)

**Comment by TastyPi** [comment]
I've experienced the same issue, adding a reader to a belt running faster than 12 caused the belt to slowly fall down to 12 (e.g. shows 14 then slows down to 12). Increasing the tick rate fixed this for me.

**Comment by heav-4** [comment]
same here. its only fixed on 240hz

**Comment by obmotum** [comment]
same here. setting it to 120Hz also fixes it, but the game gets really laggy then

**Comment by jpsalis** [comment]
Yeah, I noticed that as well. It runs at full speed for a few seconds, then seems to slow down. Splitting the belt in two then reading each lane seems to properly send and count all items through, maybe this works temporarily, I guess?

**Comment by tobspr** [comment]
Fixed in 1.2.2
