### ISSUE TITLE
game cuts runs at 20fps but the use processor max. 40%

### ISSUE THREAD

**Issue by miclemen** [tobspr/shapez.io#788]
he game cuts runs at 20fps but the use of graphics is 5% and the processor max. 40% and the frames it loads minimally (sorry my english is bad)

**Comment by EmeraldBlock** [comment]
Assuming you mean that the framerate is low, I think it's because the game runs on JavaScript, which is single-threaded and isn't able to take advantage of all of a computer's resources.

**Comment by miclemen** [comment]
so I guess there's nothing you can do about it
