### ISSUE TITLE
Pasting a Blueprint with tight components will sometimes reroute belts incorrectly

### ISSUE THREAD

**Issue by msauper** [tobspr/shapez.io#791]
When I create tight production lines, my belts will often get rerouted incorrect when I create a blueprint and then use it.  Most often it is a very short tunnel with a turn that is just after a merger. a one block belt is created from the splitter/merger to the input, replacing my one block turn from the tunnel exit to the input.  Another common culprit is the trash can. A one block belt on an output going to a tunnel or merger, will be replaced with a one block turn into the trash can.  I often need to go back after pasting a new production line and correct the one block belts to go from and to the correct inputs and outputs.  I have verified that the blueprint image is correct and the change does seem to occur during the paste.

**Comment by EmeraldBlock** [comment]
Duplicate of #34 and #214

**Comment by msauper** [comment]
Sorry, I searched and did not find it.  I'll close it since it is already on the list to be fixed.
