### ISSUE TITLE
Tunnel Connection Graphics

### ISSUE THREAD

**Issue by jmeggitt** [tobspr/shapez.io#8]
When replacing a tunnel entrance for a preexisting tunnel exit, the green line indicating a connection between them will not appear.

**Comment by tobspr** [comment]
I think only the tunnel-exit automatically detects this, this would require a change in `MetaUndergroundBelt::computeOptimalDirectionAndRotationVariantAtTile` to also check for tunnel exits. I added it to my todo list

**Comment by tobspr** [comment]
Fixed with 1.1.0
