### ISSUE TITLE
Steam version gets confused with save games - Broken cloud saves...

### ISSUE THREAD

**Issue by Toastgeraet** [tobspr/shapez.io#813]
Today i started playing on another computer and i started a new save game with the wires update (Lets call it Save W). Later i switched to my previous save game which i started without the wires update (call it Save A). I noticed, that my save A was not quite up to date with my latest additions from my other computer. A few hours and a pc restart later i wanted to continue Save A, but Save A and save W were missing, instead, now it only shows the save game that it should've showed from the beginning. 

Steam did not show any save game conflicts, as it usually does in these cases.  This is weird and frustrating.

**Comment by tobspr** [comment]
Hm, thats a steam cloud issue though :/
