### ISSUE TITLE
Clicking &#9432; (i in circle) on pinned shape unpins that shape.

### ISSUE THREAD

**Issue by AdJaGu** [tobspr/shapez.io#815]
On the main screen of the game clicking the &#9432; that is to the left of a pinned shape unpins that shape instead of bringing up the layers popup. The current required shape and the blueprint shape are unaffected and work as intended. On the upgrades page clicking the &#9432; to the right of a shape works as intended.

Before today I did not experience this issue. I run the game through Steam and have been on `1.2.0` since I purchased the game. I have also tested this today on `shapez.io` and also experience the issue there too.

**Comment by scherre** [comment]
I'm having this issue too. Running most recent version from Steam and haven't had this happen before this update.

**Comment by Harkler** [comment]
I am having this issue as well. Here is a video of it in action. I've attached my save file as well. https://youtu.be/SSQiLerueIQ

[Save file.zip](https://github.com/tobspr/shapez.io/files/5471628/Save.file.zip)

**Comment by darkwater4213** [comment]
I can confirm this. It is kind of frustrating.
