### ISSUE TITLE
[BUG] ExtractorVII only outputting 12 item/s

### ISSUE THREAD

**Issue by Eldiabolo21** [tobspr/shapez.io#827]
Hi everyone, 

so i came across this bug in the latest version of the game (1.2.0) 
The Extractor VII only outputs 12 items/S even though tooltip says it should be 14/s.

The conveyor seems to work with 14 items/S as intended as you can see in the screenshot, that there are gaps on the belt. 

Please see attached screenshot
![Screenshot from 2020-10-10 13-14-57](https://user-images.githubusercontent.com/5549781/95653710-f09f3700-0afa-11eb-8b8f-f261efede712.png)

**Comment by EmeraldBlock** [comment]
I am pretty sure this is the fault of the reader. Try splitting the lane into two and reading the resulting half-lanes.

Duplicate of #781, I feel

**Comment by Eldiabolo21** [comment]
Ah sorry my bad, didnt search for exsiting issues... Definitely duplicate.
