### ISSUE TITLE
[Feature Request] Add Layer Number numbers to Viewing Shape layers

### ISSUE THREAD

**Issue by EmileAvatar** [tobspr/shapez.io#833]
When viewing a shape layer (specifically those of 3 and 4 levels with complex shapes. 
Please add a Number on the eg top left had side so that it is easier to view which shape is on the specific layer.

Is sometimes confusing which shape goes on the the specific layer

![shapes layers](https://user-images.githubusercontent.com/40697228/95666392-5c17f180-0b59-11eb-9aa2-4a4e20a7c35b.jpg)

**Comment by tobspr** [comment]
https://trello.com/c/0TzAgEjp/508-add-layer-number-in-shape-viewer
