### ISSUE TITLE
Double Painter performance below advertised

### ISSUE THREAD

**Issue by vanyamil** [tobspr/shapez.io#842]
Here is the setup. 12 input circles, 12 input green dye. Upgrades are Belts 5 (12 / s), Paint 4 (double painter advertised as 1/s for each input, aka 2/s of output).

![image](https://user-images.githubusercontent.com/16938366/95678127-918fff80-0b98-11eb-8dda-4b8d904b7175.png)

Performance at about 95% (5.7 average of 6).

**Comment by ktsimpso** [comment]
I have the same issue. Tried adjusting to all tick rates of 60, 120, and 240 but no change in behavior. Regular painter seems to work as expected.

![painter_bug](https://user-images.githubusercontent.com/5854382/95800171-9ee9de80-0cab-11eb-9400-c8b312d490b0.png)

**Comment by tobspr** [comment]
known bug
