### ISSUE TITLE
[Feature Request] Cycle right-to-left through building variants

### ISSUE THREAD

**Issue by santa-klaus** [tobspr/shapez.io#845]
Similar to being able to rotate buildings counter-clockwise by holding shift it would be great to also be able to cycle through the building alternatives from right to left, i.e. in the other direction, e.g. by also holding shift. Especially the combiner/separator with its 5 alternatives can be quite annoying to cycle through.

**Comment by EmeraldBlock** [comment]
#790 adds this, though not yet merged

**Comment by tobspr** [comment]
done in 1.2.2
