### ISSUE TITLE
[Feature Request] The lenght of windows around names of buildings

### ISSUE THREAD

**Issue by RevosCZ** [tobspr/shapez.io#847]
I was wondering, would it be possible to make the lenght of the buildings window object change depending on the lenght of the text, so it is not covered behind the picture?
Not sure about other languages, but in czech language, there is not really a shorter word for some of those expressions that would have the same meaning or make sense, beside cutting a word in half, or making an entirely new word similar to it. :/
![3](https://user-images.githubusercontent.com/72229413/95684070-448b4800-0bef-11eb-8217-3758b404c0b3.PNG)
![2](https://user-images.githubusercontent.com/72229413/95684071-4523de80-0bef-11eb-897d-b3576e79ed5b.png)
![1](https://user-images.githubusercontent.com/72229413/95684073-4523de80-0bef-11eb-8ae0-4af579deef6a.png)

**Comment by tobspr** [comment]
I think the fix here would be to use a shorter description, at least in other languages it seems to be fine

**Comment by tobspr** [comment]
I'd be open to a PR tho
