### ISSUE TITLE
The game stay open when we quit the game.

### ISSUE THREAD

**Issue by Cassetete** [tobspr/shapez.io#848]
The game "stay" open when we quit the game.

To reproduce : open the game, then, quit the game. Steam detect that the game stay open. No game's process in process manager. I must quit Steam and force the quit.

I think it's probably when Steam sync the save because when I force the quit, and reopen the game, I have a "sync alert". 
Note : I don't have this bug with my others games.

Behavior : When the game close, the sync save don't take "infinite time".

**Comment by tobspr** [comment]
Known bug and I don't really have a fix

**Comment by lflfm** [comment]
Why is this closed? It's a bug that still exists and I found no other open issue with this...

**Comment by EmeraldBlock** [comment]
closed as "won't fix"
