### ISSUE TITLE
[BUG] Pinned item does not clear when the level is complete

### ISSUE THREAD

**Issue by leetrout** [tobspr/shapez.io#851]
![image](https://user-images.githubusercontent.com/524648/95686680-5fe55b80-0bcd-11eb-89b1-be488153e079.png)

The automatic pinning of level goals isn't clearing when the level is complete in the steam version.

Restarting the game didn't fix it either.

Maybe related to #815 and #839  ?

**Comment by EmeraldBlock** [comment]
Uh, that's the blueprint shape (note that there is a copy icon next to it). It remains pinned forever, as you use it to use blueprints.

**Comment by leetrout** [comment]
> Uh, that's the blueprint shape (note that there is a copy icon next to it). It remains pinned forever, as you use it to use blueprints.

Ok, thank you. The behavior was different compared to the bug of being able to click the info circle to remove these items on the side. It is not obvious to me that this was serving as some sort of currency count (which I found on Fandom). 

Maybe there's something else that could differentiate this? Maybe I missed this explanation somewhere?

**Comment by EmeraldBlock** [comment]
Levelling up should have shown you a screen explaining blueprints.

**Comment by leetrout** [comment]
I quit the game as soon as I leveled up yesterday and just fired it back up so I must have missed the part about that being a permanent pin.

**Comment by Hyperion-21** [comment]
> Maybe there's something else that could differentiate this? Maybe I missed this explanation somewhere?

On the left of the pinned shape is an i symbol, which when clicked shows you what layers the shape has. Also on the left is a symbol representing what the pin is: a crown for progression, paper for blueprints, and a pin for everything else.

**Comment by EmeraldBlock** [comment]
![image](https://user-images.githubusercontent.com/69981203/95687250-0cbcda00-0bc8-11eb-8a73-d1288f72bec5.png)
It is not explicitly mentioned, but I feel the provided description makes it clear enough why the blueprint shape is still pinned.

**Comment by leetrout** [comment]
> On the left of the pinned shape is an i symbol, which when clicked shows you what layers the shape has. Also on the left is a symbol representing what the pin is: a crown for progression, paper for blueprints, and a pin for everything else.

@Hyperion-21 makes me want tool tips when hovered over those! Thanks for the explanation.
