### ISSUE TITLE
Level 26 shape

### ISSUE THREAD

**Issue by JoeHalasz** [tobspr/shapez.io#853]
Just like the bug on the old max level... 
The size on the top right star gets smaller when stacked on top of the blue and grey circle.
I attached a picture of it. Switching the inputs doesnt work this time either because that makes the wrong shape. 

![bug](https://user-images.githubusercontent.com/19522902/95698708-8d9fc400-0c10-11eb-8e23-585560b394ad.png)

**Comment by EmeraldBlock** [comment]
This is known and has already been fixed (not yet updated)

**Comment by JoeHalasz** [comment]
thanks so much that did fix it
