### ISSUE TITLE
[Bug] Belt reader visual display slower than wires values

### ISSUE THREAD

**Issue by redstonedude0** [tobspr/shapez.io#855]
![Screenshot from 2020-10-12 10-25-01](https://user-images.githubusercontent.com/9257710/95729917-7941e280-0c75-11eb-8915-fe23ebf11b80.png)
If you have a flow through a reader, and then stop the flow, the wires layer almost immediately detects the flow has stopped and outputs a '0', however the visual display on the reader continues to read the flow rate for several seconds (sometimes still climbing) despite the belt stopping.

**Comment by EmeraldBlock** [comment]
I am pretty sure this is to do with how each is calculated. The displayed number takes an average over a long interval, while the wires output just cares what the current state is.

**Comment by redstonedude0** [comment]
Ah, it might be then that the list of values isn't getting a 0 added to it if the belt isn't flowing i.e. if it's the last 10 ticks the list goes from [15,15,15,15,15,15,15,15,15,15] to [15] to [] (this is when it displays 0) rather than to [15,0,0,0,0,0,0,0,0,0], which would give a smooth average - currently it seems to drop abruptly from the flow rate to 0 after a large time interval.

**Comment by tobspr** [comment]
The belt reader measures the average distance between items on the belt instead of doing snapshots, because that is the only way to be independent of the tick rate.
