### ISSUE TITLE
Cutter lowers floating layers

### ISSUE THREAD

**Issue by bastiandg** [tobspr/shapez.io#857]
In some cases the cutter lowers a top layer shape down in others it doesn't 

As seen in the screenshot the layer 3 shape on the left is lowered down to layer 2.

![cutter-issue](https://user-images.githubusercontent.com/414431/95769577-64d30980-0cb8-11eb-872f-444d11e1a877.png)

The version is the latest from steam. Reloading the game didn't help.

**Comment by EmeraldBlock** [comment]
This is intentional - Empty layers are strictly unallowed.

**Comment by bastiandg** [comment]
Thanks for the reply!

It would be helpful to clearly communicate this to the player. I was having a hard time to discern the behavior as it seemed random and thus opened this issue.
