### ISSUE TITLE
ERROR: There are no scenarios; must have at least one.

### ISSUE THREAD

**Issue by Quix0r** [tobspr/shapez.io#858]
I got this error message with `yarn` 0.32+git in the root directory. What am I doing wrong?

**Comment by LeopoldTal** [comment]
Seems to come from this: https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365

You can check with `which yarn`, and either uninstall `cmdtest` or provide the full path to the correct `yarn`.

**Comment by tobspr** [comment]
^
