### ISSUE TITLE
[Doc] python2 is not on the dependency list

### ISSUE THREAD

**Issue by Seppel3210** [tobspr/shapez.io#862]
Because python2 is finally becoming somewhat obsolete I didn't have it installed on my system anymore.
This caused an error while running `yarn` in the gulp directory.
(this isn't a huge error but I was a little bit confused at first because I seemingly had all dependencies installed)

**Comment by AdJaGu** [comment]
I don't have `python2` installed (only `python3`) and I was able to build `shapez.io`.

I did receive errors with `yarn` in the `gulp` directory when I had `node` 14 installed. Downgrading to `node` 12 provided successful builds for me. Which version of `node` are you running?

**Comment by dengr1065** [comment]
It depends on your OS - if you have prebuilt binaries, you don't need python2 (that's the case on most systems). But if you use something like ARM, or some unsupported version of Node, you'll need python2.

**Comment by tobspr** [comment]
^
