### ISSUE TITLE
 problem saving game

### ISSUE THREAD

**Issue by miclemen** [tobspr/shapez.io#867]
I bought the game on Steam, but during the last update I turned on the game and what I saw here with forgiveness upset me from level 17 and jumped there 18 without warning to a new level, but ok, I was upset that I had 1 , 3 million bluprints and rubbed here 40 thousand it annoys me the most, and I don't mind that everything else has been reset on save I have 1300 minutes, so it annoys me

**Comment by EmeraldBlock** [comment]
The loss of progress is due to rebalancing changes in the game; overall, everything is smaller and slower.

**Comment by miclemen** [comment]
so isn't it possible to givate it there via the developer mod?

**Comment by EmeraldBlock** [comment]
There is a sandbox mode, though it's not in the standalone version. If the lack of blueprints doesn't actually cause you any issues, I recommend just moving on and making more.

**Comment by miclemen** [comment]
well, and I wanted to ask if such large updates are planned in the future, because practically still hitting [zero] bi bil neslll progress will remain, but the problem is the upgrade

**Comment by miclemen** [comment]
no update if the upgrade shapes change so much
