### ISSUE TITLE
Balancer interacting with wires layer

### ISSUE THREAD

**Issue by Zalosath** [tobspr/shapez.io#886]
The balancer will show red crosses in it's inputs/outputs if there is a wire in the way on the wire layer. Causes no problems just a visual glitch.

**Comment by Zalosath** [comment]
![image](https://user-images.githubusercontent.com/49979347/96115638-2d927180-0edf-11eb-8489-5d483099bc21.png)
![image](https://user-images.githubusercontent.com/49979347/96115673-3b47f700-0edf-11eb-8856-61717e7f6847.png)

**Comment by EmeraldBlock** [comment]
Duplicate of #648
