### ISSUE TITLE
[Feature Request] Multi-lane belts

### ISSUE THREAD

**Issue by cssinate** [tobspr/shapez.io#890]
It would be awesome when using the belt planner to be able to lay down multiple rows of parallel belts at the same time. Perhaps if you're on belt planner and you use the scroll wheel, it increased the number of belts you're placing.

![belts_planned](https://user-images.githubusercontent.com/25226452/96183143-77da1980-0f04-11eb-8b14-57329049853a.jpg)
![belts_placed](https://user-images.githubusercontent.com/25226452/96183145-77da1980-0f04-11eb-8df5-e54a331860be.jpg)

**Comment by eliana-bb** [comment]
(Minor addendum/suggestion: Make this cost blueprint parts? It's very similar in concept to blueprinting.)

**Comment by darkwater4213** [comment]
I agree. Or possibly a different, easier type of shape?

**Comment by cssinate** [comment]
> I would also like to see being able to put multiple turns in the belt planner... maybe by pressing caps lock?

This would be much more difficult to implement if the multi-lane gets implemented. You'd have to calculate that any given turn isn't too tight. In addition, how do you handle someone crossing over on their own path they're currently planning? I'm not saying it's impossible, I'm just saying there are some challenges with multiple turns.

**Comment by darkwater4213** [comment]
Hmm... You have a good point. Maybe you could choose between the two and pay 10 or so blueprint shapes per turn or extra lane?

**Comment by darkwater4213** [comment]
Just thought of a potential problem... How would the game know which direction to add belts, and how would it deal with an even number of belts?

**Comment by scikadaei** [comment]
Yes yes yes, please implement this! I finally started to create a little section of multilane belts and just copy and paste it because I'm always using many lanes of belts at once.

**Comment by tobspr** [comment]
Hm, while I see the benefit, I feel like this might be a bit too OP
