### ISSUE TITLE
[Feature Request] Steam Purchase Verification for Browser Version Users

### ISSUE THREAD

**Issue by DanDeMarbre** [tobspr/shapez.io#891]
I have purchased the game from Steam in order to support its development, but am restricted to using the browser version as I do not own a PC.
Would it be possible to add a steam purchase verification mechanism into the browser version in order to disable the purchase prompts?
Thank you.

**Comment by constantoine** [comment]
It would be possible by using the steam API, I guess? The thing is that the check would probably just set a boolean somewhere, so it would be easily circumventable. Then again, this is an open source game, so trying to to something smarter than that would probably be said to be enforcing DRM.

Am I wrong in my assumption that the browser version is the full version with a boolean stuffed somewhere, or is it a fully different build?

**Comment by DanDeMarbre** [comment]
> This feature already been suggested on the Trello board for shapez.io. You can vote for it over there. Here is the link: [Allow playing full version on web after purchase](https://trello.com/c/BxYKbmiR/278-allow-playing-full-version-on-web-after-purchase).

Just a clarification, I am not asking for full features in the browser version (I appreciate the potential limitations). Only the ability to remove the prompts to purchase for users who have made a purchase.

**Comment by tobspr** [comment]
What @AdJaGu  said
