### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by fedfontana** [tobspr/shapez.io#892]
I don't know how to reproduce it, but this sometimes happens when I move around using the mouse: 
![image](https://user-images.githubusercontent.com/56149552/96247497-80852b00-0faa-11eb-86db-f8c856520f18.png)

**Comment by EmeraldBlock** [comment]
This is known all too well, and I believe it is caused by running out of vram (which I *think* is not a game issue)

**Comment by fontafederico** [comment]
I expected this to be known, but i opened an issue just in case. Anyhow, closing and opening the game again fixes it, so I guess it's not that bad, considering how fast the game loads
