### ISSUE TITLE
[Bug] .itch.toml file incorrect.

### ISSUE THREAD

**Issue by JulianWebb** [tobspr/shapez.io#899]
*Copy of [report](https://discordapp.com/channels/706121159405731910/706122201077645333/766967265412644874) in the #bugs channel on the Official Discord*

The game crashes when attempting to launch through the itch.io app because the including .itch.toml file is making it try and find files that do not exist in the platform specific builds. To fix this, the builds should have unique .itch.toml files that only contain actions that point to files that exist in that platform's build.(edited)

Here is a screenshot of the error from the itch.io launcher:
![image](https://user-images.githubusercontent.com/471907/96348350-f8139280-105c-11eb-90d8-48e82088b2c8.png)

The solution would be to create platform specific .itch.toml files and change [this line](https://github.com/tobspr/shapez.io/blob/c4d709b8e46d2b3712b8775a42bba2c598fe9313/gulp/standalone.js#L102) to include the specific one. 

An example of another electron application doing so through Gulp can be seen [here](https://github.com/tobspr/shapez.io/blob/c4d709b8e46d2b3712b8775a42bba2c598fe9313/gulp/standalone.js#L102).

Thanks!

**Comment by santa-klaus** [comment]
I think the last link in your post got mixed up, it also points to the line to change.

**Comment by JulianWebb** [comment]
Good catch @santa-klaus, it was meant to point to this: https://github.com/ct-js/ct-js/blob/develop/gulpfile.js#L435

**Comment by tobspr** [comment]
Tracking here: https://github.com/tobspr/shapez.io/issues/899
