### ISSUE TITLE
Use building selection hotkey to cycle through building variants.

### ISSUE THREAD

**Issue by ttepasse** [tobspr/shapez.io#900]
Currently to select a specific building variant first you select the building type with a hotkey like <kbd>2</kbd>, then use <kbd>T</kbd>  to cycle between variants of the building. While I get the logic of differing between selecting and cycling, the switch from <kbd>2</kbd> to <kbd>T</kbd> is some friction. I'd prefer this:

*Nothing selected* → <kbd>2</kbd> → *last selected combiner* → <kbd>2</kbd> → *next combiner* → <kbd>2</kbd> → … → <kbd>ESC</kbd> → *nothing selected*

**Comment by tobspr** [comment]
Hm , that seems a bit intuitive to me, I see the issue but I don't like the solution

**Comment by sandorex** [comment]
I would like this at least as an option though
