### ISSUE TITLE
[Minor Bug/Oversight?] "Your Game Was Saved" Save Icon Not Updated

### ISSUE THREAD

**Issue by eliana-bb** [tobspr/shapez.io#905]
The save icon in the top right is the new one -- the cleaner, more artstyle-compliant one.
![image](https://user-images.githubusercontent.com/63822830/96374561-0df68580-1139-11eb-9dc2-3ccd76ec0182.png)
But upon saving the game (manually or automatically), the older, uglier save icon pops up in the bottom right corner with the alert:
![image](https://user-images.githubusercontent.com/63822830/96374590-34b4bc00-1139-11eb-8477-f2f90999afe8.png)
(Only notable difference is the two lines in the middle of the floppy disk's label)
It's a very minor, low-priority visual inconsistency.

**Comment by Ichitran** [comment]
I can work on this one
