### ISSUE TITLE
painter tutorial uses the wrong image

### ISSUE THREAD

**Issue by sponster-au** [tobspr/shapez.io#908]
The tutorial popup for painter modules uses the wrong image: the tutorial for a painter shows an image of the painter-mirrored, and vice versa.

See the attached image - the upper tutorial pane shows a mirrored painter, not a regular painter. The lower selection pane shows the correct painter.

<img width="763" alt="Screen Shot 2020-10-18 at 8 51 24 am" src="https://user-images.githubusercontent.com/42725456/96390019-48762600-11fe-11eb-9dc1-a138255a5971.png">

**Comment by EmeraldBlock** [comment]
#901 fixes this
