### ISSUE TITLE
[Feature request] Preserve position when copying/cutting

### ISSUE THREAD

**Issue by santa-klaus** [tobspr/shapez.io#910]
When cutting or copying, the new copy's position is not kept the same relatively to the cursor, but is centered on the cursor instead. This makes it unnecessarily hard to move larger complexes by just a few tiles, and is very rarely what you want (since you end up in when of the corners when you mark the complex).

**Comment by Toastgeraet** [comment]
I would label it a Feature request, not a bug.

**Comment by santa-klaus** [comment]
I found it very unintuitive behaviour, so I felt like it's a bug, but you are probably right :)

**Comment by Toastgeraet** [comment]
Yeah it feels offputting to me as well.

**Comment by RangerDanger84** [comment]
I would think mouse top left corner - or maybe even a keyboard option to cycle through the corners and center to move the mouse anchoring (5 anchor point options total)

**Comment by santa-klaus** [comment]
I personally would prefer it just to preserve position relative to the cursor from the point of copying/cutting. That seems also less work to implement than the cycling option, which is also not that easy to understand. I don't think most players care enough about this to use a feature like that, so I argue a simple but more intuitive default behaviour is enough.

**Comment by tobspr** [comment]
I like this, tracking here: https://trello.com/c/PpydT02d/505-preserve-blueprint-relative-position-when-pasting
