### ISSUE TITLE
Speed is not increased at level 7

### ISSUE THREAD

**Issue by ronki2304** [tobspr/shapez.io#911]
Hello all,

I put a belt reader on a full line at level 6 and it indicates 12. Then I upgrade to level  7 but the belt reader still indicates 12. And I don't feel that the belt go faster

**Comment by EmeraldBlock** [comment]
This requires a little more context (what is the shape source? where are the shapes going? what is the setup?)

also, note that **readers are currently bugged and can slow down belts** (there's another issue open about that right now)

**Comment by ronki2304** [comment]
Hello I am not sure it is linked to the belt readers, please look at my setup : 
![shapez](https://user-images.githubusercontent.com/25466164/96771207-a7e05b80-13e1-11eb-8492-903302494ccb.png)

I am check betwin level 6 and level 7 the graphic ball don't look like go faster, and with that you have indeed the belt reader issue :)

**Comment by EmeraldBlock** [comment]
It should be the fault of the belt reader. The top line is definitely a full belt, and the belt reader is slowing it down (note how the belt reader input is fully saturated, but the output has small gaps).

**Comment by ronki2304** [comment]
Hum another weird thing, I don't know if everything is like to the belt reader

**Comment by tobspr** [comment]
It should be the belt reader, if not please reopen
