### ISSUE TITLE
[Bug] Belts are slower but corrected by two belt readers

### ISSUE THREAD

**Issue by Zalosath** [tobspr/shapez.io#914]
I made a short video explaining the problem: 
https://www.youtube.com/watch?v=3c6p-5-JSXg&feature=youtu.be

It's pretty similar to the belt reader but except it's a way to almost "fix" the bug.

**Comment by EmeraldBlock** [comment]
Duplicate of #781

**Comment by Hyperion-21** [comment]
Duplicate of #781 
Duplicate of #877 
Duplicate of #911 
Duplicate of #912 

Very common issue, check previous issues before posting another
