### ISSUE TITLE
[Feature Request] Configurable Pocket Dimension Machine

### ISSUE THREAD

**Issue by cssinate** [tobspr/shapez.io#920]
I think a really neat **very** late-game item would be a `Pocket Dimension Machine`. For example, [here's an image I found in the #efficient-designs channel in Discord](https://media.discordapp.net/attachments/707858977261879337/767032977103257631/unknown.png). It has 5 input lines, and 1 output line. It would be neat to have a method of turning that into a custom pocket machine that is 5 blocks wide and 1 tall that has 5 inputs and one output. So when you edit that machine, you get transported to an empty/blank grid that exists completely outside the normal map. You would mark your inputs on one side and outputs on the other, and build your machine in this empty space. When you save, you've got the same machine, but compressed into the tiniest form factor it can have.

If anyone has used Node Groups in Blender before, this is essentially the same idea.

Essentially, this is exactly like blueprints, but with massive, massive space-saving, hence the reason it's very late-game. You still have to create all the logic into the machine, but it doesn't have to take up an enormous footprint. Perhaps each machine costs 2x the number of blueprint shapes that it would cost if you were to paste that machine in using standard blueprints.

**Comment by tobspr** [comment]
Oof, well nice feature but super hard to do, so not planned currently, feel free to make a PR
