### ISSUE TITLE
[Feature Request] Save a blueprint of a copy for later use

### ISSUE THREAD

**Issue by ErneeGaming** [tobspr/shapez.io#923]
I'd love to be able to design my factories and then save their blueprint for later use.

I wouldn't mind to have to make a different shape to the blueprint one to pay for the save and load feature and then to pay for place with the basic one for example

**Comment by Hyperion-21** [comment]
Already planned.
https://trello.com/c/TOUfzhfI/297-blueprint-library-import-export-blueprints
