### ISSUE TITLE
Heavy performance drop when having a medium to large selection in map mode (fps)

### ISSUE THREAD

**Issue by Toastgeraet** [tobspr/shapez.io#927]
When i make a selection like the one in the picture below, the framerate drops from ~50 fps down to just 2 fps, while the selection is active. 

![grafik](https://user-images.githubusercontent.com/7590096/96973226-e6783200-1517-11eb-9d3e-1ae235ecfbe4.png)

I believe the problem might be in mass_selector.js (although i havent done any profiling to confirm this). There is a double loop, where a lot of roundedRectangles are being drawn.

![grafik](https://user-images.githubusercontent.com/7590096/96977976-217d6400-151e-11eb-932e-b085ab5a48cf.png)

Maybe using drawing regular rectangles, or using an [offScreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas) could alleviate the issue.

**Comment by tobspr** [comment]
https://trello.com/c/LYOwivyl/134-selecting-huge-areas-is-slow
