### ISSUE TITLE
Make the later freeplay levels significantly more complex

### ISSUE THREAD

**Issue by Hyperion-21** [tobspr/shapez.io#928]
As of now, it's coded so that the first layer can have a minimum of 2 missing shapes and the second can have a minimum of 1. However, in the extreme late-game (like level 100+) this becomes boringly easy. It'd be interesting if after a point the restrictions lighten up so that: 

If the layer and the layer above it don't overlap, then the lower layer must have at least 2 shapes, otherwise, if the layer above has a shape adjacent to the singular shape the layer below AND one of the adjacent higher-layer shapes has another shape above it (assuming 5th layer is full), the shape is possible.

**Comment by EmeraldBlock** [comment]
This is probably a `[FEATURE REQUEST]`

**Comment by tobspr** [comment]
I'm open for a PR. Maybe we'll allow overhangs starting from level 150 or so ?
