### ISSUE TITLE
[Feature Request] Quad Painter should treat gray input same as 0

### ISSUE THREAD

**Issue by femto113** [tobspr/shapez.io#930]
This seems like a small thing but would save me a large amount of wire logic.  Currently the Quad Painter treats all color inputs (including gray/uncolored) as a 1.  I'd like it to treat gray as a 0, such that the following configurations would have equivalent behavior

![Screen Shot 2020-10-24 at 11 23 08 AM](https://user-images.githubusercontent.com/184827/97089244-61f6e380-15eb-11eb-8e37-8534310c7179.png)
![Screen Shot 2020-10-24 at 11 22 49 AM](https://user-images.githubusercontent.com/184827/97089250-658a6a80-15eb-11eb-9e18-3f7849c1b351.png)

**Comment by EmeraldBlock** [comment]
That wouldn't make too much sense - all shapes and colors are treated as 1, and uncolored being different would be venturing too deep into the land of implicit type conversion. Additionally, uncolored is still a color that can be used as paint (though it is impossible to create normally).

And anyway, part of the fun is designing for this! Otherwise wires would be sort of boring.

**Comment by femto113** [comment]
I don't think this game is making much of a case for type purism.  Blank corners are not an explicit "blank shape" type, they are just a generic null, and not(not(null)) = 0.  Having not(not(uncolored)) = 1 doesn't feel very consistent, especially since there's no way to make uncolored paint (bleach?).  Quad painters also have not entirely consistent behavior with booleans--they treat all inputs off as a "shutdown" rather than "pass through without painting".   In combination this requires a whole bunch of logic to deal with (I think a minimum of around 10 gates).
<img width="811" alt="Screen Shot 2020-10-24 at 1 51 00 PM" src="https://user-images.githubusercontent.com/184827/97093449-ff104700-1600-11eb-8cfc-fb510c4c5aad.png">
If figuring all this out is a deliberate challenge then perhaps we could have a "Mark II" variant of the Quad Painter that unlocks later in the game when building compact MAMs becomes critical to progress.

**Comment by EmeraldBlock** [comment]
I totally agree about the "shutdown" thing - it's inconsistent and I've advocated for a change a few times. About blank corners, I see what you mean, though I still think returning null makes sense (if they were real, stacking shapes would cause empty corners to merge, and cutting would cause new empty corners to generate). For the double NOT, that's just the same thing as implicit type conversion (except conflicts, conflicts are weird).

Revisiting the uncolored thing, the way I think of it, shapes come "pre-colored" with uncolored. And if uncolored paint is ever made accessible, the current system would not need another change.

**Comment by Anykan** [comment]
Hi,

it is possible to build with "no color".it was hard for me to find a solution. The fun in this game is: "Find the answer !"
With the Transistors u can use the "no color" and switch it to "gray"
with the new gates you can makae many machines. The only problems are the 2 wires, 3 were better for more useable space.

![grafik](https://user-images.githubusercontent.com/10184152/97095128-fc8f0b00-165b-11eb-826d-04a2359a1794.png)

**Comment by EmeraldBlock** [comment]
I have to ask, why are you switching `null` to `uncolored` and not the other way around? Nothing different happens if you use a quad painter, because empty corners are completely ignored

**Comment by Anykan** [comment]
hi,

i need it to activate/deactivated the line in the quadpainter, with null it doesnt work.
i build an automated colorswitcher with the quadpainter, if u analyze a shape an there is a "null" the painter stucks.
becouse u need a color or an bool for the line.
So i change null to gray and use compere with an inverter. And now every time when gray or null color come, the line will be deactivated automaticly

![grafik](https://user-images.githubusercontent.com/10184152/97107520-56c5b580-16c8-11eb-981f-f067cfc207bc.png)

**Comment by Garr890354839** [comment]
You can also not use the quad painter.

**Comment by tobspr** [comment]
To get back to the initial suggestion, no I don'T like gray being 0 since thats super inconsistent
