### ISSUE TITLE
[Feature Request] High quality, whole base screenshots

### ISSUE THREAD

**Issue by deitrix** [tobspr/shapez.io#934]
It would be nice to be able to tweak the quality of the whole base screenshots. Currently, I find they're a little too pixelated.

**Comment by tobspr** [comment]
Yeah I have planned to fix this for a long time, on my todo list

**Comment by tobspr** [comment]
Tracking here: https://trello.com/c/hzIrZLF3/261-exporting-screenshots-or-savegames-does-not-work-sometimes-on-electron
