### ISSUE TITLE
[Minor Bug/Oversight?] Getting charged for blueprints that didn't do anything.

### ISSUE THREAD

**Issue by boiimakillu** [tobspr/shapez.io#935]
Not really a bug, more an unfavorable behavior. When pasting a blueprint, if you don't move your cursor at all, but place the  same blueprint multiple times, than you get charged each time it is "placed", despite nothing actually happening. This might be hard to fix, but it seems like a pretty good QOL change.

**Comment by tobspr** [comment]
Ah well. I think if no real building got placed, it should lower the cost

Tracking here: https://trello.com/c/rHYkhx4Z/294-pasting-blueprints-sometimes-breaks-buildings-pastes-incorrectly
