### ISSUE TITLE
[Feature Request] Select icon for Markers

### ISSUE THREAD

**Issue by cssinate** [tobspr/shapez.io#938]
Right now, in the list of Markers, the Hub has an arrow that points towards the Hub, and all other markers have a typical map pin. I think it would be beneficial for the user to be able to select a different icon for each marker. Consider these two use cases for markers:

- I have a factory that takes in an uncolored square and an uncolored circle, and creates `CuRuCuRu`.
- I find a `CuRuCuRu` node in the wild, that I don't need right now, but will probably want to use later.

The marker for each of these would probably be `CuRuCuRu`. But I have no way to distinguish a factory from a resource node. If, when I created the marker, I were able to select an icon for the marker, then I wouldn't be confused.

**Comment by tobspr** [comment]
Hm, sounds like a very special use case. Considering for the marker rework
