### ISSUE TITLE
[Bug/Oversight] Colorblind Tooltips do not show up with Constant Signal object

### ISSUE THREAD

**Issue by turosian** [tobspr/shapez.io#939]
When hovering over a color in the selection window, or over the Constant Signal object when a color is selected, I believe the color name should show up in the top/middle of the screen, similarly to how it does when you point at a color item.

**Comment by tobspr** [comment]
Tracking here: https://trello.com/c/878qDEXY/213-fix-color-blind-mode-on-belts
