### ISSUE TITLE
[Performance suggestion] Replace the belts items array of longer belts with implicit treap

### ISSUE THREAD

**Issue by spaanse** [tobspr/shapez.io#942]
Looking at `belt_path.js` the current approach to belts is to maintain an array `items` to store the item at each index of the belt. This means that each time step each item must be moved to the next position in the array, which is slow for long belts. In [complexity](https://en.wikipedia.org/wiki/Computational_complexity) terms the current data-structure shifts in O(n) time. I propose a data-structure that can do this faster in O(log n) which will be beneficial for longer belts but might not be for shorter belts due to a larger constant factor. A hybrid approach might be needed.

The data-structure I want to propose is the implicit treap. This is a combination of a [binary search tree](https://en.wikipedia.org/wiki/Binary_search_tree) over the elements, with a [heap](https://en.wikipedia.org/wiki/Heap_(data_structure)) over random values to try to balance the binary search tree. The implicit treap doesn't use the values of elements as keys, but instead uses the position in the tree as index. I suggest reading [this post](https://cp-algorithms.com/data_structures/treap.html) about the treap/implicit treap as it's implementation is more relevant than the one [Wikipedia](https://en.wikipedia.org/wiki/Treap) gives. Intuitively you can think of an implicit treap as a fancy array.

More concretely for this application:
A tree node contains an item, subtree size, references to the root nodes of the left and right subtree and a random value.
With this we have multiple functions:
 - `L,R split(T,idx)` that splits a tree T into two trees L and R, such that L has all nodes with index <idx and R has all nodes with index ≥idx. The new trees will once again be 0-indexed because the indices are implicit. Think of it as cutting an array into two arrays. This operation takes O(log n).
 - `T concat(L,R)` that takes two trees L and R and concatenates the arrays they represents into a tree T. Again O(log n)
- `insert(T,idx,item)` inserts the item at position idx, shifting all items at positions idx...end one to the right. done in O(log n)
- `remove(T,idx)` removes the item at position idx, shifting all items at positions idx+1...end one to the left. done in O(log n)
- `find(T, idx)` finds the element at position idx. Done in O(log n) instead of O(1) of array.
Shifting can be done by removing an item at the end (or the "empty" item closest to the end) and inserting a new item at the beginning.

pros:
 - insertion, deletion, concatenation and split take O(log n) instead of O(n)

cons:
 - probably slower for shorter arrays due to extra overhead, solved with a hybrid approach where you only start using an implicit treap when the length of a belt is longer than some minimum.
 - finding an element by index slows down from O(1) to O(log n), but that is a much smaller difference than O(n) to O(log n)

Alternatively other self-balancing binary search trees can be made implicit, but that is more difficult than the treap because the balancing operations are more involved.  
Furthermore if you maintain parent references in the implicit treap then you could also use this for the belts themselves. Following the parent pointers you can find out the index of any node in the tree, so that allows you to find the index in the belt path of any belt without traversing the whole path. However it would be more beneficial to just store the index in the path at each belt itself because that only needs updating when belts are joined and not every time step.

**Comment by tobspr** [comment]
While this sounds interesting, this would make the current belt path logic explode in terms of complexity. I'd be happy to see a PR tackling this problem though
