### ISSUE TITLE
[Bug] Standalone Steam version occasionally freezes while idle

### ISSUE THREAD

**Issue by jfxg** [tobspr/shapez.io#945]
3 or 4 times in the past week I've come back to my computer to find Shapez an empty blank screen. See attached screenshot. There is no apparent error message, Steam still indicates the game is running, and I see nearly 0% CPU usage on the process. Since the UI is blank there is no option to exit, but clicking the window 'x' does close the app immediately. When I restart the game I usually see my save game with a timestamp of some number of hours ago, so it is does not appear to be running or at least auto-saving when it enters this state.

Happy to grab log files or dumps if those might be available somewhere, I didn't see any log files in the Steam install directory.

Basic info about my environment:
* In game version reads `1.2.0 @ Production @ 366a2a9`
* Windows 10 Pro v1909 build 18363.1139
* AMD Ryzen Threadripper 2950X
* 64gb RAM
* Nvidia GeForce RTX 2070

![Screenshot 2020-10-27 212543](https://user-images.githubusercontent.com/5017824/97391994-cfca3600-189d-11eb-844d-28c2967ee331.png)

![Screenshot 2020-10-27 214849](https://user-images.githubusercontent.com/5017824/97392117-35b6bd80-189e-11eb-9c60-c75781c3b330.png)

**Comment by derekShaheen** [comment]
This has happened to me as well. Windows 10, Steam, i9-9900k

**Comment by fmonera** [comment]
Same here. Linux Kubuntu 20.10.

**Comment by tobspr** [comment]
Unfortunately I have no idea what could cause this

**Comment by KeithLRobertson** [comment]
August 2021 and this continues to occur.

**Comment by straizer** [comment]
June 2022, still occurs.

**Comment by RedactedPermaBan** [comment]
I can confirm I'm also seeing this happen but it only started after I reached level 30 and built larger machines to produce the needed upgrade shapes

**Comment by straizer** [comment]
Okay, as far as I know, if you zoom out to map view, it freezes after around 5 minutes, but if you are zoomed in, the game will be in ILDE state for hours without crash. Note that it works only when you have set 60Hz or lower in settings. When 120Hz is set, game will freeze even if you are zoomed in.

**Comment by KeithLRobertson** [comment]
That sounds like a memory leak.

**Comment by GoldenRatioMan** [comment]
This is still happening, even before Level 30. I just got to the random level after unlocking everything and it has been happening every few minutes, Steam or Epic Games copy, doesn't matter. I've not got much in the way of machines and it still does it. If I walk away from the computer for a few minutes and come back it is frozen and usually the only way to proceed is to go to settings and back out again. At the same time, production does not always seem to continue when it is frozen, only sometimes.  Any thoughts @tobspr ?

The issue with the grey screen also seems to occur once in a while forcing me to close and reopen the game and of course lost hours of potential progress. Could there be a memory leak of some sort when it autosaves?

**Comment by TyIsI** [comment]
@tobspr I have the issue as well and I know that my machine does not like hardware acceleration. And it has the same set of symptoms.

Before I go set up a build environment, I would love to know if there is a setting to disable hardware acceleration?

**Comment by TyIsI** [comment]
Alright. I just caught using just shy of 4GB of memory. Definitely a memory leak.

For context, my current map has 107K+ belts with 37K buildings. No mods.

Things I have noticed:
- It also occurs when the window is visible but doesn't have focus.
- It mostly seems to occur while other electron apps are open. (Not exclusively.)
- Saving uses sometimes around 600MB of memory. (Base for what I guess is the map thread is around 600-700MB, with around 1GB total, spiking up to around 1.8GB.

As I was looking up my map stats, it tried to save and while I was "escaped", this happened to the map. It's still functional. (Don't judge me.)

![image](https://github.com/tobspr-games/shapez.io/assets/3118952/df54be75-835b-4630-bf1b-ed5ce498c650)
![image](https://github.com/tobspr-games/shapez.io/assets/3118952/cf568845-93e8-487b-b447-f1c98008a817)

I would want to hypothesize that it's Chrome/Electron pushing back priority combined with (auto-)saving being an expensive calculation, is creating memory leaks. Perhaps with hardware acceleration throwing a spanner in the works.

Anyway. My 2 cents for now. 

I'm going to try decreasing the auto-save interval and see if that affects anything.
