### ISSUE TITLE
Wires tutorial pop-up freezes electron engine forcing manual process kill

### ISSUE THREAD

**Issue by tneo** [tobspr/shapez.io#947]
I just reached the level that unlocks the wires update. Once I reached that a nice pop-up is shown telling so and the option to see an explanatory video. Clicking that link freezes electron and I have to force kill all processes related to shapez.io in order to get back to steam.

In case it matters:
Operating System: openSUSE Tumbleweed 20201014
KDE Plasma Version: 5.20.0
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.8.14-1-default

**Comment by tobspr** [comment]
Do you have any antivirus? Besides of that, it seems to be a system related issue and nothing I can fix :/
