### ISSUE TITLE
[Bug] Corrupted savegame: bad-content / decompression-failed

### ISSUE THREAD

**Issue by santa-klaus** [tobspr/shapez.io#948]
I can't open my savegame any longer. Instead, I get the following error, stating "bad-content / decompression-failed".

![grafik](https://user-images.githubusercontent.com/10899463/97550428-f5f0f280-19d1-11eb-807c-52bd91fb9c82.png)

I might have mixed the standalone version from itch and the steam version.

Is there any way to fix this?

**Comment by EmeraldBlock** [comment]
The itch and steam version are basically the same, so I doubt that's the issue. A common reason for a corrupt savegame is force-quitting or crashing while the game is saving - did that happen to you?

That message itself is pretty vague, maybe providing the savegame file itself could help
