### ISSUE TITLE
[Bug] Shape gets corrupted after cutting

### ISSUE THREAD

**Issue by OlofMoriya** [tobspr/shapez.io#949]
![image](https://user-images.githubusercontent.com/13721900/97623760-6fb2cb80-1a26-11eb-822a-f8c570bd4391.png)

Cutting this piece should not change the inner red shape as it's constructed internally to the blue/grey shape. This is not expected behaviour.

**Comment by EmeraldBlock** [comment]
Empty layers are strictly not allowed. This is 100% intentional behavior.
