### ISSUE TITLE
[Feature Request] Adjustable Storage

### ISSUE THREAD

**Issue by Anykan** [tobspr/shapez.io#956]
At the moment the storagecontainer will send a "1" when its full (at 5000 pcs). it will be great if i can adjust the level for sending the "1".
I have automated all shapez. So my machine can build everything over 4 layers automatecly, but i want buffer the shapez in a store for sending faster then i build. But why waiting  for 5k if 500 enough :-)

**Comment by arnthorg** [comment]
I think it could also be a storage that outputs its storage value and implement a bigger than, smaller than or equal gate

**Comment by tobspr** [comment]
There's a reason thats not implemented, and there are ways to work around it :)
