### ISSUE TITLE
[Bug] Pinned shapes are removed when you click on the info

### ISSUE THREAD

**Issue by gaboroszkar** [tobspr/shapez.io#957]
After pinning a shape from the UPGRADES window for example, the shape appears on the left side of the screen.
When the **i** button is clicked (for the info of the shape), it will remove the pinned shape from the left side rather than show the info.

![image](https://user-images.githubusercontent.com/7050000/97799672-bfb0ae80-1c2f-11eb-97d5-de117d9ead7c.png)

Version: 1.2.1 @ prod @ 4b08898

**Comment by artemisSystem** [comment]
fixed in #839

**Comment by gaboroszkar** [comment]
Duplicates https://github.com/tobspr/shapez.io/issues/815.
