### ISSUE TITLE
Allow paint symbol in map tags

### ISSUE THREAD

**Issue by adalovebass** [tobspr/shapez.io#959]
This could be part of short key syntax, such as -w-w-w-w or Pw or... single color character such as 'w'? This part may be tricky without breaking the 8-character rule. Maybe if there is  P (for "Paint" symbol) in any of the shape indicators it's entirely treated as a paint symbol?

Otherwise maybe just a color picker along the bottom of the map tagging dialogue?

**Comment by EmeraldBlock** [comment]
(Maybe label as `[Feature Request]`)
Could be implemented by starting with a symbol like `^` maybe? `^white`, `^r`, etc. could work

**Comment by adalovebass** [comment]
Sorry, if you're talking to me, I can't seem to set a label... 🤷‍♀️

**Comment by EmeraldBlock** [comment]
Oh, label as in prepend text to front of issue name (probably, should have said that, oops)

**Comment by darkwater4213** [comment]
I fully support this idea! Possibly could be in the form ^#<hexcode>, for example: `^#fffff` would produce white. This would obey the 8character rule.

**Comment by EmeraldBlock** [comment]
There's no reason to have 8 characters (it would be wise to construct a separate detection system) and it just makes things harder to type, given that there are only 8 colors.

**Comment by darkwater4213** [comment]
Well, if you eventually add more colors, then this would help with that. I suppose you could add an additional detection system that looks for these:
^red or ^Red
^yellow etc.
But using the Hex would mean that the game only has to count the number of characters in the marker to see if it isn't a shape/color code. This might make things easier...?

**Comment by EmeraldBlock** [comment]
I wouldn't say so - the way markers check if a text string is a shape code is by using a specialized function (and anyway, shape codes can vary in length).

What I was thinking was allowing for both `^r` and `^red`, etc. without regard to capitalization

**Comment by darkwater4213** [comment]
Actually, that makes a lot more sense. I vote to implement this (If that's a thing?)

**Comment by tobspr** [comment]
Tracking in https://trello.com/c/v3wKZCR0/305-allow-using-colors-in-markers-and-show-them-in-the-statistics already
