### ISSUE TITLE
[Feature Request] Level 100 und nu?

### ISSUE THREAD

**Issue by Anykan** [tobspr/shapez.io#960]
Gibt es Überlegungen, wie es weiter gehen kann?
Das Game ist echt gut gelungen was die Logiken angeht, aber das ist Fluch und Segen.
Durch die Wiredebene und die ganzen Logiken (die ich sehr gut finde) hat das Game dann aber irgendwo ein hang langweilig zu werden. Ab ca lvl 51 war meine Maschine fertig, die jetzt alle Shapez bauen kann (auch die mit "null") und das automatisiert auf 4 Ebenen. Eine weiter Ebene würde nur zu Copüy & Paste führen. Das einizige was ich jetzt moch machen muss ist auf ein Knopf Drücken wenn genug im Lager von der nötigen Form ist, die dann über mehrere Forderbänder ins Lager schicken damit ich die m/s erreiche. Dies geht auch automatisch wenn man wartet bis die 5000 im Lager voll wären.

**Comment by Anykan** [comment]
Nachtrag:
Ich habe 4.200 Spielminuten, 59.886 Gebäude und 85.073  Fliessbänder und das Spiel läuft schön flüssig, Super Performance find ich.

**Comment by tobspr** [comment]
Erstmal glückwunsch, und naja, irgendwann hat man ein spiel halt auch durchgespielt :)
