### ISSUE TITLE
[Bug] Belt Reader and Marker text disappears 

### ISSUE THREAD

**Issue by Hevees** [tobspr/shapez.io#961]
![3](https://user-images.githubusercontent.com/61807910/97932969-b0d21500-1d71-11eb-978b-122cb74f3370.PNG)

Sometimes, after entering/exiting wires layer, the text on Belt Readers and Markers dissapears. Restarting the game fixes the issue temporarily.

**Comment by tobspr** [comment]
Thats a driver issue, nothing I can really do about that ...
