### ISSUE TITLE
[Feature Request] "Bowtie" merger and splitter

### ISSUE THREAD

**Issue by cssinate** [tobspr/shapez.io#963]
Right now, mergers take inputs from two perpendicular belts and output them in a direction that's parallel with one of those two belts. I'm proposing being able to take two parallel inputs, and outputting in a perpendicular line. For example, a merger could take input from the left and right and output towards the top. Or a splitter could take input from the right and output to top and bottom.

![image](https://user-images.githubusercontent.com/25226452/98161819-60140680-1eae-11eb-94a2-4a70e4a12505.png)

**Comment by 1000i100** [comment]
I would love to have a multi-purpose tool with this gfx (or without the arrow) : 
depending of neigtbord belts directions it will merge or split them. Exemples, with the same on square tool (i named it [T]) : 
```
case 1 : from left split to right and bottom
-->[T]-->
    |
    V

case 2 : from left  and bottom merge to right
-->[T]-->
    ^
    |

case 3 : from bottom split to left and right
<--[T]-->
    ^
    |

case 4 : from left and right merge to bottom
-->[T]<--
    |
    V

The only 2 cases where nothing happen are : 
case Y : input from everywhere, no output
-->[T]<--
    ^
    |
case Z : no input, only output
<--[T]-->
    |
    V
```
it could replace the boring selection between 4 distinct oriented tools.
It could also replace and improve the original 2 square repartitor : 
```
case 1 :  from left to right mixing the 2 input to the 2 output
-->[T]-->
-->[┴]-->

case 2 :  from left input to left and right outputs
-->[T]-->
<--[┴]-->

case X :  some mixing
-->[T]-->
<--[┴]<--

-->[T]<--
<--[┴]-->

-->[T]<--
   [├]-->
<--[┴]<--




```

And last, if an alternate still make sens, it should be a 4 direction mixer : 
```
case 1 : merge left and right input and split them to top and bottom output
    ^
    |
-->[┼]<--
    |
    V

case 2 : you have the idea...
    ^
    |
-->[┼]-->
    |
    V

    |
    V
-->[┼]-->
    ^
    |

    |
    V
-->[┼]-->
-->[┼]<--
<--[┼]-->
<--[┼]<--
    ^
    |

case 3 : mixing betwin the 3 part [T] alternate and the 4 part [┼] alternate : 
    |
    V
-->[┼]-->
-->[┼]<--
<--[┼]-->
   [├]-->
<--[┼]<--
   [┴]<--
Here, input T1,L1,L2,R2,R5 and R6 are merged, mixed and equally split/distributed to R1,L3,R3,R4 and L5.
PS: I've not put anything in L6 just to rember it can happen.
```

how are you about this ?

**Comment by darkwater4213** [comment]
Hmm... This is similar to a slightly different idea I came up with that has to do with late freeplay and some other things. Basically, you can make any size distributor you want, more or less.

**Comment by tobspr** [comment]
Looks more like a thing for a mod, not planning to put this into the base game
