### ISSUE TITLE
I'm confused

### ISSUE THREAD

**Issue by darkwater4213** [tobspr/shapez.io#966]
Hi! I'm a fairly new coder, and don't know a whole lot. However, I do know enough that I can make a few changes to the code to fix some inconsistencies, etc. I have already downloaded the .zip  (I'm on Windows 10) file, and extracted it. I've gone through all the contents, but can't figure out how to start the game. The reason I want to do this is to make sure that the fixes work, and don't cause any problems. I'm mostly working on GitHub Desktop, and will publish my changes once they are done and working bug-free. Can anyone possibly tell me how to work it? (As I mentioned earlier, I'm a bit of a noob)

**Comment by EmeraldBlock** [comment]
A few tips:

* Read the README! Or, if the build instructions there are a little too unspecific, read this: https://github.com/Hyperion-21/shapez.io/blob/clarify-readme/README.md#building

* Don't use such a vague issue title! "I'm confused" could mean loads of things.

* **Don't open an issue for this.** Seriously, the purpose of issues is to note and resolve problems with the game's code. Ask on the discord server about this kind of stuff (https://discord.com/invite/HN7EVzV)

**Comment by darkwater4213** [comment]
Sorry... I couldn't think of a better title. I did ask on Discord, but no one answered.

**Comment by darkwater4213** [comment]
And yes, the build instructions are a bit vague. Maybe consider updating?

**Comment by darkwater4213** [comment]
Oh, you did. Thanks!

**Comment by darkwater4213** [comment]
:( Chrome is blocking FFmpeg for some reason. Why?

**Comment by EmeraldBlock** [comment]
> Sorry... I couldn't think of a better title. I did ask on Discord, but no one answered.

As far as I can tell, people did respond to your questions, though I may have missed some.

> And yes, the build instructions are a bit vague. Maybe consider updating?

There is a PR associated with those better instructions that hasn't been merged yet (#925)

> :( Chrome is blocking FFmpeg for some reason. Why?

Could you be more specific?

**Comment by darkwater4213** [comment]
When I tried to download it as a .7z file, Chrome said "FFmpeg is dangerous -- Chrome blocked this dowload" and there was a button that said discard.

**Comment by darkwater4213** [comment]
Chrome also tried to block the site

**Comment by darkwater4213** [comment]
However, I'm trying GitPod

**Comment by EmeraldBlock** [comment]
Please don't treat comments like an instant messaging system. Group them together or edit the last message if it relates to it. Plus, every message sent here is displayed on the `#new-commits` channel on the discord (seen by people with commit notifications enabled).

For the ffmpeg thing, click on whatever "more" button, and keep the download from that menu.

**Comment by darkwater4213** [comment]
It wouldn't let me, it just said "Learn More", which takes you here: https://support.google.com/chrome/answer/6261569?visit_id=637402019209857522-387460751&p=ib_download_blocked&hl=en&rd=1

**Comment by EmeraldBlock** [comment]
send a screenshot of the download thing, maybe? or try another browser if you can do that
