### ISSUE TITLE
[Feature Request] Cut/Delete Shapes warning

### ISSUE THREAD

**Issue by darkwater4213** [tobspr/shapez.io#967]
It would be nice if a warning popped up saying that you are about to cut or delete a patch of buildings that has more than, say, 250 on it or stored there. And then you could either cancel, confirm, or, if you were cutting, click a button that allows you to paste WITH the shapes in tow, but it would cost bouquet or rocket shapes in addition to the standard blueprint shapes?

**Comment by EmeraldBlock** [comment]
Uh, isn't there already a cut/delete warning for 100+ buildings?

and what do you mean by with the shapes in tow?

**Comment by darkwater4213** [comment]
For instance, if you had two storage buildings full (5k each, so 10k total) of Logo shapes, and try to cut them, the game will recognize that you are trying to cut or delete more than 100 (or whatever the threshold is) shapes, and ask you if you want to stop, cut with shapes (which costs, say, bouquet shapes  CpRpCp--:SwSwSwSw in addition to blueprint shapes), or cut without the shapes (which ends up with the shapes gone). This also brings up another idea... (I'll edit the link into here later.)

**Comment by tobspr** [comment]
The question is, why do you have so many logo shapes stored in storages in the first place? 

I am considering the warning though, not planning to include the shapes when copying though

**Comment by darkwater4213** [comment]
Actually, it was just a possible scenario that you wouldn't want to lose shapes in. I actually have something along the lines of 150k (arranged so that it is hard to remove) Logo shapes stored up, ready to be dumped into the base,  because I figured out a ridiculously efficient factory for them and it has been running since like level 13 XD. I am currently working (slowly) on a baseline (by that, I mean very buggy) version of this. :)
