### ISSUE TITLE
[Feature Request] Fast-forward with rockets?

### ISSUE THREAD

**Issue by darkwater4213** [tobspr/shapez.io#973]
Since I have spent quite a lot of time waiting for levels to be completed, I was thinking about having a fast-forward button (possibly the rocket shape itself?) that made the game go a set amount faster for a set amount of time, but you have to spend a certain amount of Rocket shapes (CbCuCbCu:Sr------:--CrSrCr:CwCwCwCw) per second or minute or levels or whatever in order to do so. My idea is 5 rockets per second or possibly two seconds. This would really help a lot of people playing the game, because most freeplay strategies have to do with storing a bunch of shapes just outside the Hub, and the dumping them all in using filters, in order to hit the throughput goal. So, this would help them get those storages filled faster, and the benefit in the earlier levels, which are amount goals, is quite obvious.

**Comment by EmeraldBlock** [comment]
I don't really like this idea - it strengthens the idea that this game is an idle game, which is not very interesting. And anyway, even if implemented properly, a rocket stream would sort of just become the norm, and just another speed upgrade. I'm also not too sure about the consequences on low tickrate, since things may get a little broken in that case.

**Comment by darkwater4213** [comment]
Well, the idea is that it's very expensive, and maybe you have to have over, say, 1 or 2M rockets, and once you drop below that threshold, FF stops? It would be good for clearing levels where you are mostly just waiting.

**Comment by EmeraldBlock** [comment]
Well, as long as you produce as much as the thing consumes, it just goes on forever. And anyway, I think tackling the waiting problem itself is more important

**Comment by darkwater4213** [comment]
You bring up a good point. Maybe (I don't know how to implement this) you HAVE to spend however many rockets you are producing per second + two rockets? Either that or, say, five rockets per second, whichever is bigger.

**Comment by tobspr** [comment]
I don't like the idea as well
