### ISSUE TITLE
belt speeds max out at 15 for no reason 

### ISSUE THREAD

**Issue by Mattisonfire511** [tobspr/shapez.io#975]
shape speeds max out at through tunnels or something, they slow down for no reason and it really bothers me. im on tier 15  which means averything is about 17.5(or should be)

**Comment by EmeraldBlock** [comment]
protip: describe your issue in your initial comment, not your title.

**Comment by Mattisonfire511** [comment]
lol, yes, but it seems fine, the problem is maybe tunnels i think, belt readers dont seen to slow it down at all, oh and also something funny, once you get belts to tier 20 it looks like things are moving backwards

**Comment by Mattisonfire511** [comment]
i would help more but i have no idea how to code.

**Comment by EmeraldBlock** [comment]
Some research from others on the discord suggests that this happens to all non-manipulation buildings, so it's likely that. Seriously though, you should probably shorten the title and edit your original comment

**Comment by Mattisonfire511** [comment]
ok lol, and thanks for responding so quick!

**Comment by EmeraldBlock** [comment]
Check the README page (go to code tab, then scroll down)

**Comment by Mattisonfire511** [comment]
thanks!
