### ISSUE TITLE
[Bug] Extractors produce less flow than would be expected

### ISSUE THREAD

**Issue by jLouzado** [tobspr/shapez.io#976]
## Version

1.2.1 @ Production @ 4b08898

## Steps

- connect extractors in a 3 + 2 configuration.
  - each extractor is 1.2 items per minute, 
  - so that's `3.6` + `2.4` items per minute
- combine the two in a balancer onto a single belt

## Observation

- as in the screenshot, it's clearly not filling up the belt; looks to be only 4 items a minute

![image](https://user-images.githubusercontent.com/2016685/98459242-1170b000-21bf-11eb-9db5-4158ea5b71e6.png)

## Workaround

- directly connect 6 extractors in a row

![image](https://user-images.githubusercontent.com/2016685/98459280-7af0be80-21bf-11eb-8dfb-c83afac89e32.png)

## Impact

factories created in the earlier levels are impacted because it's harder to calculate flows

**Comment by EmeraldBlock** [comment]
I appreciate the very well-formatted bug report, but you do realize that belts can't feed into extractors, right?

**Comment by jLouzado** [comment]
@EmeraldBlock I did not realize that, no. :see_no_evil: 

I guess I assumed that chained extractors have a sort of input & output omg. Thank you for the clarification, I couldn't figure out what was happening. :sweat_smile:

**Comment by jLouzado** [comment]
Is there any way that this could be made clearer in the UX? Maybe a :x: indicator like when you try to place a balancer on a belt in the wrong direction.

![image](https://user-images.githubusercontent.com/2016685/98472429-119d9980-2219-11eb-8a39-bf4dba24d89f.png)

**Comment by EmeraldBlock** [comment]
The key thing to note is that these symbols only appear on inputs and outputs - since extractors don't have inputs there, they don't show the symbol at all.
