### ISSUE TITLE
how i delete

### ISSUE THREAD

**Issue by 19srzhu** [tobspr/shapez.io#978]
HHI

**Comment by 19srzhu** [comment]
wanna chat

**Comment by EmeraldBlock** [comment]
This is GitHub - if you want to chat, go to the official discord server (https://discord.com/invite/HN7EVzV).

Please close this issue, this has nothing to do with the game whatsoever!

**Comment by 19srzhu** [comment]
okokok

**Comment by EmeraldBlock** [comment]
could you, uh, close the issue

**Comment by Mattisonfire511** [comment]
lol

**Comment by 19srzhu** [comment]
how

**Comment by 19srzhu** [comment]
oh

**Comment by EmeraldBlock** [comment]
it's uh, still not closed

**Comment by 19srzhu** [comment]
idk how

**Comment by EmeraldBlock** [comment]
it's on the right bar, where "notifications" and "participants" are

please search how to do it next time: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/deleting-an-issue

**Comment by Mattisonfire511** [comment]
lol u dont know how

**Comment by 19srzhu** [comment]
do u
