### ISSUE TITLE
[Feature Request] Challenge / puzzle mode (or mod) with Zachatronics like leaderboard (bar chart & score)

### ISSUE THREAD

**Issue by 1000i100** [tobspr/shapez.io#981]
# Idea : Optimisation challenge
It's like level goals but with an empty map and depending of the challange : 
- hub, colors and shapes ressources pre-placed on the map (like in normal mode)
- user placable one square hub (like #685), and sandbox color and shapes generator
- quota by element (for exemple : 2 stackers only, 0 splitter and infinite belt)

## The challange have 3 step : 
1. **build the factory**
    Like we allready do in shapez.io
2. **run it** (to be able to collect metrics on a unmutable factory)
    reset/clean the shapes and run in a reproductible / determinist way with edition disabled.
3. **leaderboard / review** / compare scores / metrics
    This time/try/run scores/metrics/acheivements compared to : 
    - other time/try/run personnal scores
    - steam friends best scores (or non steam if also possible)
    - overall community best scores (with bar chart to see where we are compared to other and not only to the top 10)

### Metrics :
- occuped space (tiles occuped by something)
- **bounded space** (the smallest rectangle including the entire factory)
- cost (number of factory part used (excluding conveyor/belt)
- **time** (ticks from start/run the challenge to complete goal)
- rush (tick number from the first extraction to the first correct shape in the hub)
- max speed/bandwith (max shape production by second)
- **score** : time/space (or something like that)

## Leaderboard examples : 
From Zachatronics games, with bar chart & score.

**With context :**
https://ilovevg.it/2018/11/nerd-and-dev-zachtronics/#gallery-1
https://forums.somethingawful.com/showthread.php?threadid=3837813&pagenumber=4#post477638069
https://www.reddit.com/r/infinifactory/comments/8xjjob/any_cheaper_solution_i_will_be_very_surprised/

**Directly as embed images :**
![leaderboard exemple](https://i.imgur.com/sXOVRXS.png)
![leaderboard mobile layout](https://i.redd.it/zye0nupjpix11.png)

PS : there could be official challange and community created challange, and a rating system : 
- [manual] subjective difficulty (to reach goal)
- [manual] fun
- [auto] popularity (number of score submited/stored from distinct users)
- [auto] recent popularity (today or this week score submission number)
- [auto] published date
- [auto] goal difficulty (how many run before reaching the goal for the first time (if challange edit mode is in pause) with chart bar with min/avg/**median**/max and default sorted by median)
- [auto] score optimisation difficulty (how many run for a user since the first successfull goal reach to the last score improvement)
- [auto] metric specific optimisation difficulty (same but to the last improvement on a specific metric)

Do you like the idea ? for a next major update perhaps ?

**I see some distinct parts technically :**
- Quota (probably the easyest)
- Game modes selection (Demo, Classic, Sandbox, Challange), mainly UI/UX/design
- Challenge distinct build/edit mode
- Challenge distinct unmutable run mode
- Leaderboard UI (bar chart, personal/friend/global tab...)
- Leaderboard cloud storage security/anti-cheat (for this, re-run server-side the unmutable detrminist step 2 could work, and if it's too ressource intensive, pick a pool of random user and make them silently run the check re-run to validate score submission could be a way)
- Community content workshop (ideally not steam limited, perhaps with https://mod.io/ with rating and sorting system + leaderboard view before try)

Here is what i wish for this game to reach my dream (with #963, #972 and probably some advanced wire stuff and what i will imagine next...).

**Comment by tobspr** [comment]
I have something like this planned: https://trello.com/c/oxO5JIuU/39-puzzle-mode

**Comment by 1000i100** [comment]
Big up to "resource constrained challenges" named in #1142 ! It could be another leaderboard metric (how few resources you've used to reach the goal) !
