### ISSUE TITLE
[Feature Request] PvP 1v1, FFA, Team Fight, PvE and Coop PvE mode (or mod)

### ISSUE THREAD

**Issue by 1000i100** [tobspr/shapez.io#982]
In this mode, nothing is free ( to make fast progress limited by material )

Players start in the same map with some ressources/quota (see #981 for quota) and there hub.

With the same mechanism than actual upgrade or level,
Some shapes (when delivered to the hub) definitively extend : 
- map boundaries (you can see ressources positions)
- visible boundaries (you can see other player buldings/activity up to theses boundaries)
- reachable/buildable boundaries (you can build there)
- reserved boundaries (nobody else can build there, but what's allready there stay in place)
- converting boundaries (ownership of every building in this area is now yours and it overcome reserved restriction)

All these boundaries can overlaps between players except converting boundaries, for this last one, it's like a Voronoï diagram with a max radius.

You can also place some nexus/pylon/converting boundaries extender/influence tower.
When you place it, with his position as seed, it generate random patterns as leveled fuel requirement.
No fuel to burn in the tower (send it to the pylon, not to the hub), no power (influence to extend converting boundaries).
The tower start level 0 and shut back to level 0 if laking of fuel.
You can click on a tower to open a panel with level data :
- base influence power/radius at this tower level + quantity bonus.
- (in small) minimal "previous level fuel pattern"/s to reach in case the current level requierment are not maintained anymore and the tower level down.
- square-rooted quantity bonus multiplicator applied related to "previous level fuel pattern"/s.
- minimal "this level fuel pattern"/s to keep the tower on current level.
- square-rooted quantity bonus multiplicator applied related to extra "this level fuel pattern"/s.
- minimal "next level fuel pattern"/s to reach the next level.
- square-rooted quantity bonus multiplicator applied related to "next level fuel pattern"/s.

When you meet the next level requirement, the tower level up.
The old current level fuel pattern become the previous level fuel pattern.
The old next level fuel pattern become the new current level fuel pattern.
And a new (and more complex) next level fuel pattern is revealated with a flow (volume/s) requirement.

Optionnaly, a very advanced factory with advanced wire mechanism could be able to auto transmit the new fuel requirement to auto-build it... perhaps.

PvE could be : 
- like it is today
- versus AI (and writing good AI could be a specific game with AI fight challenge)
- versus time
- versus natural desaster (moving goo/rust make you move to avoid it and trying to slow it down and make as many score as you can before it reach your hub (like in [Outpost 2](https://www.gog.com/game/outpost_2_divided_destiny))
- versus cheating AI with scripted behavior and not the same constraints than player have.

**Comment by tobspr** [comment]
This would be an entirely new game
