### ISSUE TITLE
demo shape bug

### ISSUE THREAD

**Issue by dhulsman889** [tobspr/shapez.io#983]
i'm currently playing the demo and if I want to upgrade my belts to lvl 9, I need to make the shape shown on the image, and with the tools in the demo I can't do that. Could you please fix that? Thank you!
![shape](https://user-images.githubusercontent.com/74249446/98679231-fb4e2580-235f-11eb-9ce0-e7e82335478d.JPG)

**Comment by TcePrepK** [comment]
Do you have cutter and stacker ?
Then you can make it there isn't any bug

**Comment by dhulsman889** [comment]
yes I do have both

**Comment by TcePrepK** [comment]
It is just hard there isn't anything impossible about it

**Comment by dhulsman889** [comment]
but the square on the bottom left is smaller and I dont know how to make it

**Comment by TcePrepK** [comment]
Come to discord we can help you there. And please close this issue https://discord.gg/SUarVX38

**Comment by dhulsman889** [comment]
ok will do

**Comment by EmeraldBlock** [comment]
you might want to close this issue (you seem to have also gotten the trick already)
