### ISSUE TITLE
lag and performance

### ISSUE THREAD

**Issue by Mattisonfire511** [tobspr/shapez.io#987]
i know the lag and overall performance was fixed. but its still lagging at higher levels. my laptop has an rtx2060 and at lvl 27 it gives me 20 fps. and i cant delete any more buildings because every building is for upgrades. i dont even have an everything machine!
![shapez io Standalone 2020-11-12 4_06_27 PM](https://user-images.githubusercontent.com/74126804/99007244-0d1afe80-2501-11eb-9436-c194d370084e.png)

![shapez io Standalone 2020-11-12 4_07_19 PM](https://user-images.githubusercontent.com/74126804/99007323-36d42580-2501-11eb-9787-45b467b018b7.png)

**Comment by EmeraldBlock** [comment]
Please remember, this game is written in JS! That means it's on the slow side and can't take advantage of multithreading. Not sure if this can really constitute an issue, and it's also a pretty vague one
