### ISSUE TITLE
Painter (quad) speeds seem to be off.

### ISSUE THREAD

**Issue by comrade1809** [tobspr/shapez.io#989]
Quadpainter at level 23 seems off.
I'm making a teal color with 5 color mixers at 3.2 items/sec, which equals 16 items/sec.
The Painter(quad) processes 8 items/sec, so my thought is that the set of 5 color mixers should be more than enough to supply it with color, but it isn't. The set of 5 color mixers provides enough paint for the Painter(quad) to go at half speed. I needed to add another set of 5 color mixers to get it to 8 items/sec.
Please see the pictures below.

![painter_bad](https://user-images.githubusercontent.com/26911188/99131715-b842bb00-25c8-11eb-85d8-4b7ac5156adb.png)

![painter_good](https://user-images.githubusercontent.com/26911188/99131722-bd076f00-25c8-11eb-931c-470786b6724e.png)

Am I doing something wrong or is there something wrong with the painter(quad)?

**Comment by EmeraldBlock** [comment]
My guess would be that the belts simply don't restock as quickly as the quad paint runs (it's blazingly fast, and the input colors need to travel like 4 tiles)

**Comment by comrade1809** [comment]
I thought that as well, and split up the lines individually. The outcome was still the same.

**Comment by EmeraldBlock** [comment]
oh right, don't forget that you need 4x as much color, did you account for that?

**Comment by comrade1809** [comment]
Then it does make sense. Each paint section needs 8 paint/sec, making it 32 paint/sec for all 4 sections to be colored.
That was my miscalculation.
