### ISSUE TITLE
Editing & Rights questions

### ISSUE THREAD

**Issue by darkwater4213** [tobspr/shapez.io#997]
I was ~~playing~~ beta testing this game a few weeks ago when I realized that the wires layer and its various features would be perfect for a school project that has to do with digital logic. I have already forked this repository, and was wondering if I could get some help editing the code so that the shapes themselves are completely removed; only the wire layer remains (preferably without the green tint). I was also hoping to add a delay/capacitor building and would like help with that, too. If anyone is willing to teach me (I can code, I'm just not very good at it and don't have a lot of experience).

My other question is about rights: I would credit @tobspr regardless, but the main question is whether I could distribute this (Circuits.io?) legally, or do I need to obtain some sort of license? Any feedback would be great. Thank you!

**Comment by tobspr** [comment]
I would recommend to check out something like logisim or instead, which is actually built for that, because you'd also need the sandbox mode and other stuff. Getting rid of all this is quite a bunch of work.

**Comment by darkwater4213** [comment]
Okay, then. I personally like the graphics of Shapex.io better, but I have taken a look at Logisim and think it will work. Thank you though!
